### ISSUE TITLE
Can an existing PDF be used as a template?

### ISSUE THREAD

**Issue by jemminger** [gettalong/hexapdf#1]
In older versions of Prawn (0.12) you could start with an existing PDF as a template, and add text/etc on top of it.  Does/will hexapdf support this?

**Comment by gettalong** [comment]
FYI: The [prawn-template](https://github.com/prawnpdf/prawn-templates) gem should work with the latest Prawn version again.

As for HexaPDF:

* Yes, this works out of the box. You can find an example on the [hexapdf website](http://hexapdf.gettalong.org/examples/show_char_bboxes.html) where this functionality is used.

* Also note that HexaPDF allows using a page from a PDF file like an image, thus having access to a vector graphics format (besides the lossless PNG and the lossy JPEG format).

* It is possible to have three canvas for a page: The main canvas where all the drawing operations would be done or which represents an existing page. And their is a canvas for an overlay and one for an underlay. See http://hexapdf.gettalong.org/api/HexaPDF/Type/Page.html#method-i-canvas

**Comment by jemminger** [comment]
Fantastic, thanks!

**Comment by Nakilon** [comment]
> * Yes, this works out of the box. You can find an example on the [hexapdf website](http://hexapdf.gettalong.org/examples/show_char_bboxes.html) where this functionality is used.

Can't find it now.

**Comment by gettalong** [comment]
@Nakilon This is the correct link. The example uses an existing PDF, parses it's content and display borders around the characters. It only adds vector graphics on top but you can do anything, text, images, ....
