### ISSUE TITLE
Load A3 document

### ISSUE THREAD

**Issue by Genie23** [gettalong/hexapdf#100]
Hello,

I try to load a A3 pdf document with this code :
```
require "hexapdf"

files = [
	"a4.pdf",
	"a3.pdf"
]

files.each do |file|
	source = HexaPDF::Document.open(file)
	puts "- #{file} :"
	(0...source.pages.count).each do |i|
		page = source.pages[i]
		puts "\t- Page #{i + 1} : #{page.inspect}"
	end
end
```

but, the a3 document display 3 pages (when he only has one). How can I load an A3 document correctly ?

**Comment by gettalong** [comment]
Can you provide the PDF in question? Otherwise it is hard to diagnose the problem.

What I *can* say is that the code path doesn't distinguish between paper sizes.

**Comment by Genie23** [comment]
You were right, it came from the PDF file, which, contrary to what I thought, was on 3 pages and not one. Thank you for your help.
