### ISSUE TITLE
Typo in acro_form/form.rb definitions

### ISSUE THREAD

**Issue by iSunRise** [gettalong/hexapdf#102]
Hello,

it seems that `Ressources` is a typo here:
https://github.com/gettalong/hexapdf/blob/8b0d84b68f3475c91df9a0913b40b4bf5e16d528/lib/hexapdf/type/acro_form/form.rb#L59

But I'm not 100% sure since I've seen "Ressources" word in pdf structure before (mostly in render errors).

Thanks

**Comment by gettalong** [comment]
Thank you - you are right, that is an error, coming from me having German as mother tongue where "Ressourcen" is a proper word.

Will fix for the next release!

**Comment by gettalong** [comment]
Fixed it now - thanks again!
