### ISSUE TITLE
Canvas overlay adds content under some objects

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#104]
We sometimes have problems with PDFs where our added content shows up under certain PDF objects even though we're using `page.canvas(:type => :overlay)`

Here's a screenshot: https://share.getcloudapp.com/5zu1NApX

Here's the example source PDF: https://share.getcloudapp.com/xQuW6npZ

Test code for duplicating the issue with that PDF:

    pdf = HexaPDF::Document.new(io: open('/SOME_PATH/door-example.pdf'))
    font = pdf.fonts.add('/SOME_PATH/OpenSans-Regular.ttf')
   
    pdf.pages.each do |page|
      overlay = page.canvas(:type => :overlay)
      box = page.box(:media)
      fragment = HexaPDF::Layout::TextFragment.create("THIS IS SOME TEST TEXT", font: font, font_size: 40)
      layouter = HexaPDF::Layout::TextLayouter.new(align: :left, font: font)
      result = layouter.fit([fragment], box.width - 300, box.height)
      result.draw(overlay, 100, 350)
    end

    pdf.write('/SOME_PATH/final.pdf')

**Comment by gettalong** [comment]
I have looked at your example source PDF. The reason the images are shown above everything else is that those images are not part of the page content itself but are annotations. Those will always show up on top of everything, like form fields.

In order for this to work, you would need to make the annotations part of the page content; sometimes known as flattening the annotations.

Alas, this is something that HexaPDF cannot do, yet. However, I'm currently working on support for forms which also use annotations. I will read up on annotations to see how much work flattening would be.

**Comment by earthlingworks** [comment]
Interesting. Yeah, this comes up pretty often for us and I don't think people are aware that that's what they're doing. Would be great if you're able to add flattening! Hope you find that it's something that's doable - thanks!

Ruben
------------------------
Founder, http://www.bidsketch.com
Twitter: http://twitter.com/bidsketch

**Comment by gettalong** [comment]
I have looked at the spec and it should be doable. It *might* involve a lot of work if the application that generated the PDF didn't add an "appearance stream", i.e. the visual representation of the annotation, since then HexaPDF has to use the information in the annotation to create the visual representation.

**Comment by earthlingworks** [comment]
That's great to hear. Thanks for following up!

Ruben
------------------------
Founder, http://www.bidsketch.com
Twitter: http://twitter.com/bidsketch

**Comment by gettalong** [comment]
@earthlingworks I have implemented now all changes for this to work in most cases (e.g. if the annotations already contain the necessary appearances) - see the [devel branch](https://github.com/gettalong/hexapdf/tree/devel). There will be a new release this week with the fixes.
