### ISSUE TITLE
How to extract text?

### ISSUE THREAD

**Issue by egibney** [gettalong/hexapdf#106]
I apologize if this isn't the place for this, but none of the documentation I've found online for HexaPDF outlines how to extract text from a PDF.

For example, this page outlines how to do pretty much everything other than extract text:
https://hexapdf.gettalong.org/documentation/reference/hexapdf.1.html#examples

Is text extraction possible with HexaPDF? If so how do I do it?

Thank you

**Comment by gettalong** [comment]
Text extraction works in the sense that the individual characters/words can be extracted from the PDF document, see example https://hexapdf.gettalong.org/examples/show_char_bboxes.html

However, this kind of extraction works only if the application creating the PDF has laid out the data in a meaningful way. For text extraction to reliably work in many more cases, semantic analysis of the extracted characters and their position has to be done but this is currently not implemented in HexaPDF. This is also the reason why there is no "extract_text" CLI command available.

So: For easy cases it will work acceptably but in the general case it won't.

**Comment by egibney** [comment]
Thank you for this response @gettalong . Much appreciated :)
