### ISSUE TITLE
Installing from source raises error loading rake from hexapdf.gemspec

### ISSUE THREAD

**Issue by beneggett** [gettalong/hexapdf#108]
I'm getting an issue from our CI server complaining about the presence of `require rake` in the gemspec when installing from source

```
Fetching https://github.com/gettalong/hexapdf.git

[!] There was an error while loading `hexapdf.gemspec`: cannot load such file -- rake

Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.
 #  from /home/circleci/franklin_covey/vendor/bundle/ruby/2.6.0/bundler/gems/hexapdf-e0c00752aa0d/hexapdf.gemspec:1
 #  -------------------------------------------
 >  require 'rake'
 #  require_relative 'lib/hexapdf/version'
 #  -------------------------------------------
Exited with code exit status 14 
CircleCI received exit code 14
```

I'm not sure why we would need to `require rake` in the gemspec at all, I presume to use `FileList` ? If so, consider adding as a development dependency as the rake tests seem to be about cutting gems, publishing  documentation & appending licensing info

Please advise, happy to submit a PR removing the line if helpful

**Comment by gettalong** [comment]
I guess it won't help adding rake as a development dependency because CircleCI would only know about the dependency once the gemspec is parsed, but it raises an error on line 1...

**Comment by beneggett** [comment]
Yes, I think you're correct. 

I think you could swap out  `FileList.new`  for `Dir.glob` and achieve the same results without the dependency. I will test real quick and see if it causes the same issue

**Comment by beneggett** [comment]
It seems to work, and satisfies the CI server

```
require 'rake'
PKG_FILES = FileList.new([
                           'bin/*',
                           'lib/**/*.rb',
                           'data/**/*',
                         ])
PKG_FILES_DIR = Dir.glob([
                           'bin/*',
                           'lib/**/*.rb',
                           'data/**/*',
                         ])

PKG_FILES.to_a.sort == PKG_FILES_DIR.to_a.sort
# => true 
```

**Comment by beneggett** [comment]
Sorry to create a typically "non-issue" out of this; it was never my intention

**Comment by beneggett** [comment]
A note for future eyes, we understand not to install from `master`  branch in any sort of  production environment, it is better to wait for a proper release. 

However, testing against CI in a development build revealed an unnecessary dependency at gem load time which could be easily mitigated

**Comment by beneggett** [comment]
If you are insterested in a PR,  here is the base for it: https://github.com/gettalong/hexapdf/compare/master...beneggett:master

**Comment by gettalong** [comment]
@beneggett Thank you testing this out!

**Comment by gettalong** [comment]
I have looked through the rake source code to see what's going on with `FileList` and it basically defers to `Dir.glob` in the end. I have just pushed the changes to Github.
