### ISSUE TITLE
Nested text not recognised in content processor

### ISSUE THREAD

**Issue by danyill** [gettalong/hexapdf#109]
In the attached file there is text which is selectable and looks like a normal text content but I cannot process using the example given https://hexapdf.gettalong.org/examples/show_char_bboxes.html. I'm not sure if I need to take a more sophisticated approach to processing or if I am hitting a limitation.

I _think_ this is because each glyph is separate text content "nested" underneath a parent element.

This is what I see when I inspect it using a PDF viewer

![image](https://user-images.githubusercontent.com/674783/83195468-5fa07280-a18e-11ea-9901-a176593d193e.png)

Whereas on a "more normal" text content I see the full text line in each child element.

![image](https://user-images.githubusercontent.com/674783/83195723-c9b91780-a18e-11ea-9c9a-e55aebe6b684.png)

I'm wondering if there is some kind of off by one error that I don't see the text value for each character in the first case when I process using https://hexapdf.gettalong.org/examples/show_char_bboxes.html

Here's an example file showing this case:

[Example_AutoCAD_Inventor_Text.pdf](https://github.com/gettalong/hexapdf/files/4698338/Example_AutoCAD_Inventor_Text.pdf)

I think I am making a feature request for the `HexaPDF::Content::Processor` to be able to read text encoded in this manner but I confess to a relative weak understanding of how this works in the pdf spec, in hexapdf and in this file (my `hexapdf inspect` has not been very successful) and I may just be requesting a little guidance. :facepalm:

Thank you for this tool.

**Comment by gettalong** [comment]
When I try to run the "show character boxes" example on your sample PDF, it gives me an error because the Unicode mapping is missing for the embedded font. So in general, it is not possible to extract the text there.

As for "text as character by character": How a text is layed-out in a PDF is completely defined by the conforming PDF writer itself. So it would also be possible to start at the last character and work your way to the front while still maintaining the same appearance.

**Comment by danyill** [comment]
You are quite right, I had suppressed the error in my own code. I think that is where the problem lies and I must look into the way the writer works in more detail to see if I can configure this correctly.

**Comment by danyill** [comment]
Thank you so much for looking into this.
