### ISSUE TITLE
Support for embedding PDF images via canvas API?

### ISSUE THREAD

**Issue by gioele** [gettalong/hexapdf#11]
Could HexaPDF embed PDF images in the same way in which raster images are embedded in generated PDF?

It would be nice to be able to do

    canvas.image("foo.pdf", at: [350, 0], height: 80)

or

    canvas.pdf("foo.pdf", page: 1, at: [350, 0], height: 80)

This feature would give HexaPDF support for vector images, a point of differentiation from Prawn, see prawnpdf/prawn#1020.

**Comment by gettalong** [comment]
@gioele It already does :wink: - see https://hexapdf.gettalong.org/api/HexaPDF/ImageLoader/PDF.html.
