### ISSUE TITLE
Nil password issue with NitroPDF

### ISSUE THREAD

**Issue by DangerDawson** [gettalong/hexapdf#110]
One of our clients uses a pdf viewer called:
[NitroPDF](https://www.gonitro.com/em/sem/nitro-pdf-software?gclid=EAIaIQobChMIjO_Y4LL86QIVie3tCh0nfgGGEAAYASAAEgI9vPD_BwE)

When they try to view a pdf that has been created using the following encryption options:

```
{
  algorithm: :aes,
  password: nil,
  permissions [:print]
}
```
(ensure a pdf can only be printed and prevent copy and paste etc.)

They are prompted for a password and even if you supply an empty string it does not allow you to proceed, this is a different behaviour to adobe viewer which does not prompt you for a password.

Am I doing something incorrectly with the permission options?

**Comment by gettalong** [comment]
I don't think so, your encryption options look fine to me. After trying a few things with different PDF viewers I have available on my system, I didn't hit any problems.

The encryption options you use should result in a PDF file with security handler version 4, key length of 128 bits, and a PDF version of at least 1.5. Can you verify that with `hexapdf info INPUT.PDF`. It should look similar to this:

~~~
File name:          /tmp/test.pdf
File size:          50674 bytes
Creator:            cairo 1.9.5 (http://cairographics.org)
Producer:           HexaPDF version 0.11.8
ModDate:            2020-06-12 21:12:29 +0200
Encrypted:          yes (version: 4, key length: 128bits)
  String algorithm: aes
  Stream algorithm: aes
  EFF algorithm:    aes
  Permissions:      print
Pages:              1
Version:            1.5
~~~

Could you also provide the answers to the following questions that may pinpoint the problem:

* Does it work correctly if a password is set?
* Does it work correctly for other permission arrays?
* Does it work when using a different source PDF?
* Do you use the `optimize: true` option when writing the secured PDF? If so, does it work when not optimizing the file?

**Comment by DangerDawson** [comment]
After testing:

- Does it work correctly if a password is set?
- Does it work correctly for other permission arrays?
- Does it work when using a different source PDF?
- Do you use the optimize: true option when writing the secured PDF? If so, does it work when not optimizing the file?

None of the above made a difference, I also tried changing the encryption algorithm and that did not help either.

The only thing that allows the pdf to render without the password prompt, is to not encrypt the document.

**Comment by gettalong** [comment]
Thanks for investigating further!

Could you please try the following files and see if they open fine:

* [simple.pdf](https://github.com/gettalong/hexapdf/files/4779679/simple.pdf) - Simplest document to create with HexaPDF, i.e. `HexaPDF::Document.new.write('out.pdf')`.
* [simple-encrypted.pdf](https://github.com/gettalong/hexapdf/files/4779680/simple-encrypted.pdf) - Like above but with a call to `Document#encrypt`
* [simple-encrypted-perms.pdf](https://github.com/gettalong/hexapdf/files/4779683/simple-encrypted-perms.pdf) - Like above but with the additional `permissions: [:print]` given
* [simple-encrypted-other.pdf](https://github.com/gettalong/hexapdf/files/4779681/simple-encrypted-other.pdf) - The `simple.pdf` encrypted with a different tool.

**Comment by DangerDawson** [comment]
The first and fourth where fine, the second and third were not.

Dave

**Comment by gettalong** [comment]
Thanks for testing!

I have looked at the differences between HexaPDF's output and the working one. Here are two test files again, each with a different structure to see what Nitro trips up on:

* [simple-encrypted.pdf](https://github.com/gettalong/hexapdf/files/4780350/simple-encrypted.pdf) - this adds the `/Length` key to the encryption dictionary although that is optional and not required for the specific encryption dictionary in question
* [simple-encrypted2.pdf](https://github.com/gettalong/hexapdf/files/4780351/simple-encrypted2.pdf) - this makes the encryption dictionary an indirect object, again not a requirement

All other differences between the second and fourth file should be irrelevant.

**Comment by DangerDawson** [comment]
First one prompts for a password, the second one does not (it works), although the document is blank, which is intentional?

**Comment by gettalong** [comment]
Yes, the document is just the smallest possible PDF document possible, so just a page with no content.

Thanks for testing this out!

Since the second one works I will change HexaPDF so that the encryption dictionary will always be an indirect object.

**Comment by DangerDawson** [comment]
Really appreciate your efforts in getting to the bottom of this.

**Comment by gettalong** [comment]
Version 0.11.9 with the needed change has just been released!
