### ISSUE TITLE
Is there a plan to support JBIG2Decode?

### ISSUE THREAD

**Issue by DangerDawson** [gettalong/hexapdf#111]
We use HexaPDF to manipulate and merge Pdf documents together, although if a PDF contains an image which uses the 'JBIG2Decode' filter I receive the following error message:

Unknown stream filter 'JBIG2Decode' encountered

Is there a plan to support this filter? if not would you be able to suggest a workaround e.g. preprocess the image with a given tool to convert the images

**Comment by gettalong** [comment]
It depends on what you exactly mean by "supported". Most of the filters are fully supported in the way that retrieving the unfiltered data works.

However, some filters like [DCTDecode](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/filter/dct_decode.rb#L40) (which, in essence, is responsible for parsing a JPEG picture and returning all the pixels; and the other way around) are only implemented as pass-through filters.

Filters implemented in this way will work normally until you want to retrieve and work with the pixel values.

So, if you don't actually do anything with the image implementing the JBIG2Decode as pass-through should work as expected. You can try this out by passing `'filter.map' => {JBIG2Decode: 'HexaPDF::Filter::DCTDecode'}` in the configuration hash for `HexaPDF::Document.new`:

~~~
doc = HexaPDF::Document.new(config: {'filter.map' => {JBIG2Decode: 'HexaPDF::Filter::DCTDecode'}})
~~~

If this works for your use-case I will update the default configuration for the next release to include this change.

**Comment by DangerDawson** [comment]
First of all thank you for getting back to me so quick.

And yes that worked... fantastic!!!!

**Comment by gettalong** [comment]
No problem! :smile: 

Great that it works, then I will include that in the upcoming release!

**Comment by gettalong** [comment]
Implemented and will be in the next release.
