### ISSUE TITLE
Weird placement position issue with text on a specific PDF

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#114]
We're having a very weird issue on a PDF with placing text doesn't match the location we're using. Any other PDF this size with the same code, places the text/content in the correct location. This one PDF gets the content placed lower down (always) than all the other PDFs. (Same size and code)

Here's a screenshot of the problem PDF (number 1) and a normal PDF (number 2) with the same text on the bottom left hand corner: https://share.getcloudapp.com/DOux9YyY 

PDF number 1 download: https://share.getcloudapp.com/2NuyjDZ7

PDF number 2 download: https://share.getcloudapp.com/2NuyjDZL

The code:

    pdf = HexaPDF::Document.new(io: open('[path to file]/test-size.pdf'))
    font = pdf.fonts.add('/fonts/OpenSans-Regular.ttf')
   
    pdf.pages.each do |page|
      overlay = page.canvas(:type => :overlay)
      box = page.box(:media)
      fragment = HexaPDF::Layout::TextFragment.create("THIS IS A TEST", font: font, font_size: 10)
      layouter = HexaPDF::Layout::TextLayouter.new(align: :left, font: font)
      result = layouter.fit([fragment], box.width - 300, box.height)
      result.draw(overlay, 0, 20)
    end

    pdf.write('[path to file]/test-size-out.pdf', update_fields: true, validate: false, optimize: true)

Any idea what could be going on here?

**Comment by gettalong** [comment]
The media box on the first PDF has its lower left corner not at (0, 0) but at (-11.9622, 11.99606), see `hexapdf inspect pdf1.pdf 18`.

The width/height of the box will be correctly computed but for HexaPDF the origin still resides at (0, 0). So this is most definitely a bug, will have to see how to best solve this (most probably by moving the origin on canvas creation).

Thanks for reporting!

**Comment by gettalong** [comment]
@earthlingworks I have pushed a fix to the devel branch - please try this out. I have gone with moving the canvas origin to the bottom left corner.

If this fixes your problem, I will make a proper release.

**Comment by earthlingworks** [comment]
@gettalong Nice! Just tried it and it works great.

**Comment by gettalong** [comment]
Thanks - will do a proper release later!

**Comment by gettalong** [comment]
@gettalong New version 0.12.2 with fix released!
