### ISSUE TITLE
Question: Extract Stream to file?

### ISSUE THREAD

**Issue by sixtyfive** [gettalong/hexapdf#122]
After playing around with the API and the CLI and browsing the docs, I can't seem to find anything about this. Apologies if I just missed the information. Does hexapdf provide any way of extracting a character stream from a PDF?

Use case: I've read through the output of `r` and found that `5` is the object I'm interested in. It happens to be written in a non-latin script, though, so `s 5` isn't very helpful. At this point my expectation was that there'd be something like `d(ump) 5 "5.txt"` which I could then have opened with my favourite text editor of the day.

**Comment by gettalong** [comment]
From what you write I guess you don't want a "stream" as defined by the PDF but the text of a page? If this is the case, this is a bit more involved because in most cases semantic information is not preserved when creating a PDF. So the PDF library must stitch together the characters to form (at least) lines, sometimes even words. This is not something that HexaPDF has built-in right now, do it is doable with what is already there.

**Comment by sixtyfive** [comment]
> From what you write I guess you don't want a "stream" as defined by the PDF but the text of a page? If this is the case, this is a bit more involved because in most cases semantic information is not preserved when creating a PDF. So the PDF library must stitch together the characters to form (at least) lines, sometimes even words. This is not something that HexaPDF has built-in right now, do it is doable with what is already there.

Yes-ish. I want the list of characters as they would be rendered by, say, Evince, according to their x-y-coordinates on the page, including spaces between them larger than so-and-so-many pixels on the x axis interpreted as ` `, and changes larger than so-and-so-many pixels on the y axis interpreted as `\n`.

If I understand you correctly, getting the list of characters and their x-y-coordinates is possible using hexapdf, but it has no algorithm to turn the characters into words and paragraphs, which is the part I'll have to do myself. Is that accurate?

**Comment by gettalong** [comment]
Yes, that is accurate. Have a look at https://hexapdf.gettalong.org/examples/show_char_bboxes.html where you can find an example for how to get the positions of the characters.

On issue https://github.com/gettalong/hexapdf/issues/18 you will find some more information regarding this.

**Comment by sixtyfive** [comment]
These help greatly. Thank you, @gettalong!
