### ISSUE TITLE
Simply copying existing page to new PDF?

### ISSUE THREAD

**Issue by 9mm** [gettalong/hexapdf#126]
I'm looking at this example https://github.com/gettalong/hexapdf/blob/master/examples/005-merging.rb

All I want to do is loop through a PDF, and every other page I want to create a NEW pdf using just that page I'm on. I want the filenames to just be 1.pdf, 2.pdf, 3.pdf etc (its a 5000 page document).

When I try to do this though: `target.pages << target.import(page)` it seems to be not adding an actual NEW page, first of all its just overwriting the existing page or something, and on top of that its not actually using the filename i specify, and its not creating a new PDF. im super confused by the code below just keeps modifying/creating a file that doesnt even match the filename I specify:

```
@new_pdfs.each do |pdf|
  target = HexaPDF::Document.new

  pdf.each do |page|
    target.pages << target.import(page)
  end

  target.write("#{filename}.pdf", optimize: true)

  @filename += 1
end
```

@new_pdfs comes from this: `HexaPDF::Document.open(filename)`

**Comment by 9mm** [comment]
its actually doing it correctly except why the heck is it not using the filename i specify, it keeps overwriting a filename and i dont even know where that is coming from, its like its parsing the filename from the last page i import...... and then ignoring it in the argument

**Comment by gettalong** [comment]
Can you provide the full code? Because `@filename` is used at the bottom but never initialized and `filename` (either a local variable or method) is called in the `HexaPDF::Document#write` method.

Also: You said you want to loop through the pages of a single PDF. However, you are looping through `@new_pdfs` (an array of PDF files) *and* through their pages.

**Comment by 9mm** [comment]
jesus im an idiot, i fat-finger deleted the instance variable itno local variable and it was using that

KILL ME........... still thinking about GME 🚀
