### ISSUE TITLE
Fast way to "search" or render the text of a document?

### ISSUE THREAD

**Issue by 9mm** [gettalong/hexapdf#127]
Is there a way I can "render" the text of a document to a string?

I understand it would be extremely hard to make a _sensible_ output considering PDFs are more like layers, but really the only thing I need to do is search the document for an occurrence of a piece of text. I don't care if I get a big messy jumble of text, I just need to check for it's presence.

I'm currently using `pdf-reader` to do this step but it takes _FIVE_ seconds per page to render............wtf

**Comment by gettalong** [comment]
This is currently not built-in but you can do it yourself by analyzing the position of the characters and assembling them into words and lines. The example https://hexapdf.gettalong.org/examples/show_char_bboxes.html shows you how to get the basic text fragments which would need to be assembled.

Also search the issue tracker - there were some similar questions already.
