### ISSUE TITLE
form problem

### ISSUE THREAD

**Issue by dsisnero** [gettalong/hexapdf#133]
when I run hexapdf form on a pdf I get Problem encountered.

 Dominics-iMac:forms dominic$ hexapdf form clearance.record.form.pdf
Page 1
  document_type
    └─ "90% Engineering Transmittal"
  id_number
    └─ nil
  budget_impact
    └─ false
  title
    └─ "NEXCOM Radio Replacement"
  name
    └─ "Dominic Sisneros"
  routing
    └─ "AJW-2W13B"
  phone
    └─ nil
  cell
    └─ "801-558-1966"
  summary
    └─ "The Engineering Transmittal for the NEXCOM radio replacement at SLCD RTR is attached. This project will upgrade electronic equipment associated with the SLCD RTR located at the Salt Lake International Airport in Salt Lake City, UT. The project is currently scheduled to start on 11/1/2017, and end on or before 12/15/2017.  Please return a signed clearance record (with comments attached) to Dominic.E.Sisneros@faa.gov. Please call the phone number listed above if you have any questions or if you would like to complete this review by phone.\r"
  approving_official_routing
    └─ nil
  approving_official_signature
Problem encountered: undefined method `field_value' for #<HexaPDF::Type::AcroForm::Field [394, 0] value={:AP=>{:N=>#<HexaPDF::Reference [58, 0]>}, :DA=>"/Helv 0 Tf 0 g", :F=>4, :FT=>:Sig, :MK=>{}, :P=>#<HexaPDF::Reference [31, 0]>, :Rect=>#<HexaPDF::Rectangle [0, 0] value=[207.0, 489.649, 384.0, 511.0]>, :Subtype=>:Widget, :T=>"approving_official_signature", :Type=>:Annot}>
Did you mean?  field_name

**Comment by gettalong** [comment]
The `approving_official_signature` field is a signature field which is not yet implemented. I will provide a basic implementation for the next release.

**Comment by gettalong** [comment]
@dsisnero This is now implemented and will be in the next release. Note that it is not possible to fill out a signature field, yet.
