### ISSUE TITLE
Question: How to define a spot color/CutContour

### ISSUE THREAD

**Issue by silikone** [gettalong/hexapdf#134]
Hi,

I'm looking into using HexaPDF to generate a lot of automatic print materials.
I need to define a 'CutContour' to indicate where the printers are to cut the materials.

For a quick brush up on CutContour check this:
https://www.prigraphics.com/wp-content/uploads/2014/04/How-to-Prepare-Contour-Cut-Jobs.pdf

As far as I see this, it is a named color(Spot Color) that is used to draw a shape to indicate where the cutting is to happen.
Ideally placed on a separate layer from the rest of the graphics/text.

Is there a way to create this in HexaPDF??

/S

**Comment by gettalong** [comment]
There are currently no built-in convenience methods for creating this. However, it can be done with HexaPDF.

If you'd provide a small sample input file before and after the cut contour has been added, I can provide you with the necessary steps to automate this.

**Comment by silikone** [comment]
Hi,

Thanks for the response.

Would love to tak you up on the offer.

Here is a PDF with just a cutContour defined. Let me know if you need anything else


/S


On 26 Mar 2021, at 17.58, Thomas Leitner ***@***.*** ***@***.***> > wrote:


There are currently no built-in convenience methods for creating this. However, it can be done with HexaPDF.

If you'd provide a small sample input file before and after the cut contour has been added, I can provide you with the necessary steps to automate this.

**Comment by gettalong** [comment]
@silikone There is no PDF attached in your comment.

**Comment by silikone** [comment]
Sorry - missed the file
[CutContour_only.pdf](https://github.com/gettalong/hexapdf/files/6218466/CutContour_only.pdf)

**Comment by gettalong** [comment]
@silikone Thanks for the file. Following is a minimal example:

~~~ ruby
require 'hexapdf'

doc = HexaPDF::Document.new
canvas = doc.pages.add.canvas
# The following lines define the separation color space
space_definition = [:Separation, :CutContour, :DeviceCMYK,
                    {C0: [0.0, 0.0, 0.0, 0.0], C1: [0.0, 1.0, 0.0, 0.0], Domain: [0, 1],
                     FunctionType: 2, N: 1.0, Range: [0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]}]
cut_contour_space = HexaPDF::Content::ColorSpace::Universal.new(space_definition)

# Usng cut_contour_space.color you can select the needed tint for the cut contour
canvas.stroke_color(cut_contour_space.color(1.0))
# Then use the appropriate path construction operators to define your contour
canvas.rectangle(10, 10, 400, 700).stroke

doc.write('/tmp/cutting.pdf')
~~~

Let me know if that works for you!

**Comment by gettalong** [comment]
@silikone Since I think this is resolved, I will close the issue. Let me know if this is not the case - thanks.
