### ISSUE TITLE
Encryption and Permissions

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#135]
We're trying out the encryption and permission features and I noticed that if we're not able to restrict to readonly/print permissions.

Setting any PDF to `permissions [:print]` seems to work at first, but then I can simple open it with Acrobat Reader and go to "Permission Details" (after clicking on the security settings) and remove the security settings like this: https://share.getcloudapp.com/v1ubR5OW

Also, is there a way to digitally sign PDFs? I found an issue a couple of years ago that mentioned that it wasn't supported yet but that's about it, so wanted to verify.

**Comment by earthlingworks** [comment]
One more thing: I noticed that even with just print permissions enabled, if I open the PDF (any PDF with print permissions enabled through HexaPDF) and right click -> Edit text & images, it prompts for a password. If I just hit enter it accepts the empty password and allows me to modify the contents. 

If I try to add password, it won't let me open the PDF without the password, which isn't really what we're intending to do. Basically, we're just looking to make PDFs readonly with the ability to print and select/copy the text.

**Comment by gettalong** [comment]
* You are not using Adobe Reader but Adobe Acrobat Pro to disable the encryption/permissions. And Acrobat Pro  is able to edit PDFs. So this is expected to work.

* Have you set a password when setting the permissions? You can set a user password and/or an owner password. If you just set the owner password, then a user can open the PDF without password but the restrictions are still in place. If you use a user password, the user has to enter the password to be able to see the contents. Note that if just an owner password is set any PDF editing software (also HexaPDF) can just disable the encryption/permissions. If you don't set any password but just the permissions,  the empty password is used.

* Digitally signing PDFs is on my TODO list for one of the next releases. Working AcroForm and annotations were a prerequisite for that. There is another issue here (#133) which also needs the signature field to be implemented (at least in a basic version).

**Comment by earthlingworks** [comment]
Hey Thomas, gotcha, so even if we did it at the owner level, it's still not going to be truly a readonly document for everyone on any tool. Seems like the best bet will be to just do digital signing on our end. 

Ok, thanks for the quick reply! Note: we'll be looking to do LTV (long term validation) on digital signatures. Looking at iText (Java library) but not ideal given our environment does not use Java.

**Comment by gettalong** [comment]
Thanks, I will look up LTV!

Using the owner password is good for normal users but not for power users as it whole depends on their knowledge of PDFs (or their PDF editor).

As far as I know the [Ruby Origami library](https://github.com/gdelugre/origami/) can do signatures. You might want to have a look at that until this is implemented in HexaPDF.

**Comment by gettalong** [comment]
@earthlingworks Status update: Digital signatures can now be created that are LTV enabled, meaning if some additional data is added, it would be an LTV signature.

**Comment by earthlingworks** [comment]
That's awesome! Appreciate the updates here

**Comment by gettalong** [comment]
Forgot to mention the docs: https://hexapdf.gettalong.org/documentation/digital-signatures/signing-pdfs-howto.html#applying-a-pades-signature

The [introduction to digital signature support](https://hexapdf.gettalong.org/documentation/digital-signatures/index.html) has also been overhauled.

PAdES level B-T signatures should show up as LTV enabled.

**Comment by earthlingworks** [comment]
Ok, thanks!

**Comment by gettalong** [comment]
@earthlingworks Although this has not been implemented in HexaPDF itself (yet), have a look at https://github.com/gettalong/hexapdf/discussions/201#discussioncomment-6265253 to see how to go from a PAdES B-T to a full LTV signature.

This was the last bit missing for this issue here. Providing an easy way to add that LTV information using HexaPDF is on my ToDo list.
