### ISSUE TITLE
Issue with opening s3 url based files

### ISSUE THREAD

**Issue by munib-concord** [gettalong/hexapdf#136]
I want to merge a file that is places on s3 bucket and when i try to open that file using hexapdf it returns no pdf error although the file is there and all access is public. 
 HexaPDF::Document.open(url)
Errno::ENOENT: No such file or directory @ rb_sysopen https://s3.xyz.com/etc

Can't we open s3 file using hexapdf ?

**Comment by gettalong** [comment]
See issue #131 - you need to provide either a file or an IO object to `HexaPDF::Document.open`.
