### ISSUE TITLE
"No Unicode mapping"

### ISSUE THREAD

**Issue by sixtyfive** [gettalong/hexapdf#137]
Hi, I've been trying to work with some Persian and Arabic PDFs and keep running into https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/configuration.rb#L415 ("No Unicode mapping for code point 1234 in font so and so"). Is there any way that hexapdf can be told to just output a warning but otherwise keep going? (Which I guess carries the risk of ending up with blank in the output file, but that'd be okay). Or will it require working with a monkeypatched version?

**Comment by gettalong** [comment]
The code you point to is part of the configuration that allows you to customize the response of HexaPDF in certain situations. In this case, you can customize how HexaPDF responds if a character code cannot be converted to an UTF-8 character when reading the contents of a page.

By setting the `font.on_missing_unicode_mapping` configuration option (see https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/configuration.rb#L270-L277 and https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Document/index.html#method-c-new) you can output a warning and return any UTF-8 character.

**Comment by sixtyfive** [comment]
Dankeschön!
