### ISSUE TITLE
Error with flatten_annotations

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#139]
Hello! We're still receiving errors at times with `flatten_annotations` with certain PDFs. 

`ruby test.rb "/path/to/input.pdf"`

```
require 'hexapdf'
​
file = File.open ARGV[0]
document = HexaPDF::Document.new(io: file)
document.pages.each(&:flatten_annotations)
```
I'll send the PDF through email. Thanks!

**Comment by gettalong** [comment]
Thanks for the PDF!

The problem with the file is that there is a completely different object where an appearance stream is expected, e.g. a cross-reference stream instead of a Form XObject.

I have updated HexaPDF to handle such cases and released a bug fix version.
