### ISSUE TITLE
Wiki looks suspicious

### ISSUE THREAD

**Issue by Kjarrigan** [gettalong/hexapdf#141]
@gettalong I just saw a notification in my profile:

![image](https://user-images.githubusercontent.com/310475/119486151-3e01a900-bd58-11eb-8862-f759c5c0e469.png)

and this looks really fishy:

![image](https://user-images.githubusercontent.com/310475/119486257-583b8700-bd58-11eb-8963-6e61b0efa423.png)

**Comment by gettalong** [comment]
Thanks, I have removed the spam pages.
