### ISSUE TITLE
Watermark not working for some files

### ISSUE THREAD

**Issue by thanhtoan1196** [gettalong/hexapdf#143]
Watermark not working for some files
Here is an example: [error_example_file.pdf](https://github.com/gettalong/hexapdf/files/6724071/error_example_file.pdf)

**Comment by gettalong** [comment]
The file is damaged and does not conform to the PDF spec because the cross-reference table has invalid EOL sequences in it.

I will try to find a work-around for this damaged file so that HexaPDF can read it correctly.

**Comment by gettalong** [comment]
Okay, faster than I thought :smile: I found a work-around for dealing with the invalid file which will be in the next release.

**Comment by thanhtoan1196** [comment]
Thank you very much.

**Comment by gettalong** [comment]
@thanhtoan1196 I released 0.15.5 which addresses this problem.
