### ISSUE TITLE
Type1 encoding has no codepoint for lslash

### ISSUE THREAD

**Issue by marcomd** [gettalong/hexapdf#144]
Hello Thomas,

I'm switching from origami to hexa pdf. The specs in which I use names with characters present in the alphabet of those nationalities fail with this a description like this: 

_Type1 encoding has no codepoint for lslash_

The description changes based on the special character in the text.

I have this method to write simple text in a page of a given pdf:

```ruby
def write_sentence(text, pdf, tl, canvas, x, y, width, height, font_family: 'Helvetica', font_size: 10, fill_color: [0, 0, 0], align: :center, valign: :center, variant: nil)
    font = pdf.fonts.add(font_family, variant: variant)
    tl.style.align(align).valign(valign)
    tf = HexaPDF::Layout::TextFragment.create(text, font: font, font_size: font_size)
    tl.fit([tf], width, height).draw(canvas, x, y)
  end
```

When the text contains, for example, 'Izabela Kamila Kukuła'

The spec fails:

```
Failure/Error: tl.fit([tf], width, height).draw(canvas, x, y)

      HexaPDF::Error:
        Type1 encoding has no codepoint for lslash
```

Recap:

If the text contains 'Izabela Kamila Kukuła' -> Type1 encoding has no codepoint for lslash

If the text contains 'Dominik Krajči' -> Type1 encoding has no codepoint for ccaron

If the text contains 'Pavel Pospieszyński' -> Type1 encoding has no codepoint for nacute

If the text contains 'Daividas Bereś' -> Type1 encoding has no codepoint for sacute

If the text contains 'Jeremi Narożny' -> Glyph for "ż" missing

...

Each character seems to generate a different error

**Comment by gettalong** [comment]
This error comes from the fact that the standard encoding used for Type1 fonts, WinAnsiEncoding, doesn't contain an entry for that named character, i.e. 'lslash' or 'ccaron'.

What you can do to overcome this is to use a custom encoding by specifying `custom_encoding: true` when calling `pdf.fonts.add`. This will built up a custom encoding containing only the characters in the PDF.

Please note, though, that the built-in fonts contain many characters used in western countries but there may be characters which aren't available. If you run into this, it would be better to use a TrueType font.

**Comment by marcomd** [comment]
Thank you. It added a custom font that solved. I have not noticed an increase in the size of the pdf.

<img width="592" alt="immagine" src="https://user-images.githubusercontent.com/194608/124456276-cbd6a800-dd8a-11eb-84ec-6889fb796c46.png">

**Comment by gettalong** [comment]
There will be a slight increase in the PDF size but should not be much more than 1K at worst.
