### ISSUE TITLE
Can't set bleedbox

### ISSUE THREAD

**Issue by jcmichaudMarquis** [gettalong/hexapdf#145]
I can't set the BleedBox, it is place with the values of the CropBox no matter what I set it to. I have no problems with the TrimBox, ArtBox, CropBox or MediaBox. What, do you think, I do wrong?
Thank you

**Comment by gettalong** [comment]
How do you set the bleed box? There is a [helper method called `#box`](https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Type/Page.html#method-i-box) on page objects that allows you to set any kind of supported box, e.g. `page.box(:bleed, [0, 0, 100, 200])`.

**Comment by jcmichaudMarquis** [comment]
I set it the same way I do the other boxes

page2pdf.pages[page2][:BleedBox] = bbc

where

page2pdf: hexapdf object
page2 : the actual page where to set the bleedbox
bbc: an array with the coordinates for the box.

It works for all the other boxes but not for the bleedbox.

Thanks

**Comment by gettalong** [comment]
If `page2` is already a valid `HexaPDF::Type::Page` object, you should use it directly and not as index.

Did you inspect the generated PDF file? You can do so using `hexapdf inspect file.pdf po 1`  where `file.pdf` would be the generated file and you would substitute the number `1` for the actual page number. The output should look similar to this:

~~~
2 0 obj
<<
  /Type /Page
  /Parent 1 0 R
  /MediaBox [0 0 595.32 841.92 ]
  /Contents 4 0 R
  /Resources 3 0 R
>>
endobj
~~~

You should see the set `BleedBox` entry there.

**Comment by jcmichaudMarquis** [comment]
In the PDF, opened in BBedit, I get:

5 0 obj
<< /Type /Page /Group
<< /CS /DeviceCMYK /S /Transparency /Type /Group
>> /xb2 612 /yb2 792 /TrimBox
[ 27 27 603 783
] /BleedBox
[ -9 -9 639 819
] /Parent 11 0 R /Resources
<< /XObject
<< /Im0 9 0 R /Im1 16 0 R
>> /Font
<< /T1_0 21 0 R /T1_1 8 0 R
>> /ExtGState
<< /GS0 20 0 R /GS1 23 0 R /GS2 25 0 R
>> /ProcSet
[ /PDF /Text /ImageC
]
>> /u2pMat
[ 1 0 0 -1 0 810
] /xt1 27 /Rotate 0 /yt1 27 /StructParents 10 /xt2 603 /yb1 18 /CropBox
[ -9 -9 639 819
] /Contents 2 0 R /ArtBox
[ 27 27 603 783
] /MediaBox
[ -9 -9 639 819
] /xb1 18 /yt2 783
>>

I set the trimbox first, then I create the other arrays  from that one.
For the bleedbox, I expand the trimbox by 9 points, for the cropbox and the mediabox, I expand by 36 points.

I don't understand why, but the bleedbox takes on the value intended for the cropbox and mediabox

I use an index for the page because I loop thru all the pages in the pdf one by one, because, sometimes, not all the pages are from a single distilling and the boxes don't match, I must adjust each page individually to standardise the pdf.

I hope I'm explaining my self more clearly.

Thanks

**Comment by gettalong** [comment]
If possible, use the included `hexapdf` command line tool for inspecting PDFs, like with the example command I showed you. Using a text editor will only work in a few cases.

> For the bleedbox, I expand the trimbox by 9 points, for the cropbox and the mediabox, I expand by 36 points.

Are you making sure that you duplicate the array before making both modifications? I.e. `bleed_box = trim_box.dup; crop_box = trim_box.dup`.

**Comment by jcmichaudMarquis** [comment]
I create a new array, then modifying each of the 4 values individually.

    largeurtb = tbf[2].to_f - tbf[0].to_f #values from the original file
    hauteurtb = tbf[3].to_f - tbf[1].to_f #values from the original file
    diffx = (largeurtb - (largeur.to_f * 72)) / 2 #calculate the offset to apply in with to match the job reference, Width
    diffy = (hauteurtb - (hauteur.to_f * 72)) / 2 #calculate the offset to apply in with to match the job reference, Height
    tbc = [0, 0, 0, 0]
    tbc[0] = tbf[0] + diffx
    tbc[1] = tbf[1] + diffy
    tbc[2] = tbf[2] - diffx
    tbc[3] = tbf[3] - diffy
    page2pdf.pages[page2][:TrimBox] = tbc

      page1 = page2pdf.pages[page2]
      abc = [0, 0, 0, 0]
      abc[0] = tbc[0] 
      abc[1] = tbc[1]
      abc[2] = tbc[2]
      abc[3] = tbc[3]
      page2pdf.pages[page2][:ArtBox] = abc
   
    #Bleedbox
    page1 = page2pdf.pages[page2]
    bbc = [0, 0, 0, 0]
    bbc[0] = tbc[0] - 9
    bbc[1] = tbc[1] - 9
    bbc[2] = tbc[2] + 9
    bbc[3] = tbc[3] + 9
    page2pdf.pages[page2][:BleedBox] = bbc

    page1 = page2pdf.pages[page2]
    mbc = [0, 0, 0, 0]
    mbc[0] = tbc[0] - 36
    mbc[1] = tbc[1] - 36
    mbc[2] = tbc[2] + 36
    mbc[3] = tbc[3] + 36
    page2pdf.pages[page2][:MediaBox] = mbc
    page2pdf.pages[page2][:CropBox] = mbc

Tell me why it works for the trimbox, the artbox, the cropbox and the mediabox, but not for the bleedbox?

Thank you

**Comment by gettalong** [comment]
Your code looks fine at first glance, have you tried inspecting the various arrays to see if the values are as expected? I.e. inserting `p tbc` and so on?

Btw. you can make your code more succinct by writing `tbc = [tbf[0] + diffx, tbf[1] + diffy, tbf[2] - diffx, tbf[3] - diffy]` and so on.

**Comment by jcmichaudMarquis** [comment]
I have re-tested it, and the values in the array are still correct. I update the Gem to 0.15.7, still the same result.
I tried not to set the mediabox, the bleedbox took the values of the current mediabox, disregarding my values.

I am running Ruby 2.6.3p62 on a Windows Server 2016 Datacenter version 1607

I think you should try it on your side, maybe you can reproduce the result.

Thank you

**Comment by gettalong** [comment]
Please provide a complete runable sample script that exhibits this behaviour and I will test it.

One thing comes to mind that you might wanna try: Use `HexaPDF::PDFArray.new(bbc)` instead of just `bbc` when assigning the bleed box, and to the same for media and crop box. You may have run into the unlikely case that the source PDF has the same indirect object as value for the bleed, media and crop boxes.

Can you run `hexapdf inspect source.pdf po XXX` on the source PDF and replace `XXX` with the page number where this problem occurs? What is the output of that command?

**Comment by jcmichaudMarquis** [comment]
I will try the complete array creation that you suggest, I will give you feedback later today.

I have seen the same result on all pages of all pdf files since I upgraded from Hexapdf gem from 0.14.2 to 0.15.5

Here the inspect result on the original pdf:
37 0 obj
<<
  /BleedBox [18 18 1204.17114 792 ]
  /Contents 65 0 R
  /Group <<
    /CS /DeviceCMYK
    /S /Transparency
    /Type /Group
  >>
  /MediaBox [0 0 1222.17102 810 ]
  /Parent 36 0 R
  /Resources <<
    /ColorSpace <<
      /CS0 10 0 R
      /CS1 16 0 R
    >>
    /ExtGState <<
      /GS0 68 0 R
      /GS1 69 0 R
      /GS2 70 0 R
      /GS3 71 0 R
      /GS4 72 0 R
      /GS5 73 0 R
      /GS6 74 0 R
      /GS7 75 0 R
      /GS8 76 0 R
    >>
    /Font <<
      /T1_0 22 0 R
      /T1_1 35 0 R
      /T1_2 26 0 R
      /T1_3 30 0 R
    >>
    /ProcSet [/PDF /Text /ImageC /ImageI ]
    /XObject <<
      /Im0 50 0 R
      /Im1 66 0 R
      /Im10 44 0 R
      /Im11 39 0 R
      /Im2 59 0 R
      /Im3 46 0 R
      /Im4 38 0 R
      /Im5 55 0 R
      /Im6 42 0 R
      /Im7 58 0 R
      /Im8 45 0 R
      /Im9 61 0 R
    >>
  >>
  /TrimBox [27 27 1195.17114 783 ]
  /Type /Page
  /u2pMat [1 0 0 -1 0 810 ]
  /xb1 18
  /xb2 1204.17114
  /xt1 27
  /xt2 1195.17114
  /yb1 18
  /yb2 792
  /yt1 27
  /yt2 783
>>
endobj

**Comment by gettalong** [comment]
> I have seen the same result on all pages of all pdf files since I upgraded from Hexapdf gem from 0.14.2 to 0.15.5

So it did work correctly before?

I couldn't reproduce the problem,  so if you could provide a script that exhibits this problem, it would be very helpful.

**Comment by jcmichaudMarquis** [comment]
Well, I'll be damned. The test script I have done produce a good bleedbox, no problem. Sorry to have bothered you, there is something in my code produce the effect, not your software. Here is the code, that works, if you're interested.

require "rubygems"
require "pathname"
require "fileutils"
require "hexapdf"
jobpdfc2 = "C:/Users/switch_services/Documents/C1C4 4C_ok.pdf"
pathpdf = "C:/Users/switch_services/Documents/C1C4 4C.pdf"
page2pdf = HexaPDF::Document.open(pathpdf)
tbc = page2pdf.pages[0][:TrimBox]
abc = [0, 0, 0, 0]
abc[0] = tbc[0]
abc[1] = tbc[1]
abc[2] = tbc[2]
abc[3] = tbc[3]
page2pdf.pages[0][:ArtBox] = HexaPDF::PDFArray.new(abc)
#Bleedbox
page1 = page2pdf.pages[0]
bbc = [0, 0, 0, 0]
bbc[0] = tbc[0] - 9
bbc[1] = tbc[1] - 9
bbc[2] = tbc[2] + 9
bbc[3] = tbc[3] + 9
page2pdf.pages[0][:BleedBox] = HexaPDF::PDFArray.new(bbc)
#Mediabox
page1 = page2pdf.pages[0]
mbc = [0, 0, 0, 0]
mbc[0] = tbc[0] - 36
mbc[1] = tbc[1] - 36
mbc[2] = tbc[2] + 36
mbc[3] = tbc[3] + 36
page2pdf.pages[0][:MediaBox] = HexaPDF::PDFArray.new(mbc)
page2pdf.pages[0][:CropBox] = HexaPDF::PDFArray.new(mbc)
page2pdf.write(jobpdfc2.to_s, validate: false)

Thank you for your patience.

**Comment by gettalong** [comment]
No problem!
