### ISSUE TITLE
Could not reconstruct malformed PDF because trailer was not found?

### ISSUE THREAD

**Issue by thanhtoan1196** [gettalong/hexapdf#146]
I got this error, how to fix?

```
HexaPDF::MalformedPDFError: PDF malformed around position 0: Could not reconstruct malformed PDF because trailer was not found
```

**Comment by gettalong** [comment]
Can the PDF be processed by any other application? I.e. can you, for example, view it in a PDF viewer? Have you tried running `hexapdf info --check my-file.pdf`?

Please provide the PDF in question so that I can inspect it and find out why it fails.

**Comment by gettalong** [comment]
@thanhtoan1196 I will close the issue since I can't do anything without the requested information.

Once you provide the information I will happily re-open the issue.

**Comment by vladislav-zubov** [comment]
I have the same error and I ran `hexapdf info --check my-file.pdf` and got this:
```
WARNING: Parse error at position 0: PDF file trailer with end-of-file marker not found - trying cross-reference table reconstruction
WARNING: Parse error at position 275417: Invalid stream length, keyword endstream not found
Error: PDF file my-file.pdf is damaged and cannot be recovered
       Could not reconstruct malformed PDF because trailer was not found
```

This file is open correctly with browsers and other pdf readers

**Comment by vladislav-zubov** [comment]
@gettalong unfortunately, I can't provide you an pdf file because it is our clients one. 

I debugged and found an issue [here](https://github.com/gettalong/hexapdf/blob/REL_0_46_0/lib/hexapdf/parser.rb#L371) and my pdf file is parsed like:
```
[
...,
"%%EOF\xDA\x9D\x83\x1A\fJ\x83\x8C\xD1#\xA2\f]\x1F\x84+\x13c\x8C\xC0$a\xDEH\xD2\x13F\xE7\x06\xE5\xBCf\xB4\x9CW\x86\xD8u"
]
``` 


Do you have any ideas how to fix that?

**Comment by gettalong** [comment]
@vladislav-zubov The part you are showing might indicate an invalid EOF marker line due to some additional garbage bytes at the end of the file. Whether this is recoverable by itself I cannot say without more information.

The reconstruction algorithm then tries to find all the PDF objects in the file which doesn't succeed in your case. Maybe I could deduce it if you provide enough bytes around the mentioned offset 275417.

**Comment by vladislav-zubov** [comment]
> The reconstruction algorithm then tries to find all the PDF objects in the file which doesn't succeed in your case. Maybe I could deduce it if you provide enough bytes around the mentioned offset 275417.

My pdf file does not have `275417 ` offset. If[ I seek to](https://github.com/gettalong/hexapdf/blob/REL_0_46_0/lib/hexapdf/parser.rb#L357) the end of file I have a pos like `274432`

**Comment by gettalong** [comment]
@vladislav-zubov Hmm .. that's strange since I took the number from your initial comment.

If you can't provide the PDF, I'm afraid you need to debug this yourself.
