### ISSUE TITLE
Does -v option prevent writing output in some cases?

### ISSUE THREAD

**Issue by oddhack** [gettalong/hexapdf#147]
I have a document where 'hexapdf --force optimize in.pdf out.pdf' produces the desired output, while 'hexapdf -v --force optimize in.pdf out.pdf' raises warnings:

> Problem encountered: undefined method `oid' for "Object must be an indirect object":String  
> Did you mean?  ord

and no file is written. Is the intent of the '-v' option that it is not just verbose, but also changes processing behavior like this?

I can provide a sample PDF with the specific problem if desired, but that's tangential to the question.

**Comment by gettalong** [comment]
Thanks for the bug report!

Indeed, the `-v` option should not change any processing behaviour. I have found the problem and will push a new release.

**Comment by gettalong** [comment]
@oddhack I just released a bug fix version.

**Comment by oddhack** [comment]
Thanks very much! Verified this fixes the issue for me.
