### ISSUE TITLE
Adding font using FileFontLoader issue

### ISSUE THREAD

**Issue by jpgeek** [gettalong/hexapdf#149]
It looks like FileFontLoader is broken (or I am misunderstanding its usage).

 lib/hexapdf/document/fonts.rb:86 in configured_fonts():
`          # lib/hexapdf/document/fonts.rb:86:`
`          next unless loader.respond_to?(:available_fonts)`

However, HexaPDF::FontLoader::FromFile does not respond to :avalable_fonts and is thus never returned by configured_fonts.

I can't find any examples on how to load a font so I am guessing that loading one from a file is supposed to be done via the FileFontLoader, but this makes it look impossible.  The other two loaders (FromConfiguration and Standard14) do respond to :available_fonts.

**Comment by gettalong** [comment]
The `#available_fonts` method provides information from the font loader to the font system which fonts are *always* available. Since HexaPDF itself doesn't know which files are available on any system, there are no defaults here (in contrast to Standard14 which provides the 14 standard PDF fonts and FromConfiguration which uses a configuration value for providing the defaults).

So the file font loader is not broken. Just supply a valid TTF filename and it will be used.

**Comment by jpgeek** [comment]
Thank you soooo much for the super fast reply - thanks for that.  So it looks like I was misunderstanding the intent of the method.

Trying to add a font using:
`      doc = HexaPDF::Document.new
      ttf_file = '/absolute/path/to/arial/black/tty'
      doc.config['font.map'] = {:Arial => {black: ttf_file}}
      doc.fonts.add(:'Arial', variant: :black)
      canvas = doc.pages.add.canvas
      canvas.font('Arial', variant: :black, size: 100)`

Throws a (comparison of Array with Array failed) at 
/lib/hexapdf/document/fonts.rb:73

`=> 73:           font_list = configured_fonts.sort.map do |font_name, variants|
   74:             "#{font_name} (#{variants.join(', ')})"
   75:           end.join(', ')`

in this context, configured_fonts is returning:
`{"Times"=>[:none, :bold, :italic, :bold_italic], "Helvetica"=>[:none, :bold, :italic, :bold_italic], "Courier"=>[:none, :bold, :italic, :bold_italic], "Symbol"=>[:none], "ZapfDingbats"=>[:none], :Arial=>[:black]}`

So it looks like line 73 is not compatible with the output of configured_fonts (unless I have somehow screwed up the context).  What is the intent here?

**Comment by gettalong** [comment]
The font name needs to be a string, as can be seen by the output of `#configured_fonts`. So use `"Arial"` instead of `:Arial`.

**Comment by jpgeek** [comment]
Thank you!   
I have tried both ways and get the same error.  

As an aside, from the docs at lib/hexapdf/configuration.rb:244 but wasn't totally sure which it was signifying, since "Arial": returns a symbol.  It might be best to change it to use rocket style hash?

```
  # font.map::
  #    Defines a mapping from font names and variants to font files.
  #
  #    The value needs to be a hash of the form:
  #      {"font_name": {variant: file_name, variant2: file_name2, ...}, ...}
```

to
`  #      {"font_name" => {:variant => file_name, :variant2 => file_name2, ...}, ...}`

**Comment by gettalong** [comment]
Thank you, you are completely right, that should be a hash-rocket - fixed for the next release!
