### ISSUE TITLE
Manipulate an encrypted pdf given pw

### ISSUE THREAD

**Issue by Plummat** [gettalong/hexapdf#15]
Given an encrypted pdf and password, is it possible to decrypt and and make a copy given this library?

Apologies if this has been answered; I just didn't see it if so!

**Comment by gettalong** [comment]
Yes, this is possible. You need to pass the correct `decryption_opts` argument when creating a `HexaPDF::Document` and then remove the encryption with a call to `#encrypt`, see https://hexapdf.gettalong.org/api/HexaPDF/Document/index.html#method-c-new, https://hexapdf.gettalong.org/api/HexaPDF/Encryption/StandardSecurityHandler/index.html, https://hexapdf.gettalong.org/api/HexaPDF/Encryption/StandardSecurityHandler/EncryptionOptions.html
and https://hexapdf.gettalong.org/api/HexaPDF/Document/index.html#method-i-encrypt.

**Comment by gettalong** [comment]
Or you can just use the provided `hexapdf` binary to do this, using the `modify` command, see  https://hexapdf.gettalong.org/documentation/hexapdf.1.html

**Comment by Plummat** [comment]
Appreciate the direction Thomas

**Comment by Plummat** [comment]
Getting back to this and actually, I got lost there - I sent through the
decrypt opts, but I am not sure what to do with the encrypt call to remove
 it.

**Comment by Plummat** [comment]
However, seems to work as expected if I call open on the pdf, as opposed to
new

**Comment by gettalong** [comment]
If it works with `#open` but not with `#new`, this could be a bug. Would you mind sharing the code that leads to the error?
