### ISSUE TITLE
Fill PDF AcroForm text field with boldface text: Font not accepted?

### ISSUE THREAD

**Issue by JRSeabird** [gettalong/hexapdf#150]
I have a pre-existing pdf form. Filling in the form manually, one of its text fields shows its value in boldface type. When using HexaPdf to fill this field, the text should also appear in boldface, but it appears in regular type.

I fill the field with

~~~ ruby
doc.acro_form.field_by_name('text1').field_value = @record.value
~~~

To get this to be shown in boldface, I have tried the following:

~~~ ruby
doc.acro_form.field_by_name('text1').set_default_appearance_string(font: 'Helvetica-Bold', font_size: 0)
~~~

This gets the error message "The requested font 'Helvetica-Bold' in variant 'none' couldn't be found".

Then I tried:

~~~ ruby
doc.acro_form.field_by_name('text1').set_default_appearance_string(font: 'Helvetica', variant: :bold, font_size: 0)
~~~

This gets: "unknown keyword: variant".

The configured fonts for the document are:

~~~ ruby
{"Times"=>[:none, :bold, :italic, :bold_italic], "Helvetica"=>[:none, :bold, :italic, :bold_italic], "Courier"=>[:none, :bold, :italic, :bold_italic], "Symbol"=>[:none], "ZapfDingbats"=>[:none]}
~~~

So Helvetica with variant :bold should be available.

I'm not sure if this is an issue or if I may be missing the correct syntax. In the latter case, please excuse!

**Comment by gettalong** [comment]
Thanks for reporting this!

It is indeed an issue as there is no way to do this currently with that method - I will fix it for the next release.

You can use the following work-around until then:

~~~ ruby
name = doc.acro_form.default_resources.add_font(document.fonts.add('Helvetica', variant: :bold).pdf_object)
doc.acro_form.field_by_name('text1')[:DA] = "0 g /#{name} 0 Tf"
~~~

**Comment by gettalong** [comment]
@JRSeabird Hmm... auto-sizing should still work. Would it be possible that you share the PDF where it doesn't work?

**Comment by JRSeabird** [comment]
Yes, you can find it on [this page](https://www.zh.ch/de/bildung/informationen-fuer-schulen/informationen-volksschule/volksschule-fuehrung/volksschule-personal-fuehren/volksschule-personal-beurteilen.html#830862349) -> go to "Für Lehrpersonen" -> it's the file "Beurteilungsdokument Lehrperson". 
: 

I'm also having trouble using the checkboxes in this form, always getting the message that they don't have check_box_on_name set. I'm working around this by deleting the checkboxes and creating new ones at the same location, but maybe you have a better suggestion.

**Comment by gettalong** [comment]
@JRSeabird Thanks for providing the PDF!

I will see about the problem with the auto-sizing later.

As for the check boxes: This is the same issue as in https://github.com/gettalong/hexapdf/issues/148 where two check boxes are used to act like a radio button group. So this will work soon.
