### ISSUE TITLE
Adding fonts, closing file handles for fonts clarification

### ISSUE THREAD

**Issue by jpgeek** [gettalong/hexapdf#151]
I have been able to add a font using this:

```
      ttf_file = (Rails.root + 'app/resources/fonts/TakaoGothic.ttf')
      doc.config['font.map'] = {'TakaoGothic' => {:none => ttf_file}}
      doc.fonts.add('TakaoGothic', {variant: :none})
```

Apparently by using the font.map I don't have to instantiate and configure a 
`HexaPDF::FontLoader::FromFile`

However, tracing the code it looks like it is used underneath to open the font file, and the documentation for it says:
```
      # If a file name is given, the file object representing the font file is *not* closed and if
      # needed must be closed by the caller once the font is not needed anymore.
```

Sure enough, when I inspected:
`ObjectSpace.each_object(File).to_a`
it shows that the handle is still open.

What is the preferred way to handle this?  The only way I can see to manually close this is to go through ObjectSpace.each_object(File) which seems wrong.  I also think the documents said (and I have confirmed) that a font file would not be re-opened if the same path was entered twice - is it the intention to leave these open until the program exits?
 
Thanks!

**Comment by gettalong** [comment]
To close the underlying file object, store the font object returned by `doc.fonts.add` and then close the IO object via `font.wrapped_font.io.close`.

As for loading a TTF file: You can also just provide the file name directly to `doc.fonts.add` and it will work.

N.B. the situation is similar with images. However, there is already a configuration option "image_loader.pdf.use_stringio" to make HexaPDF use a `StringIO` when loading PDF images.

Generally, file objects and when to close them wrt HexaPDF is something that needs to be addressed in the future to make it consistent.
