### ISSUE TITLE
No Gemfile and rake dev:setup is broken

### ISSUE THREAD

**Issue by eregon** [gettalong/hexapdf#156]
```
$ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
$ rake dev:setup
Installing required runtime and development gems:
rake aborted!
NameError: undefined local variable or method `spec' for main:Object
Did you mean?  inspect
/home/eregon/code/hexapdf/Rakefile:54:in `block (2 levels) in <top (required)>'
Tasks: TOP => dev:setup
(See full trace by running task with --trace)
```

This makes it hard to run the tests.

**Comment by gettalong** [comment]
I don't have a need for the Gemfile, therefore there is none in the repo.

Thanks for the report about `rake dev:setup` - I have fixed it and pushed the changes to the repo.

**Comment by eregon** [comment]
Actually the fact it's in repo is useful for contributors IMHO, it's easy to see what's run in CI and what's needed to get started.
I typically look there rather than searching in the README or so.
A CI is also nice for feedback when making a PR (e.g., system packages might not be installers on the dev machine and so some tests are skipped).

Somewhat related, when TruffleRuby fixes the last issue and passes the entire test suite I think it would be great to add it in CI, but of course it is up to you.
