### ISSUE TITLE
Setting nil as field value of a single line text field value crashes

### ISSUE THREAD

**Issue by sled** [gettalong/hexapdf#157]
I just noticed, that if I set `nil` as `field_value` to a "Single Line Text Field" HexaPDF crashes because, `.gsub` is not defined on `nil`, this happens here: https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/type/acro_form/text_field.rb#L168 where it apparently replaces tabs, newlines etc. with a regular space character.

It's a bit unexpected, as `nil` works perfectly fine for other concrete text field types like a multi line textfield for example.

If the safe navigation operator is an option, this could be written as:

```
str = str&.gsub(/[[:space:]]/, ' ') if concrete_field_type == :single_line_text_field
```

or alternatively, converting it to a string:

```
str = str.to_s.gsub(/[[:space:]]/, ' ') if concrete_field_type == :single_line_text_field
```

I tested with HexaPDF v0.16.0 and Ruby 2.7.4

**Comment by gettalong** [comment]
Thanks for the bug report - just in time for the upcoming release this evening :wink:
