### ISSUE TITLE
How to change the color of the fonts text_fields / acro_form ? 

### ISSUE THREAD

**Issue by btazi** [gettalong/hexapdf#159]
So I managed to change the font of my text_fields using `document.config['acro_form.fallback_font']` .
Now I just need to change the color of the text fields but I couldn't find anything in the documentation.

**Comment by gettalong** [comment]
@btazi This will be implemented for the next release.

**Comment by gettalong** [comment]
@btazi I have implemented this. Now you can specify the font color and it will be used by the appearance generator.
