### ISSUE TITLE
Help adding links to named destinations

### ISSUE THREAD

**Issue by robjperez** [gettalong/hexapdf#166]
Hi, :wave: . First of all, thanks for this amazing library :)

Now, to the question:

Reading the documentation I see
```
new(dest: nil, uri: nil, file: nil, border: false, border_color: nil)
Creates a new LinkLayer object.

dest
The destination array or a name of a named destination for in-document links.
```
I wonder how I can create the named destination on the target page.
Let's say I write
```
link = HexaPDF::Layout::Style::LinkLayer.new(dest: "chapter3")
link.call(...)
```
How can I add the `chapter3` reference in the chapter3 page?

Thanks!

**Comment by gettalong** [comment]
There are currently no helper methods for easily generating destination arrays. Such an array looks like `[doc.pages[0], :XYZ, 50, 100, 0]` - this will specify a destination on the first page at the location (50, 100) - see section 12.3.2 in the PDF specification for details.

A named destination is just such a destination array registered under `doc.catalog[:Names][:Dest]`.

So what you might wanna do is generating named destination during the generation of the file and later referring to them.

**Comment by robjperez** [comment]
Thanks for the quick reply!

Can you post an example on how can I register an array under `doc.catalog[:Names][:Dest]`. I'm trying different approaches but none of them seems to work.

Thanks in advance!

**Comment by gettalong** [comment]
I just saw that I wrote `Dest` instead of `Dests`, updated my comment.

This should do the trick:

~~~ ruby
doc.catalog[:Names] = {}
doc.catalog[:Names][:Dests] = {}
dests = doc.catalog[:Names][:Dests] # to get the correct class
dests.add_entry("chapter3", [doc.pages[0], :XYZ, 50, 100, 0])
~~~

I should probably add the necessary convenience methods for the named destinations - added to my TODO list.

**Comment by robjperez** [comment]
Thanks again,
Just wrote this sample code

```
require 'hexapdf'

doc = HexaPDF::Document.new

doc.pages.add([0, 0, 300, 300])
doc.pages.add([0, 0, 300, 300])
doc.pages.add([0, 0, 300, 300])

doc.catalog[:Names] = {}
doc.catalog[:Names][:Dests] = {}
dests = doc.catalog[:Names][:Dests] # to get the correct class
dests.add_entry("chapter3", [doc.pages[2], :XYZ, 50, 100, 0])

canvas = doc.pages[0].canvas
link = HexaPDF::Layout::Style::LinkLayer.new(dest: "chapter3", border: true)
canvas.translate(50, 50) do
    link.call(canvas, HexaPDF::Layout::Box.new(width: 50, height: 50))
end

doc.write("test.pdf", optimize: true)
```

It worked as expected, when clicking on the square in page 1, it went to page 3.
Also, if you open `test.pdf` with another editor, add 2 pages in between 1 and 3, link still goes to what it was page 3, even though it is page 5 now. :tada:

**Comment by gettalong** [comment]
Great! :smile: The link still work because the reference is to a page object and not to a page number.
