### ISSUE TITLE
Export a page as PNG?

### ISSUE THREAD

**Issue by unikitty37** [gettalong/hexapdf#17]
I've spent some time looking through the documentation and haven't been able to find this out:

Is it possible to use Hexapdf export a page of a PDF as a PNG (eg for generating a thumbnail) or do I have to use ImageMagick to do this?

**Comment by gettalong** [comment]
HexaPDF doesn't include a PDF rendering engine. You need to use other applications for this, like the mentioned ImageMagick or, better, a tool designed for PDF rendering like the `pdfcairo` executable from the poppler library.
