### ISSUE TITLE
Extract text

### ISSUE THREAD

**Issue by masylum** [gettalong/hexapdf#18]
Hello,

First of all, congratulations for the gem. It's impressive the amount of work that you've put in this project!

More than an issue, it's a question. We are trying to replace `pdf-reader` with `hexapdf` at factorialhr.com. We have a functionality that reads payslips and extracts information from it. `pdf-reader` sometimes does not return us the data correctly, information is missing.

I've tried to replace it like this:

```rb
    # Original code
    reader = PDF::Reader.new(StringIO.open(document.file.read))
    @text = reader.pages.join.split("\n")

    # HexaPDF code
    class SampleProcessor < HexaPDF::Content::Processor
      attr_reader :text

      def initialize()
        super()
        @text = ['']
      end

      def show_text(str)
        @text << decode_text(str)
      end
      alias :show_text_with_positioning :show_text
    end

    reader = HexaPDF::Document.new(io: StringIO.open(document.file.read))
    processor = SampleProcessor.new
    reader.pages.each do |page|
      page.process_contents(processor)
    end

    @text = processor.text
```

Does not seem to be right, but I'm not sure I understand how else to do it. Also, If I comment out the `alias :show_text_with_positioning :show_text` it misses plenty of text (the one that is positioned) but if I have it appears in a different ordering.

Am I missing something big?

**Comment by gettalong** [comment]
Content processing with HexaPDF does *only* the following:

* Tokenize the page stream into PDF tokens
* Call appropriate methods on the processor

What this means is that you get the decoded text with positional information **in the order it appears in the page stream**. This information alone is useful for some applications (e.g. for highlighting certain words in a PDF).

However, what you what is **text in the correct reading order**. Whether the appearance order and reading order is the same depends on the application that generated the PDF. So you can't really depend on it.

The solution? You need to use the positional information returned by HexaPDF to figure out whether a piece of text belongs to some other pieces of text on the same line, whether there is a space between pieces of text (some PDF generators don't encode this information), and so on.

I have an item on my TODO list that says: "Smart text extraction with positioning, i.e. for representing the text of a PDF page in a terminal" which is what you would need in this case for further processing. This functionality would replicate what other PDF-to-text programs are doing.

You may wanna try `pdftotext` from the Poppler library for the moment which already has such functionality if `pdf-reader` is doing something strange.

Also, some PDFs don't have correctly encoded text at all. If this is the case, your only chance would probably be generate an image of the pages and use OCR software to recover the Unicode characters.

Does this answer your question?

**Comment by masylum** [comment]
That is an amazing answer actually! Will try `pdftotext` on the meantime.

Thanks a lot.

**Comment by nevostruev** [comment]
I've created processor which sorts extracted text into lines. This can be useful if you don't want to include extra library dependency just for simple text extraction.

```ruby
  class GetTextProcessor < HexaPDF::Content::Processor
    def initialize
      super
      @text_blocks = []
    end

    def show_text_with_positioning(str)
      text_pos = decode_text_with_positioning(str)

      @text_blocks << {
          x: text_pos.upper_left[0],
          y: text_pos.upper_left[1],
          height: (text_pos.upper_left[1] - text_pos.lower_left[1]).abs,
          index: @text_blocks.length,
          text: text_pos.string,
      }
    end

    def string
      prev_block = nil
      text = []

      def on_same_line?(block1, block2)
        ## consider blocks on same line when vertical distance is less than 0.2 of block height
        (block1[:y] - block2[:y]).abs < [block1[:height], block2[:height]].max * 0.2
      end

      # sort fragments by coordinates:
      #   - sort by line first - allow slight variation in y coordinate
      #   - then by x
      #   - then by index - so output doesn't depend on text
      @text_blocks.sort do |left, right|
        if on_same_line?(left, right)
          [left[:x], left[:index]] <=> [right[:x], right[:index]]
        else
          right[:y] - left[:y] # reverse order
        end
      end.each do |block|
        unless prev_block.nil?
          text << (on_same_line?(prev_block, block) ? ' ' : "\n")
        end

        text << block[:text]
        prev_block = block
      end

      text.join + "\n"
    end
  end
```

**Comment by briantavour** [comment]
@nevostruev 

Thanks for sharing. While I didn't use your code exactly, I did find myself needing to add

```
  alias :show_text :show_text_with_positioning
```

Or else it would miss some text.
