### ISSUE TITLE
[Documentation] prawn-to-hexapdf guide

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/hexapdf#182]
Yo,

You currently mention this:

"Such functionality will be incorporated into HexaPDF in the near future"

So perhaps hexapdf may one day replace prawn. What I was thinking
here was ... some prawn users could probably already migrate to
hexapdf. But there is always a cost of learning a new toolset, and
many users are lazy (well I am, but I know there are many other
lazy folks out there too).

The idea here would be to kind of show a "corresponding feature"
list or table or a guide. Actually in the simplest form this could be
a simple markdown table, that showcases and compares 
SIMPLE examples. Nothing too long really, I think at max 
2 DIN A4 pages should suffice, all starting with the simplest
parts, and if time permits add a very few complex examples
to show how things are done via hexapdf.

Note that I focus here mostly on EXISTING functionality - I understand
that hexapdf isn't on 1:1 parity yet, but this isn't that important. The
main idea here is to allow people to more easily transition into
hexapdf, as an additional alternative to prawn (and perhaps some
will decide to stay with hexapdf).

**Comment by gettalong** [comment]
Thanks for the idea!

At one time I thought to make a Prawn-compatibility layer for HexaPDF but gave up since there are many small differences in behaviour that would need to be addressed. So having such a corresponding feature table would certainly be useful.

**Comment by gettalong** [comment]
@rubyFeedback I have taken your idea and put up an initial document  at https://hexapdf.gettalong.org/documentation/howtos/migrating-from-prawn.html - would love to get your feedback on it!

It currently provides a simple-ish example and then a mapping from Prawn to HexaPDF for the various operations there are, with additional info on what's only available in Prawn or in HexaPDF.

You wrote about *simple* examples; what exactly where you thinking about here? I know the Prawn codebase but haven't used it in any production code for quite a while.

**Comment by gettalong** [comment]
Will close this since now there is the migration guide.
