### ISSUE TITLE
Digital signature operation from external Library 

### ISSUE THREAD

**Issue by cristianpaul0** [gettalong/hexapdf#187]
Hey guys, 

I'm trying to integrate this Google's SDK Ruby snippet in to the how-to singing PDF example [2] I've noticed it already uses OpenSSL [3] but since this is Google KMS (HSM) backed I need to pass then the digest/message (from the PDF's content part/bits to be signed) to then (very straightforward if you look at the snippet) and store the signature response back to the file..

What's the best way to implement this? I was initially looking for a generic pkcs11 interface support, but I couldn't even find a recent ruby gem for this then tried the self-signed PDF sign example, but I'm still reading API docs trying to understand what's the best way or the right method that could be monkey patched to fit my use case.

[1] https://cloud.google.com/kms/docs/create-validate-signatures#create_signature
[2] https://hexapdf.gettalong.org/documentation/howtos/signing-pdfs.html
[3] https://github.com/gettalong/hexapdf/blob/master/data/hexapdf/cert/demo_cert.rb

**Comment by gettalong** [comment]
Adding support PKCS11 is on my TODO list but nothing done yet.

Have a look at https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/document/signatures.rb#L46-L162. This is the default handler class that uses OpenSSL to actually sign the content (see the #sign method there). You would need to write a custom handler (probably based on the default one) for signing with Google KMS.

Calculating the to-be-signed content and putting the signed CMS data structure back into the PDF is done by HexaPDF, so no need for you to do that.

**Comment by cristianpaul0** [comment]
Does the `sign` method (https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/document/signatures.rb#L157) expects the DER in a single string?  I'm trying to use openssl cms cli (couldn't find openssl cms support in ruby) to hack this for now, just trying to understand what should I return here exactly

**Comment by gettalong** [comment]
Yes, a single string that will be the value of the /Contents key in the signature object.

**Comment by cristianpaul0** [comment]
@gettalong  out of curiosity and since I'm trying to form the pkcs7 object myself, I'm struggling with the `https://www.rubydoc.info/gems/rubysl-openssl/1.0.2/OpenSSL/PKCS7#add_certificate-instance_method` `add_certificate` do you recall may be using it in the past? I pass to it a x509 certificate but wasn't happy with it…

**Comment by gettalong** [comment]
@cristianpaul0 I'm sorry, no. From what I can see passing a https://www.rubydoc.info/gems/rubysl-openssl/1.0.2/OpenSSL/X509/Certificate should do the trick. 

Have you tried turning on debuging `OpenSSL.debug = true` and viewing the errors in `OpenSSL.errors`. What did the error say?

**Comment by kristianpaul** [comment]
> @cristianpaul0 I'm sorry, no. From what I can see passing a https://www.rubydoc.info/gems/rubysl-openssl/1.0.2/OpenSSL/X509/Certificate should do the trick.
> 
> Have you tried turning on debuging `OpenSSL.debug = true` and viewing the errors in `OpenSSL.errors`. What did the error say?

Debug helped!, looks like I have to pass the type (signed) when creating the PKCS7 object like this:

`openssl::PKCS7::PKCS7.new(signed)`

**Comment by cristianpaul0** [comment]
Ideally, would be nice to interface this signing via pkcs11 

> Adding support PKCS11 is on my TODO list but nothing done yet.
> 
> Have a look at https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/document/signatures.rb#L46-L162. This is the default handler class that uses OpenSSL to actually sign the content (see the #sign method there). You would need to write a custom handler (probably based on the default one) for signing with Google KMS.
> 
> Calculating the to-be-signed content and putting the signed CMS data structure back into the PDF is done by HexaPDF, so no need for you to do that.



> Adding support PKCS11 is on my TODO list but nothing done yet.
> 
> Have a look at https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/document/signatures.rb#L46-L162. This is the default handler class that uses OpenSSL to actually sign the content (see the #sign method there). You would need to write a custom handler (probably based on the default one) for signing with Google KMS.
> 
> Calculating the to-be-signed content and putting the signed CMS data structure back into the PDF is done by HexaPDF, so no need for you to do that.

How big this support of PKCS11 would be? Starting that openssl's gem is not really well documented… Do you have another crypto library for ruby in mind?

**Comment by gettalong** [comment]
There is https://github.com/larskanis/pkcs11 but I haven't looked at it in detail. That one doesn't rely on OpenSSL but directly interacts with a native PKCS11 library.

**Comment by cristianpaul0** [comment]
@gettalong I've noticed that `data` length is zero  first time `sign` method is called, but even still the openssl sign is called, is this intentional? What should i return from a custom implementation of `sign` when `data` length is zero?

**Comment by gettalong** [comment]
@cristianpaul0 This is due to [this method](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/document/signatures.rb#L132-L134) where the size of the signature blob is determined. This is just a *very* simple implementation of getting the signature size, so you might need to adjust that.

The `#sign` method should always return a proper signature object, regardless of the data. If having an empty string as input is a problem, then you should write a custom `#signature_size` method.

**Comment by gettalong** [comment]
@cristianpaul0  So I just wanted to mention that the next version due in a few days will have support for external signing via a special signing handler. This should make it a bit easier to interface with an external signing service like Google KMS.

**Comment by gettalong** [comment]
@cristianpaul0 The mechanism for external signing is now incorporated in the default signing handler:

~~~
signing_proc = lambda do |io, byte_range|
  io.pos = byte_range[0]
  data = io.read(byte_range[1])
  io.pos = byte_range[2]
  data << io.read(byte_range[3])
  signing_service.pkcs7_sign(data)
end
document.sign("output.pdf", signature_size: 10_000, external_signing: signing_proc)
~~~

Regarding PKCS#11 support: On my TODO list but will probably not be implemented in the near future.

Regarding building a PKCS#7 object yourself: Did it work? I recently had to dig into the PKCS#7 structure and OpenSSL and I don't think that the PKCS#7 class of OpenSSL is intended to be manually built. What you probably can do is build the PKCS#7 structure from the ground up using its base ASN.1 description. This is something I will investigate further for LTV support.

Regarding another crypto library: I know of https://github.com/RubyCrypto/rbnacl/ but this library only ships basic encryption algorithms, so PKCS#7 support there.

I will close the issue. Let me know if this is not resolved for you.

**Comment by cristianpaul0** [comment]
> PKCS#7

havent tried it

**Comment by gettalong** [comment]
@jotolo You are correct that PKCS#1 signatures are deprecated. However, you should be able to create a PAdES/CMS signature using one of the rsa-sign-pkcs1-{2048,3072,4096}-{sha256,sha512} RSA signing keys . The resulting signature can be embedded in the CMS signed data structure. Just make sure that the digest method you use with HexaPDF and the key are the same.

In the example in https://github.com/gettalong/hexapdf/issues/187#issuecomment-1401013535 you would change the line `external_signing: proc {|alg, hash| key.sign_raw(alg, hash)},` so that `key.sign_raw(alg, hash)` refers to the Google KMS invocation for signing.

Note that HexaPDF currently only supports RSA without PSS for signing, so you would need to have one of the rsa-sign-pkcs1-* keys (although I don't know the difference between the pkcs1 and raw version of those keys...).

**Comment by jotolo** [comment]
Hi @gettalong . Thanks for your quick reply and explanation. I managed to get it working by signing with Google KMS as you described.

For future references in case someone else read this issue:
You could use `rsa-sign-pkcs1-2048-sha256` as the algorithm for the private key you upload to Google KMS (or any other without PSS, depending on your key). Then you just need to sign as proposed in the documentation and mentioned by @gettalong here: https://github.com/gettalong/hexapdf/issues/187#issuecomment-1611789263

```ruby
version_key_name = 'version_key_name' # Get the key version name from Google KMS

signing_mechanism = lambda do |digest_method, data|     
     digest = { digest_method.to_sym => data } # data is already digested so, no need to do it again
     
     kms = Google::Cloud::Kms.key_management_service
     sign_response = kms.asymmetric_sign(name: key_version_name, digest: digest)
     sign_response.signature
end
```

@gettalong It could be an idea to include something like this example in the documentation. I guess more people will use HSMs to integrate them with HexaPDF. Please, let me know if I can help somehow, I will be glad.

Again, thanks for the big help 🚀 Really appreciated! 🤝

**Comment by gettalong** [comment]
@jotolo Thanks for confirming that this works! :smile: I will add some documentation to https://hexapdf.gettalong.org/documentation/digital-signatures/signing-pdfs-howto.html

**Comment by jotolo** [comment]
@gettalong Thank you for the explanation provided and the work you have done with HexaPDF. 🤝
