### ISSUE TITLE
Digitally signed pdf, issue with signature when reloading / persisting to StringIO

### ISSUE THREAD

**Issue by biril** [gettalong/hexapdf#189]
Hello and thank you for the very useful lib.

I have a piece of functionality around digitally signing a PDF, serializing/desirializing it and persisting it.

I've already read through the useful information in https://github.com/gettalong/hexapdf/issues/56. Here's the use case that's giving me trouble:

```ruby
# Works. I can open the PDF in Acrobat and see reasonable information pertaining to the digital signature.
string_io = StringIO.new(''.b)
doc.sign(string_io, certificate: ..., key: ..., certificate_chain: ...)
File.open('/some/path/doc.pdf', 'wb') { |f| f.puts(string_io.read) } # perhaps requires string_io.seek(0) beforehand, can't quite recall, not significant

# Does not work. PDF document renders as expected but Acrobat says 
# "There are errors in the formatting or information contained in this signature
#  (support information: SigDict /Contents illegal data)"
string_io = StringIO.new(''.b)
doc.sign(string_io, certificate: ..., key: ..., certificate_chain: ...)
other_doc = HexaPDF::Document.new(io: string_io) # Same thoughts around seek(0), not significant
other_doc.write('/some/path/doc.pdf')
```

Perhaps the issue I'm facing is not relevant to the use of io but rather some nuances around reloading a signed PDF (`HexaPDF::Document.new(io: string_io)`)? Could you shed some light?

**Comment by gettalong** [comment]
This is to be expected because when you open and write the document, the on-disk representation will be changed, invalidating the signature hash. So this would also happen, if you load a signed PDF from a file.

What you need to do is use incremental writing in such a case: `other.write('output.pdf', incremental: true)`.

**Comment by biril** [comment]
Thank you @gettalong. That's very helpful.
