### ISSUE TITLE
TextLayouter

### ISSUE THREAD

**Issue by Dazzed** [gettalong/hexapdf#19]
Hi 
I am trying to render text in multiple lines, but am getting an error about missing TextLayouter class.

[UPDATE]: I figured its using the textbox class. Can you please update your examples as they are still referring to TextLayouter

**Comment by gettalong** [comment]
Nope, the examples are correct :wink: - they reflect the latest changes in the code where TextBox was renamed to TextLayouter since a real TextBox, based on a general Box class, will be coming shortly.

The code for these changes will shortly be pushed to Github.
