### ISSUE TITLE
Error "Invalid index into object stream given" when adding a file to a PDF 

### ISSUE THREAD

**Issue by noniq** [gettalong/hexapdf#193]
When I add a file to an existing PDF and then call `#write` the following error occurs:

```
Traceback (most recent call last):
	18: from bug.rb:11:in `<main>'
	17: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/document.rb:674:in `write'
	16: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/writer.rb:55:in `write'
	15: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/writer.rb:83:in `write'
	14: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/revisions.rb:282:in `each'
	13: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/revisions.rb:282:in `each'
	12: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/writer.rb:84:in `block in write'
	11: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/writer.rb:146:in `write_revision'
	10: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/writer.rb:199:in `xref_and_object_streams'
	 9: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/revision.rb:218:in `each'
	 8: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/utils/object_hash.rb:120:in `each'
	 7: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/utils/object_hash.rb:120:in `each'
	 6: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/utils/object_hash.rb:120:in `block in each'
	 5: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/revision.rb:220:in `block in each'
	 4: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/revision.rb:270:in `load_object'
	 3: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/revisions.rb:71:in `block in from_io'
	 2: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/parser.rb:92:in `load_object'
	 1: from .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/parser.rb:212:in `load_compressed_object'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/hexapdf-0.24.2/lib/hexapdf/type/object_stream.rb:92:in `object_by_index': Invalid index into object stream given (ArgumentError)
```

I’m not sure if it depends on the contents of the original PDF. Here's a minimal test case that reliably reproduces the error on my machine when used together with [this PDF](https://github.com/gettalong/hexapdf/files/9627726/bug-base.pdf):

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "hexapdf", "0.24.2"
end

File.write("bug-attachment.txt", "")
doc = HexaPDF::Document.new(io: File.open("bug-base.pdf"))
doc.files.add("bug-attachment.txt")
doc.write(StringIO.new(""), validate: false)
```

Versions <= 0.22 appear not to be affected.

**Comment by gettalong** [comment]
Thanks for the issue and the reproducible test case. I can confirm there *is* a bug and my guess is that it is related to the /XRefStm entry of the second revision of the `bug-base.pdf`.

**Comment by gettalong** [comment]
So the problem is that when `validate: false` is used and the file is just written, an object stream is loaded but its content not immediately parsed (method `#parse_stream`). Since the file also has that weird structure with an added empty revision that just references a cross-reference stream via `/XrefStm`, this means that when the original revision where the content *and* the cross-reference stream is located is written, no objects are defined for the object stream and so the information is reset to reflect this. Then the writer wants to write an object that appears in the object stream and can't find it anymore.

I have a work-around that removes this weird, additional revision but I think it would be better to handle this in the object stream object, e.g. by making sure it is parsed when loaded and the information is then also immediately provided to the parser.

**Comment by noniq** [comment]
The PDF was generated by [PrinceXML](https://www.princexml.com/) – if it’s not conforming to spec I could also report an issue there. (However it would still be nice if HexaPDF could work with these PDFs, there are probably quite a lot of them in the wild.)

**Comment by gettalong** [comment]
HexaPDF *will* work with those PDFs :grin: I'm just deciding how many precautions I'm adding to support those PDFs and in which way to represent them.

I think it is a bit of a grey area, the spec says: *"For a file that has never been incrementally updated, the cross-reference section shall contain only one subsection, whose object numbering begins at 0."*. The file has two subsections, "0 6" and "15 28" (the first being the object number and the second the number of entries in the subsection). So in my opinion that is not valid.

The incremental update only consists of the following:

~~~
%%EOF

xref
0 0

trailer
<</XRefStm 36504
/Prev 36651
/Info 41 0 R
/Size 43
/Root 1 0 R
/ID [<825D9FDB2E4142E485AC8B360F441012> <825D9FDB2E4142E485AC8B360F441012>]>>
startxref
37492
%%EOF
~~~

So an empty cross-reference table and a reference to a cross-reference stream that is actually in the *initial revision*. Microsoft Word does something similar but has a valid cross-reference table in the initial revision. Don't know if that is valid... The thing is: One could just place the `/XRefStm 36504` entry in the initial revision...

**Comment by gettalong** [comment]
@noniq Ah, just found this in the spec: *"Therefore, the XRefStm entry shall not be used in the trailer dictionary of the main cross-reference section but only in an update cross-reference section."* So it is actually mandated by the spec to have another revision just for the `/XRefStm`. I still find it weird that the object and cross-reference streams are in the initial revision and not the update one...

**Comment by noniq** [comment]
Weirdness all the way the down … Thanks for taking this deep-dive into this! 🤓

**Comment by gettalong** [comment]
Thanks again for the report!

I have fixed the problem in both places, so when parsing the revisions and in the object stream class itself (it now makes sure that any initially set stream is parsed and the data loaded).

Additionally, I found another bug while testing the bug fixes and fixed that, too :grin:

**Comment by noniq** [comment]
Thank you for fixing this so quickly! 🚀
