### ISSUE TITLE
Do we have mechanism to read PDF S3 URL?

### ISSUE THREAD

**Issue by userrails** [gettalong/hexapdf#194]
Hi @gettalong,

I want to use PDF merge feature to merge PDFs by reading from the S3 URL. Do we have mechanism for that?

I'm expecting something like this:

```
HexaPDF::Document.open(s3_url)
```

I've read this issue: https://github.com/gettalong/hexapdf/issues/136. I wanted to confirm if we have any such feature recently developed.

Thank you.

**Comment by gettalong** [comment]
Using PDFs stored in S3 is orthogonal to this library. HexaPDF has the general mechanism that you can provide an IO object to read a PDF from. So what you need to do is, get an IO object for the S3 URL and pass it to HexaPDF via `HexaPDF::Document.new(io: s3url_io)`.

It doesn't matter to HexaPDF whether the PDF is stored as file, in a database, in S3, ... or just in a `StringIO`. All it cares about is that it gets an IO object.

**Comment by userrails** [comment]
@gettalong Thanks for your response. I'm trying to get I/O object from S3 for that PDF url and I'm passing it inside `HexaPDF::Document.new(io: s3url_io)`.

````Ruby
bucket = Aws::S3::Bucket.new(bucket_name, client: client)
obj = bucket.object(file.path)
````

I've inspected object variable, I am getting the S3 file object.

```
[11] pry(#<HexaPdfDocument>)> obj
=> #<Aws::S3::Object:0x00000001393e5050
 @bucket_name="my_bucket_name",
 @client=#<Aws::S3::Client>,
 @data=nil,
 @key="{my_class_name}/files/000/001/123/original/{my_pdf_name}.pdf",
 @waiter_block_warned=false>
```

I passed that `obj` variable inside `HexaPDF::Document.new(io: obj)`, I ran into this error. Did I make anything wrong?

NoMethodError: undefined method `seek' for #<Aws::S3::Object:0x00000001393e5050>

![image](https://user-images.githubusercontent.com/4639903/191897874-ee9792bd-e93b-4326-96fd-4bf4526093bc.png)

**Comment by gettalong** [comment]
I don't know what an `AWS::S3::Object` is (I have never used S3). You either have to get an IO object or a binary string with the data and wrap that then in a `StringIO`.

**Comment by gettalong** [comment]
@userrails Great - could you write a comment with how you solved so that others may find the solution? Thank you!

**Comment by userrails** [comment]
Hope this feedback will be useful.

#### The arbitrary string.

```
binary_string = Net::HTTP.get(URI.parse("https://example.s3.amazonaws.com/uploads/document.pdf?155463860"))
```

#### StringIO method used to set as the file object 

```
file = StringIO.new(binary_string)
```

#### Create a new PDF document by reading from the provided io

```
HexaPDF::Document.new(io: file)
```

**Comment by userrails** [comment]
@gettalong Hope this feedback will be helpful to everyone.

#### The arbitrary string.

```
binary_string = Net::HTTP.get(URI.parse("https://example.s3.amazonaws.com/uploads/document.pdf?155463860"))
```

#### StringIO method used to set as the file object 

```
file = StringIO.new(binary_string)
```

#### Create a new PDF document by reading from the provided io

```
doc = HexaPDF::Document.new(io: file)
```

#### Writes the document to the given file name.

```
doc.write('document.pdf', optimize: true)
```

**Comment by userrails** [comment]
@gettalong 


I'm able to combine multiple PDFs using following code.

```
@target = HexaPDF::Document.new

bills.each do |inv|
    path = inv.file.url
    t = Tempfile.new([inv.id, '.pdf'])
    t.write(open(path).read.force_encoding(Encoding::UTF_8))
    t.close

    pdf = HexaPDF::Document.open(t.path)
    pdf.pages.each { |page| @target.pages << @target.import(page) }
 end

@target.write('combined.pdf', optimize: true)
```

Without saving PDF on temp location as shown in above code, is it possible to use `HexaPDF::Document.open()` method to accept StringIO object or may be binary string data?

I have multiple PDFs on object `bills` which I want to merge into one PDF. Just curious to know if there are other ways in HexaPDF to merge multiple PDFs.

**Comment by gettalong** [comment]
> @gettalong Hope this feedback will be helpful to everyone.

Thanks, yes!

> #### The arbitrary string.
> 
> ```
> binary_string = Net::HTTP.get(URI.parse("https://example.s3.amazonaws.com/uploads/document.pdf?155463860"))
> ```

Ah, so you are just using the URI without going through the S3 client gem. I think there should be a way to do this with the client gem since it has to be possible to get the contents of some blob stored in there.

**Comment by gettalong** [comment]
> @gettalong
> 
> I'm able to combine multiple PDFs using following code.
> 
> ```
> @target = HexaPDF::Document.new
> 
> bills.each do |inv|
>     path = inv.file.url
>     t = Tempfile.new([inv.id, '.pdf'])
>     t.write(open(path).read.force_encoding(Encoding::UTF_8))
>     t.close
> 
>     pdf = HexaPDF::Document.open(t.path)
>     pdf.pages.each { |page| @target.pages << @target.import(page) }
>  end
> 
> @target.write('combined.pdf', optimize: true)
> ```
> 
> Without saving PDF on temp location as shown in above code, is it possible to use `HexaPDF::Document.open()` method to accept StringIO object or may be binary string data?

The `HexaPDF::Document.open` method only accepts a file name. If you already have an IO object, just use `HexaPDF::Document.new(io: io_object)`.

What you should be able to do is the following:

~~~ ruby
@target = HexaPDF::Document.new

bills.each do |inv|
  open(inv.file_url) do |io|
    pdf = HexaPDF::Document.new(io: io)
    pdf.pages.each {|page| @target.pages << @target.import(page) }
  end
end

@target.write('combined.pdf', optimize: true)
~~~

So if you can use `open` to read `inv.file_url`, you should be able to pass the created IO object directly to HexaPDF.

**Comment by userrails** [comment]
@gettalong 

In combined pdf gem there was mechanism to read the pdf

#### Service Class
````Ruby
      # Add page numbers
      # @pdf.number_pages(location: [:bottom_right], max_font_size: 8)
      # resize each pages to A4 size
      a4_size = [0, 0, 595, 842]
      @pdf.pages.each { |p| p.resize a4_size}
      @pdf = @pdf.to_pdf
````

#### And on controller action 
It converts the pdf and display on the browser.

```
    @pdf.pdf
```


In HexaPDF, I am not exactly getting how to do this.

https://github.com/gettalong/hexapdf/issues/194#issuecomment-1256577643 In this solution, I was able to directly write the IO file and I can read PDF from downloaded source. 

`@target` object is the PDF instance i believe. Is there a way to read PDF content from this @target object so that if I do something like `@target.to_pdf.pdf` I can able to display PDF on browser?

Any hints or documentation please?

**Comment by gettalong** [comment]
I'm not really sure what you mean. My guess is you mean rendering to a string instead of a file? If so, then yes, this is possible, just supply a `StringIO` object when using `HexaPDF::Document#write`.

As for showing it in the browser without downloading: This has nothing to do with HexaPDF, you need to do this in the web framework.
