### ISSUE TITLE
NoMethodError: undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by olegsobchuk** [gettalong/hexapdf#2]
Hi, I've tried merge document with next steps

    target = HexaPDF::Document.new
    ['/path/to/my/file.pdf')].each do |file|
       pdf = HexaPDF::Document.open(file)
       pdf.pages.each_page {|page| target.pages.add_page(target.import(page))}
    end

    target.write("merging.pdf", optimize: true)

but it raise:

    NoMethodError: undefined method `downcase' for nil:NilClass
    from /my/path/gems/hexapdf-0.1.0/lib/hexapdf/serializer.rb:91:in `block (2 levels) in initialize'

**Comment by gettalong** [comment]
This should definitely not happen. However, without the source PDF I can't really do much - can you provide it?

**Comment by olegsobchuk** [comment]
I've tried with different documents, all raise same error. For example I took this [https://wwwimages2.adobe.com/www.adobe.com/content/dam/Adobe/ru/legal/licenses-terms/pdf/PlatformClients_PC_WWEULA-ru_RU-20150407_1357.pdf](https://wwwimages2.adobe.com/www.adobe.com/content/dam/Adobe/ru/legal/licenses-terms/pdf/PlatformClients_PC_WWEULA-ru_RU-20150407_1357.pdf) file

**Comment by gettalong** [comment]
I have tried with your provided document and it works fine. Which Ruby version are you using? Try Ruby 2.3 if you are not using it.

**Comment by olegsobchuk** [comment]
I'm using 
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$ rails -v
Rails 5.0.0.1

**Comment by gettalong** [comment]
Rails version should be irrelevant since the code you presented didn't have anything to do with Rails. However, if this was not the case, try using the code without Rails and see if it works then.

**Comment by gaga5lala** [comment]
I've test merge method with the file provided by @olegsobchuk at both ruby and rails environment, it's work fine. 

* ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
* Rails 4.2.5.2

**Comment by gettalong** [comment]
@gaga5lala Thanks!

**Comment by olegsobchuk** [comment]
I don't know why but in `HexaPDF::Serializer` in initializer when I run `klass.ancestors` it shows me

```
 => [#<Module:0x00000006e79d10>,
 ActiveSupport::NumericWithFormat,
 Fixnum,
 JSON::Ext::Generator::GeneratorMethods::Fixnum,
 ActiveSupport::ToJsonWithActiveSupportEncoder,
 Integer,
 Numeric,
 Comparable,
 ActiveSupport::ToJsonWithActiveSupportEncoder,
 Object,
 PP::ObjectMixin,
 ActiveSupport::Dependencies::Loadable,
 JSON::Ext::Generator::GeneratorMethods::Object,
 ActiveSupport::Tryable,
 Kernel,
 BasicObject]
```

as you can see there is Module and that mace error

**Comment by gettalong** [comment]
Okay, so it seems we found the culprit, namely ActiveSupport prepending modules to built-in classes which shouldn't be done globally - that's what refinements are for.

**Comment by gettalong** [comment]
@olegsobchuk @gaga5lala I have updated the serialization implementation to work around this problem. Please try the code from Github and see if it works with your setup.
