### ISSUE TITLE
Getting the doc/page width

### ISSUE THREAD

**Issue by brandit-dev** [gettalong/hexapdf#200]
I tried to find if doc or page would give me the width of the document/page but couldn't find it.  
I'm sure it's there somewhere. 
Is it possible?

**Comment by gettalong** [comment]
Each page can be of a different size, so this is a property of a page. Therefore see https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Type/Page.html#method-i-box which returns the media box by default.
