### ISSUE TITLE
text alignment lost when flattening acro_form

### ISSUE THREAD

**Issue by andi-dev** [gettalong/hexapdf#221]
Hi again 😄,

in the following pdf the text-alignment of form-fields get lost when flattening the form.

Original PDF:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/152931/207041200-7fa84eb5-6ae0-48c6-84f5-3bfa8292e1c2.png">

Resulting PDF:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/152931/207041402-e3190eb8-aab8-4ad3-8611-bdb3149cc16d.png">

Screenshot from Acrobat:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/152931/207041779-048967c4-1421-41d1-b206-4c771d5bec53.png">

Again, I am not sure how feasible it even is to adapt the various settings of form fields to the copied / created appearances when flattening the form, but I would be curious about your opinion / knowledge.

Thank you a lot in advance, and again: let me know if the original pdf would be helpful.

**Comment by gettalong** [comment]
I'm sorry but apart from the background color I don't really see any difference between these two screenshots. Generally, though, text alignment in form fields is supported, see https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Type/AcroForm/VariableTextField.html#method-i-text_alignment and e.g. https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/type/acro_form/appearance_generator.rb#L409-L413.

So if it is not working in this case, there might be a bug in the implementation or alignment was done differently, in which case having the PDF in question would be very useful.

**Comment by gettalong** [comment]
@andi-dev I need your feedback to resolve this - thanks!

**Comment by andi-dev** [comment]
Hey Thomas, 

I am really sorry! tThis was either not working with a previous version of hexapdf, or - more likely! - with a previous version of my code. And I didn"t even properly check the screenshot again before uploading them here 🙈
