### ISSUE TITLE
Can't serialize special floating point number NaN

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#234]
We ran into an issue with another PDF when flattening. I'll send in the PDF through email...script to reproduce below.

Error: `HexaPDF::Error: Can't serialize special floating point number NaN`

```
require 'hexapdf'
​
document = HexaPDF::Document.open(ARGV[0])
document.pages.each { |page| page.flatten_annotations }
```

**Comment by gettalong** [comment]
Thanks for reporting the bug - I can reproduce it and will fix it.

**Comment by earthlingworks** [comment]
Great, thanks!

**Comment by gettalong** [comment]
This is fixed and will be in the next release.
