### ISSUE TITLE
Contribute documentation

### ISSUE THREAD

**Issue by jalevin** [gettalong/hexapdf#24]
I'd love to contribute some documentation to https://hexapdf.gettalong.org that I think would be useful for new users of the library and newer programmers. What's the best way to get that to you?

**Comment by gettalong** [comment]
The source for the HexaPDF website is available online at https://github.com/gettalong/hexapdf-website. It uses [webgen](https://webgen.gettalong.org) for generating the website.

Many things are automatically generated from files in the HexaPDF repository:

* The whole API documentation (everything under `/api`) from the source code in the `lib/` directory
* The example PDF files and their documentation from the files in the `examples/` directory
* The changelog page from the `CHANGELOG.md` file
* The manual page from the manual page in `man/man1/hexapdf.1.md`
* The benchmark graphs and documentation from the respective files in the `benchmark/` directory

All the files use [kramdown](https://kramdown.gettalong.org) markup where possible.

So, depending on which kind of documentation you want to contribute, it needs to go either to this repo or the website repo. The easiest way would probably be a pull request.

Also see the [contributing page](https://hexapdf.gettalong.org/contributing.html) of the HexaPDF website.
