### ISSUE TITLE
Problem while decoding Flate encoded stream: incorrect header check (HexaPDF::FilterError)

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#241]
Hey Thomas, looks like I forgot to submit this one from a couple of weeks ago. I'll email in the specific PDF - thanks!

Error: `Problem while decoding Flate encoded stream: incorrect header check (HexaPDF::FilterError)`

Script to reproduce:

```require 'hexapdf'
​
hdoc = HexaPDF::Document.open(ARGV[0])
path = 'output.pdf'
​
hdoc.write(path, validate: false, optimize: true)
​
hdoc2 = HexaPDF::Document.open(path)```

**Comment by gettalong** [comment]
Thanks - I will have a look at it!

**Comment by gettalong** [comment]
@earthlingworks I ran you script with the PDF you sent with HexaPDF 0.32.0 but no error was thrown. Which version of HexaPDF were you testing with?

**Comment by earthlingworks** [comment]
Huh, might be on an older version. I'll ask the team to check with the latest version and will follow up. Thanks!
