### ISSUE TITLE
Signatures not recognised as valid when including and image

### ISSUE THREAD

**Issue by jotolo** [gettalong/hexapdf#251]
Hi @gettalong,

I have been using HexaPDF a lot lately and something happen to me when I tried to use some of the functionalities it provides.
First, I was trying to get a valid signature with my certificates using a HSM, we talked about this here: https://github.com/gettalong/hexapdf/issues/187#issuecomment-1611789263 and it worked well. Then, I tried adding an image to the pdf to simulate the signature of a user (something I had working before). 

When this is done, suddenly the signature is not recognised by Adobe anymore, same certificates and keys, nothing changed.
At first, I thought it has something to do with the `external_signing` option. I tried using the private key directly to sign and I got the same result, signature not being recognised by Adobe.
After that, I have tried to not use the `external_signing` mechanism and pass the key directly into the sign method as explained in the documentation. This option also failed. 
At last, I tried the example provided in the [documentation](https://hexapdf.gettalong.org/documentation/digital-signatures/signing-pdfs-howto.html#visual) to add a visual using my private key and that did work without issues.
I tried again the example from the docs, modifying it a bit to include an image (script provided) and again, it didn't work.

```ruby
image = File.new( 'signature.png', 'rb')
doc = HexaPDF::Document.open(Rails.root.join('document.pdf'))
sig_field = doc.acro_form(create: true).create_signature_field('signature')
widget = sig_field.create_widget(doc.pages[0], Rect: [20, 500, 120, 600])
widget.create_appearance.canvas.xobject(image, at: [0, 0], width: 100, height: 100)
doc.sign("signed_with_image.pdf", signature: sig_field,
                                  key: key, 
                                  certificate: certificate,
                                  certificate_chain: [certificate_sub_ca, certificate_root])

```

The image is shown perfectly. The problem is that, for some reason, something changed within the document that affect the signature and the ability for Adobe Reader to recognise it as valid. 
If we skip the image part, the signature is recognised.

Any idea what could be creating this issue?
Thanks in advance

version: hexapdf (0.32.2)

**Comment by gettalong** [comment]
Hmm... I'm not sure why that happens. When viewing it in others viewers it shows correctly. 

What happens if you right click on "Rev. 1: ..." and select "Validate signature"? And what does "Show signature properties" say?

**Comment by gettalong** [comment]
If you run the following code

~~~ ruby
require 'hexapdf'
require HexaPDF.data_dir + '/cert/demo_cert.rb'

image = 'signature.png'
doc = HexaPDF::Document.open('minimal.pdf') # from test/data/minimal.pdf in HexaPDF repo
sig_field = doc.acro_form(create: true).create_signature_field('signature')
widget = sig_field.create_widget(doc.pages[0], Rect: [20, 20, 120, 120])
widget.create_appearance.canvas.xobject(image, at: [0, 0], width: 100, height: 100)
doc.sign("signed_with_image.pdf", signature: sig_field,
                                  key: HexaPDF.demo_cert.key,
                                  certificate: HexaPDF.demo_cert.cert,
                                  certificate_chain: [HexaPDF.demo_cert.sub_ca,
                                                      HexaPDF.demo_cert.root_ca])
~~~

does it have the same effect in Adobe Reader? And does it still have the same effect if you manually trust the HexaPDF demo root certificate?

**Comment by jotolo** [comment]
@gettalong 
I ran the code and I can confirm it does have the same effect in Adobe Reader. 
I manually trusted the HexaPDF demo root certificate  but the result was the same. I tried opening and closing the reader in case it needed to reload the certificates but it shows the same result unfortunately.

The strange thing is, I verified the process with 2 different readers. Once I trusted the HexaPDF certificate in the other reader the signature is shown as valid, same as with our certificate. This does not happen with Adobe Reader.

**Comment by jotolo** [comment]
> What happens if you right click on "Rev. 1: ..." and select "Validate signature"? And what does "Show signature properties" say?

![CleanShot 2023-06-30 at 12 23 57](https://github.com/gettalong/hexapdf/assets/6193238/dcd97202-3ff8-41e1-88d0-cd1d1f26fa29)
![CleanShot 2023-06-30 at 12 25 10](https://github.com/gettalong/hexapdf/assets/6193238/b40cd388-7457-4030-b60f-fbc82ca03e19)

**Comment by jotolo** [comment]
This is the result when used with our certificate and without image. 
What I can see here is that Adobe is not able to recognize the Hash Algorithm nor the Signature Algorithm.
If I repeat the process with our certificate and including the image the same happens, Adobe is not able to recognize Hash nor Signature Algorithms. Without those I think it won't be able to validate the signatures?

![CleanShot 2023-06-30 at 12 28 55](https://github.com/gettalong/hexapdf/assets/6193238/f4dbade5-3880-421f-8ab2-62617f3321ac)

**Comment by gettalong** [comment]
Thanks @jotolo! So Adobe Reader expects a PDF dictionary instance somewhere, I will *just* have to find out where :grin:

As for the problem with the hash and signature algorithms: Those aren't stored in a PDF data structure but in the signature. So my guess is that this information is not correctly shown because of the other error.

**Comment by gettalong** [comment]
@jotolo Oops, that was easier than thought: https://stackoverflow.com/questions/72935931/pdf-signature-expected-a-dict-object describes the problem and has the solution.

Modify the line where the widget's appearance gets created like this:

~~~ ruby
image = widget.create_appearance.canvas.xobject(image, at: [0, 0], width: 100, height: 100)
image[:Resources] = {}
~~~

So we add that unnecessary `/Resources` hash for the image object. I tried it out and it worked for me!

Could you verify that this work for you?

**Comment by jotolo** [comment]
@gettalong It does work! 😄 By adding the `:Resources` to the image Adobe recognise it. I even tried with multiple signers and with multiple signatures, all of them containing an image and all of them worked!

Do you think this assignment should happen internally in HexaPDF? 

Thanks again for checking this so quickly and providing the right guidance. It is really appreciated! 🤝

**Comment by gettalong** [comment]
Thanks for testing this out!

Yes, I think this should be in HexaPDF. However, I *really* dislike adding such work-arounds...

**Comment by jotolo** [comment]
I don't know exactly how it works but maybe it could be the default value for this type of object?
I noticed it didn't have it before. Maybe a simple set up during initialization works.

**Comment by gettalong** [comment]
> I don't know exactly how it works but maybe it could be the default value for this type of object? I noticed it didn't have it before. Maybe a simple set up during initialization works.

Yeah, that could easily be done in [`lib/hexapdf/type/image.rb`](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/type/image.rb) but then the size of all image objects increases, by not much but still. So I wanna first see if I can narrow down this work-around to just images in signatures.

**Comment by gettalong** [comment]
@jotolo I have added the work-around to the method for creating digital signatures. So with the next version of HexaPDF this will now work without any additional fixes on your side.

**Comment by jotolo** [comment]
Thanks @gettalong ! Amazing work!
