### ISSUE TITLE
AT&T/McDonalds blocking hexapdf.gettalong.org

### ISSUE THREAD

**Issue by brandondrew** [gettalong/hexapdf#255]
I don't know if you care, but the WiFi at McDonalds, provided by AT&T is blocking access to [hexapdf.gettalong.org](https://hexapdf.gettalong.org/).

I don't know whether there is legitimately something wrong with the site that is triggering the block, or whether they are just not too bright.  I'm just posting an issue in case you feel it's worth contacting them to get removed from the block list OR figuring out if there's something wrong that might cause this.

**Comment by gettalong** [comment]
Thanks for letting me know - I will see what I can find out.

**Comment by gettalong** [comment]
I have contacted them but haven't heard back. I didn't find anything that is wrong with the website itself, so not sure why it is blocked. Alas, I think there is not much else for me to do, so I'm closing this issue.

**Comment by brandondrew** [comment]
I'll try to remember to check again if I'm in a McDonalds or Starbucks anytime soon (Starbucks uses AT&T too AFAIK).
