### ISSUE TITLE
Annotations are lost instead of flattened on Ghostscript-generated PDF

### ISSUE THREAD

**Issue by justinlara** [gettalong/hexapdf#258]
I am working on an app that ingests and manipulates documents as PDF. We currently run all files through Ghostscript at the point of upload, as we have found this helps remove rough edges and results in files with a more consistent quality. Afterward, we are now trying to flatten any annotations into the file content stream. However, we have found that while the Ghostscript processing retains annotations, using HexaPDF's flattening on the output file removes those annotations entirely rather than flattening them into the document.

This can be replicated with the following CLI commands, using the attached PDF document (or any PDF with annotations) as the initial input:

```bash
gs -dNOPAUSE -dSAFER -dBATCH -sDEVICE=pdfwrite -sOutputFile=<OUTPUT FILEPATH> <INPUT FILEPATH>
hexapdf modify --annotations flatten <INPUT FILEPATH> <OUTPUT FILEPATH>
```

Ghostscript version: 9.56.1
HexaPDF version: 0.32.0

Any guidance would be appreciated, thank you!

[annotated.pdf](https://github.com/gettalong/hexapdf/files/12490727/annotated.pdf)

**Comment by gettalong** [comment]
Thanks for opening the issue and providing the PDF as well as the reproduction script.

When using HexaPDF on the original file, it works as expected. However, I can confirm that it doesn't work on the one modified via Ghostscript. 

A quick investigation shows that Ghostscript modifies the appearance streams of the annotations in a peculiar way.

**Comment by gettalong** [comment]
I found the problem: Ghostscript modifies the annotation's appearances so that they are scaled by a factor of 10. HexaPDF does take this into account when flattening annotations but the problem is that it scales back around the origin and not the bottom-left cornerof the annotation's rectangle.

**Comment by gettalong** [comment]
@justinlara I have fixed the problem and not flattening works for both the original file and the file modified by Ghostscript.

**Comment by justinlara** [comment]
Interesting, I'm surprised that Ghostscript makes such a drastic change to annotations. Thank you very much for looking into this!

**Comment by gettalong** [comment]
Yeah, the change done by Ghostscript basically amounts to scaling all coordinates by a factor of 10, i.e. 59.5 -> 595 :man_shrugging: Which means they also parsed and changed the content stream of the annotation's appearance.
