### ISSUE TITLE
general usage question: control of content flow inside column box

### ISSUE THREAD

**Issue by adas172002** [gettalong/hexapdf#262]
Hello,

I am looking for a way to control flow of content inside columns box. What I mean by that is a way to tell HexaPDF to put part of content I have inside columns box with `columns: 4` argument to start on top of next column. If I understand correctly the way columns box works, I can specify column box height on initialisation and box will be rendered in a way to fill each column and keep them same height not larger than specified on init `height: ddd` argument. Is there a way to achieve this with `children: []` argument?

**Comment by gettalong** [comment]
You can insert an empty box that automatically fills the remaining height of the column to achieve a column break:

~~~ ruby
require 'hexapdf'

HexaPDF::Composer.create('columns.pdf') do |c|
  c.document.config['debug'] = true
  c.column(columns: 4, equal_height: true, height: 200, style: {margin: [0, 0, 20]}) do |col|
    col.lorem_ipsum(sentences: 2)
    col.lorem_ipsum(sentences: 1)
    col.lorem_ipsum(sentences: 3)
    col.lorem_ipsum(sentences: 2)
  end
  c.column(columns: 4, equal_height: true, height: 200) do |col|
    col.lorem_ipsum(sentences: 2)
    col.box(:base)
    col.lorem_ipsum(sentences: 1)
    col.box(:base)
    col.lorem_ipsum(sentences: 3)
    col.box(:base)
    col.lorem_ipsum(sentences: 2)
    col.box(:base)
  end
end
~~~

Will get you this result:
![image](https://github.com/gettalong/hexapdf/assets/4104/2c2462f6-a922-4410-9be8-bba23ba035dc)

**Comment by adas172002** [comment]
Hi Thomas,

You are quick in responses! And they work :-)

Thanks!
