### ISSUE TITLE
Missing pages on output

### ISSUE THREAD

**Issue by NelsonDocsketch** [gettalong/hexapdf#270]
Hi Thomas!

We are having an issue when writing an specific PDF, the output is missing the first page, i'll follow up with the PDF through email. I was able to go around it by re saving the original file with other tools or reconverting the file to PDF using cloudconvert.com

```
require 'hexapdf'

path = 'output.pdf'

document = HexaPDF::Document.open(ARGV[0])

document.write(path, validate: false, optimize: true)
```

**Comment by gettalong** [comment]
Thanks for the issue and the PDF! It is working fine with the devel version of HexaPDF as far as I can tell and may be similar to #261. Could you please try the code in the devel branch?

**Comment by NelsonDocsketch** [comment]
I just tried the devel version and it works fine there!

**Comment by gettalong** [comment]
Great! Then I will close this issue.
