### ISSUE TITLE
Strange behaviour with rescue retry

### ISSUE THREAD

**Issue by MorneL** [gettalong/hexapdf#276]
Hi there,

I'm currently dealing with removing emoji's from strings if the glyphs are not found, I'm aware of font.on_missing_glyph but we want to completely remove the glyph as replacing it with a different glyph is giving us different strange behaviour.

However right now I'm dealing with this issue where I get the following error ONLY when I retry in a rescue. If I run the block inside begin again after the gsub, it's fine, however if I use the retry my document for some reason gets wrapped as a stream.

undefined method `contents=' for #<HexaPDF::Stream:0x000000010ffe87a0>

```
  hexa_pdf_document.acro_form.each_field do |field|
    begin
      field.field_value = "test 😬"
    rescue HexaPDF::MissingGlyphError => glyph_error
      data[field.field_name].gsub!(glyph_error.glyph.str, "")
      retry
    end
  end
```

<img width="1512" alt="Screenshot 2023-12-07 at 09 26 03" src="https://github.com/gettalong/hexapdf/assets/24522538/4fb49452-b4c2-4210-b019-8b7ff21388ac">

The screenshot shows that further down the code it doesn't pass any stream, however it returns as a stream 🤷

**Comment by gettalong** [comment]
Using `Field#field_value=` more than once should definitely be possible, I will take a look at it.

If you have time, could you open another issue for *" I'm aware of font.on_missing_glyph but we want to completely remove the glyph as replacing it with a different glyph is giving us different strange behaviour."*, i.e. what strange behaviour? - Thanks!

**Comment by gettalong** [comment]
@MorneL I have created a small, self-contained example:

~~~ ruby
require 'hexapdf'

doc = HexaPDF::Document.new
form = doc.acro_form(create: true)
field = form.create_text_field('test')
field.create_widget(doc.pages.add, Rect: [10, 10, 100, 30])
data = "test 😬"
begin
        field.field_value = data
rescue HexaPDF::MissingGlyphError => glyph_error
  data = 'test'
        retry
end
doc.write('gh276.pdf')
~~~

This example works as is, i.e. no error is thrown.

Could you provide a self-contained example that shows the problem? My guess is that the used PDF has something to do with the problem.

**Comment by gettalong** [comment]
@MorneL Did you have the chance to look at the problem again and provide a self-contained example?

**Comment by gettalong** [comment]
@MorneL I will close this issue for now. Feel free to open it again with more information or a self-contained example to reproduce the problem.
