### ISSUE TITLE
How to make Khmer language show correctly?

### ISSUE THREAD

**Issue by kuyseng** [gettalong/hexapdf#278]
Hi All;

I'm looking for help about render my native language (Khmer) on PDF. It's wrong in some how. I don't know whether the hexapdf library has option or tweak to make it work correctly.
The text should be "ប្រទេសកម្ពុជា" but it shows up like in below image.

![image](https://github.com/gettalong/hexapdf/assets/771344/6037de59-4426-433f-881c-4290a07be07a)

To type Khmer language, we need to choose Khmer Keyboard first and the font can get from [Google font](https://fonts.google.com/specimen/Khmer):

**Comment by gettalong** [comment]
This has most likely to do with the fact that the characters you write are combined to the correct glyphs by the browser font engine while HexaPDF outputs the characters as glyphs as is.

I'm not familiar with Khmer but if it is possible to pre-combine the characters HexaPDF should be able to output the correct version.

**Comment by gettalong** [comment]
For more information, see e.g. https://harfbuzz.github.io/why-do-i-need-a-shaping-engine.html, especially the third bullet point which may also apply to Khmer.

There is actually a harfbuzz-gem which you may wanna try to use because HarfBuzz is able to do what you want. Also see https://github.com/gettalong/hexapdf/issues/191.

**Comment by kuyseng** [comment]
thanks @gettalong for your direction.
As I search Harfbuzz seem support my Khmer language in [issue](https://github.com/harfbuzz/harfbuzz/issues/972).
Currently I try [harfbuzz-gem](https://github.com/jslabovitz/harfbuzz-gem) but I still get wrong shaping for some cases.
e.g. "កម្ពុជា" seem work fine. but wrong with "ប្រទេស"
I will try to folk [harfbuzz-gem](https://github.com/jslabovitz/harfbuzz-gem) to map some functions such `hb_buffer_set_direction`, `hb_buffer_set_script` & `hb_buffer_set_language` because `hb_buffer_guess_segment_properties` may not well with my text.

![image](https://github.com/gettalong/hexapdf/assets/771344/7f220e78-19f2-490f-a4c4-6f4ec3aa3d0e)

**Comment by gettalong** [comment]
@kuyseng I'm closing this issue for now since this can only be done using a fully-featured font layout engine like HarfBuzz.

**Comment by seanghay** [comment]
Check out: https://github.com/seanghay/sone created to solve this issue.

**Comment by gettalong** [comment]
@kuyseng The next version of HexaPDF will have an optional shaping engine based on HarfBuzz. Your sample text would result in this, first line without shaping, second line with shaping:

<img width="624" height="309" alt="Image" src="https://github.com/user-attachments/assets/2e8be974-a5ac-4a21-8724-45e704d7a5be" />
