### ISSUE TITLE
How we know level DocMDP from the document?

### ISSUE THREAD

**Issue by WSPDV** [gettalong/hexapdf#284]
Hi mas @gettalong 

Can we get the level DocMDP from the already signed document using `.signatures`?

I can get the information on the signature, but I didn't find information about docMDP

<img width="832" alt="image" src="https://github.com/gettalong/hexapdf/assets/95156318/6712acdf-5796-49c4-8b49-8c3bbe1e908f">

Thank you

**Comment by gettalong** [comment]
This information is available in `doc.signatures.first[:Reference].first[:TransformMethod]`, i.e. from the signature reference dictionary of the signature object.

**Comment by WSPDV** [comment]
Thank you mas @gettalong that's very helpful.
But, not necessarily all PDF document has a TransformMethod. How about the level DocMDP if has no TransformMethod method? Is default 2 or 3?

```
signature_dict = doc.signatures.first

# the sigref have possibility null value
sigref = signature_dict[:Reference]&.find {|ref| ref[:TransformMethod] == :DocMDP }
```

**Comment by WSPDV** [comment]
Terima kasih mas @gettalong 🙏🏿
