### ISSUE TITLE
Media, Bleed, Trim, Crop Boxes?

### ISSUE THREAD

**Issue by Phill** [gettalong/hexapdf#29]
I'm wondering if there is a way to set the different box sizes like Media, Bleed, Trim, and Crop?

Thanks!

**Comment by gettalong** [comment]
Sure, have a look at the [API documentation for the Page type](https://hexapdf.gettalong.org/api/HexaPDF/Type/Page.html). There is currently the method `#box` for returning a certain box size. Setting would currently need to be done using the general `#[]=` method, i.e.

~~~ ruby
doc.pages[0].box(:crop) # returns the crop box
doc.pages[0][:CropBox] = [-5, -5, 255, 255] # sets the crop box
~~~

It would probably be helpful to change the `#box` method to `#box(type, value=nil)` to allow setting the value in a consistent way - I will do this for the next release.

**Comment by Phill** [comment]
Ah there's the docs. Didn't find it from a search for some reason.

Thanks again!

**Comment by gettalong** [comment]
@Phill FYI: The next version of HexaPDF will also support setting a box:

~~~
doc.pages[0].box(:crop, [1, 2, 3, 4])
~~~

**Comment by Phill** [comment]
That sounds great!
