### ISSUE TITLE
Remove digital certificate

### ISSUE THREAD

**Issue by WSPDV** [gettalong/hexapdf#290]
Hai mas @gettalong ~ i have a question about how to remove the digital cert without breaking the document?

i already tried some scripts but the document is corrupted.

1. remove the sigflags

```
@doc = HexaPDF::Document.open(path)
@output_file = "tmp/HILANG-#{Time.now.to_i}.pdf"

if @doc.trailer[:Root] && @doc.trailer[:Root][:AcroForm] && @doc.trailer[:Root][:AcroForm][:SigFlags]
  @doc.trailer[:Root][:AcroForm].delete(:SigFlags)
end

@doc.write(@output_file)
```

the result is image's digital signature still exists then there is an error message like the picture below
<img width="537" alt="image" src="https://github.com/gettalong/hexapdf/assets/95156318/9c124024-801a-4376-9847-a0bd2950b701">

2. copy page per page

```
@doc = HexaPDF::Document.open(path)
@output_file = "tmp/HILANG-#{Time.now.to_i}.pdf"

new_pdf = HexaPDF::Document.new
@doc.pages.each { |page| new_pdf.pages << new_pdf.import(page) }

new_pdf.task(:optimize, compact: true, object_streams: :generate,
                        compress_pages: false)
new_pdf.write(@output_file)
```
the result is the same

any suggestion for removing certiface, mas?

**Comment by gettalong** [comment]
The following should do the trick:

~~~ ruby
require 'hexapdf'

HexaPDF::Document.open(ARGV[0]) do |doc|
  doc.acro_form.each_field do |field|
    next unless field.field_type == :Sig
    doc.delete(field.field_value)
    doc.delete(field)
  end
  doc.acro_form.find_root_fields!
  doc.acro_form.signature_unflag(:signatures_exist, :append_only)
  doc.write('/tmp/nosig.pdf', optimize: true)
end
~~~

**Comment by WSPDV** [comment]
is it expected there is information on the deleted signature, mas @gettalong ?

<img width="504" alt="image" src="https://github.com/gettalong/hexapdf/assets/95156318/c77dafb0-6e46-497a-af57-f911c6a62470">

and in the signature panel will show the details below

<img width="290" alt="image" src="https://github.com/gettalong/hexapdf/assets/95156318/2993a0ea-a43d-43dc-b81a-ee0a25609281">


can we remove the image signature and detail certification (not shown on the signature panel)?

**Comment by WSPDV** [comment]
hai mas @gettalong 

I try to combine your code with my code like below

```
require 'hexapdf'

doc = HexaPDF::Document.open(path)
output_file = "tmp/HILANG-#{Time.now.to_i}.pdf"

doc.acro_form.each_field do |field|
    next unless field.field_type == :Sig

    @doc.delete(field.field_value)
    @doc.delete(field)
end

doc.acro_form.find_root_fields!
doc.acro_form.signature_unflag(:signatures_exist, :append_only)
doc.pages.each do |page|
page.delete(:Annots)
end
doc.write(@output_file, optimize: true)
```

the certificate is removed and the annotation does not appear

thank you mas @gettalong

**Comment by gettalong** [comment]
@WSPDV Ah, thanks for the response. My code was missing the deletion of the annotations that were not embedded in the field itself. So one would need to add `field.each_widget {|widget| field.delete_widget(widget) }` before deleting the field itself.

I will add a field deletion method to the main form dictionary to make this use-case easier.
