### ISSUE TITLE
Migration guide from prawn to hexapdf - link appears to be wrong

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/hexapdf#291]
Sers Thomas,

You provide information in the main README as-is:

"If you want to migrate from Prawn to HexaPDF, there is the migration guide with detailed information and examples, comparing the Prawn API to HexaPDF's equivalents."

The URL for the migration guide is this:

https://hexapdf.gettalong.org/documentation/howtos/migrating-from-prawn.html

However had, when I click it, I seem to be redirected towards:

https://hexapdf.gettalong.org/documentation/getting-started/index.html

And once I am on that page, I tried to find the substring "migrat", for that migration
guide, but I can not find that substring. If the file still exists then perhaps it should
be linked in from that website; and the link in the README be corrected.

I actually came to the github issue tracker to see how well the migration guide 
is, because I actually plan to move away from prawn finally (always need to 
struggle through my inertia). I'll retain the old code as-is for prawn, but I
really want to move ALL the prawn code towards hexapdf finally in 2024.

**Comment by gettalong** [comment]
Thanks for noticing that! The correct link is https://hexapdf.gettalong.org/documentation/document-creation/migrating-from-prawn.html, after I re-organized the documentation into topics. I will update the README with the next release which is due today or tomorrow.

The reason why are you redirected to that page is that all non-existing/old links will get you there. You can always try the search box on the top right to find a page.

If you need any help with migrating, please let me know.
