### ISSUE TITLE
In a list containing sub-items, sub-items fitted into a new column or page are bulleted erroneously

### ISSUE THREAD

**Issue by emilyst** [gettalong/hexapdf#295]
Hi, again. After filing #293, I realized you might benefit from knowing about the possible bug we were avoiding by using a table in the first place. This is not an urgent issue, since it can be worked around. I am not even certain if it's a bug or if I've done something wrong.

My original intention had been to create a PDF with a bulleted list. Each list item would contain two sub-items, a "question" and an "answer" (i.e., the output of filling out a survey). The question is always text, but the answer can include text, another list, or even an image.

By using a bulleted list, I was hoping that it would be easy to visually scan for where each group of sub-items began. Unfortunately, I found that if the second sub-item was fitted onto a new column or page, **it would spuriously get assigned its own bullet**.

This defeated the point of using a list at all. Because of this problem, and because of #293, we've decided for the time being to locate all image content in its own section at the end of the PDF.

I know this is a little tough to visualize, so I've included below a minimal example script, along with a PDF rendered using this script, and the image I've been using for testing. I'm also including a screenshot, in case the PDF nor script render for you as they're rendering for me.

----

<img width="781" alt="Screenshot 2024-03-19 at 11 30 16" src="https://github.com/gettalong/hexapdf/assets/528994/6f2cd630-1215-4e40-a7fc-d3df80c704cf">

----

```ruby
# frozen_string_literal: true

require "hexapdf"

file = File.open("test.pdf", "w+")

HexaPDF::Composer.create(file) do |composer|
  composer.list(item_spacing: 12) do |list|
    10.times do
      list.multiple do |item|
        item.lorem_ipsum
        item.image(File.open("stunning.png"), width: 100)
      end
    end
  end
end
```

----

[test.pdf](https://github.com/gettalong/hexapdf/files/14654784/test.pdf)

----

<img width="379" alt="stunning" src="https://github.com/gettalong/hexapdf/assets/528994/27b08177-ac42-45d9-a88e-47f4eb63fe19">

**Comment by gettalong** [comment]
Thanks for reporting this - I can reproduce the bug though with a result that is a little bit different from your output:

![image](https://github.com/gettalong/hexapdf/assets/4104/75a4c238-e970-4977-8bcf-3d688f3c6612)

Will let you know once I find the problem.

**Comment by gettalong** [comment]
I have found the problem and a fix for it:

![image](https://github.com/gettalong/hexapdf/assets/4104/1feab58d-bb37-4cb0-94ec-77597e55b470)

Will test some more and then release a new bug fix version.

**Comment by emilyst** [comment]
Oh, that's great! Thanks so much for looking into this. (Incidentally, I wonder why my HexaPDF version is so far behind. I should try to figure that out today.)

**Comment by gettalong** [comment]
@emilyst I pushed version 0.40.0 with the fix for this bug and two others in list box.

**Comment by emilyst** [comment]
I really appreciate it! This helps a lot.

**Comment by gettalong** [comment]
No problem :smile:

Please let me know if you come across other such cases, thanks!
