### ISSUE TITLE
Linearization

### ISSUE THREAD

**Issue by Niccori250k** [gettalong/hexapdf#300]
Hello,
I heavily use HexaPDF for adding bookmarks to scanned documents and optimizing various files. For this use, since scanned documents generally have their data messed up, it seems better to me that resulting documents be linearized.
So, are there any plans to implement a feature to linearize documents?

**Comment by gettalong** [comment]
Tl;dr: Not planned currently but maybe sometime in the future.

Linearization is only useful in the context of viewing PDFs over a slow connection, there is no other benefit. So if you are just using the PDFs locally, it won't make any sense.

Having said that I currently have no plans to implement linearization. After reading the specification it would be quite a big addition and there are other planned features on the HexaPDF road map for the near future.

Also see https://github.com/gettalong/hexapdf/discussions/226

**Comment by gettalong** [comment]
No problem :smile: If you ran into any pain points using HexaPDF for your tasks, feel free to open an issue.
