### ISSUE TITLE
Suggestion: Add signing_time as a handler option

### ISSUE THREAD

**Issue by vedantj25** [gettalong/hexapdf#311]
Overview
To enhance the flexibility of the HexaPDF DigitalSignature, it is proposed to add a signing_time option. This will allow users to specify the exact time of signing, similar to how the reason field is currently handled.

Rationale
Currently, users can specify the reason, location, and contact_info for signing a PDF document. However, there is no direct way to specify the exact signing time. Adding this feature will allow users to set the signing time explicitly, improving the accuracy and traceability of the signed document.

Thanks in advance for even taking a look at this. This is my first time reporting an issue, and I appreciate your attention to this matter.

**Comment by gettalong** [comment]
Thank you for your input, I think this is a good idea and will implement it.

**Comment by gettalong** [comment]
I have added the option of setting the signing time. The code is live on the devel branch and will be included in the next release.

**Comment by vedantj25** [comment]
Thanks a lot for working on this! 🙏

**Comment by vedantj25** [comment]
Hi @gettalong,
Just wanted to know when we could expect this to go live? I want to use this in my code.
Thanks

**Comment by gettalong** [comment]
@vedantj25 A new release will be done this week.

**Comment by vedantj25** [comment]
Alright, thanks for the update!
