### ISSUE TITLE
StringIO support when opening existing PDF

### ISSUE THREAD

**Issue by kapso** [gettalong/hexapdf#320]
Is this the only way to create `HexaPDF::Document` instance using `StringIO`?

I could not find anything in the docs.

```ruby
form = HTTP.get(FORM_URL).to_s
HexaPDF::Document.new(*[], io: StringIO.new(form))
```

**Comment by gettalong** [comment]
Yes, you can directly pass any IO instance to `HexaPDF::Document.new`. The `HexaPDF::Document.open` method can additionally be used when opening files.
