### ISSUE TITLE
[Suggestions: two in one] Automatically set a default font? And adding an example showcasing a generated .pdf file, via hexapdf, for unicode + emoji symbols/glyphs

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/hexapdf#322]
Omitting setting a font is currently not possible in hexapdf:

    /root/.gem/gems/hexapdf-0.45.0/lib/hexapdf/content/canvas.rb:2714:in `raise_unless_font_set': Operation only allowed if a font is set (HexaPDF::Error)

So we have to add a font specifically. I would like to suggest that in that case, 
where the user omits, a default font is picked that is automatically available on the
computer system. (I tried to use the font Hack, but even when I specified where it
is, I still ran into an issue, due to the next reason.)

I did run into an issue where I was unable to have a glyph corresponding to:

    ₂

be part of the generated .pdf file. hexapdf had some warning about that lower 2
not being an allowed glyph or something like that. I needed the lower glyph for
somechemical formulas, such as **SO₂** ("Schwefeldioxid").

I am using that to autogenerate a .pdf file based on an exam-trainer as well as
for a submodule that helps calculate the molecular weight of chemical formulas.

I believe prawn manages this, whereas hexapdf has some issue - but it may well
be that me is the one that has an issue, due to using hexapdf incorrectly (probably).

I had a look at:

https://hexapdf.gettalong.org/examples/standard_pdf_fonts.html

If you do happen to have some time, could perhaps an additional example be added
that showcases how to use some unicode symbols? I believe lower 2, lower 3 etc...
may be unicode symbols.

These are, from 1 to 9 to 0, the following symbols:

    ₁₂₃₄₅₆₇₈₉₀

If you do happen to add such an example, it would be quite of some help, because then
I know that hexapdf works with these symbols just fine, so I am having an issue locally
on my computer system. This could perhaps be a new subsection, emoji + unicode; you
don't need to showcase everything, just a few examples I would think. Perhaps also the
poop emoji, since it is so important. :D 

It may be useful for other users of hexapdf too, to see how unicode + emojis work in
regards to generated .pdf files. And, it works a tiny bit like a specification too, in that
we can say "yes, unicode and emojis work just fine"; and we can reproduce the code
from the example.

**Comment by gettalong** [comment]
Thanks for the suggestions!

What HexaPDF does depends on the level you are using HexaPDF on:

* The example you linked uses the `HexaPDF::Content::Canvas` methods which are intentionally low-level and provide only the most basic convenience functionality (like checking whether calling the method in the current drawing context is allowed by the PDF specification).

* The high-level functionality provided by the `HexaPDF::Document::Layout` class and the other document layout facilities *do* provide what you seek. See the documentation on the page https://hexapdf.gettalong.org/documentation/api/HexaPDF/index.html for the configuration options 'font.fallback', 'font.map', 'font.on_invalid_glyph', 'font.on_missing_glyph' and the example at https://hexapdf.gettalong.org/examples/composer_fallback_fonts.html.

  In production context one would register a TrueType font (or more) using the `font.map` configuration option and set the font fallback to that TrueType font. This way if a Unicode character is not available as glyph from the selected font, the fallback fonts are tried.

**Comment by gettalong** [comment]
Here is an example for your use-case:

~~~ ruby
require 'hexapdf'

HexaPDF::Composer.create('unicode.pdf') do |composer|
  composer.document.config['font.map'] = {
    'Noto' => {
      none: '/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf',
      bold: '/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf',
    }
  }
  composer.document.config['font.fallback'] = [
    'Noto',
    '/home/thomas/.fonts/NotoEmoji-Regular.ttf',
  ]
  composer.text("SO₁₂₃₄₅₆₇₈₉₀ 💩", font: 'Noto', font_size: 50)
end
~~~

In this example we do the following:

* We register the font NotoSans under the name "Noto" and provide the font file for the regular style and the bold style of the font (we could also add `:italic` and `:bold_italic` styles which are recognized by HexaPDF).
* Next we use that font as first fallback font but add an additional one for Emoji support.
* Then we render text with some regular ASCII characters, Unicode subscript numbers and the poop emoji.

And the result is:

![image](https://github.com/user-attachments/assets/a98c2138-34c2-41d3-a0a5-ee51dd6aa9f1)

If you modify the example and remove `font: 'Noto'` from the `#text` call, the "SO" part would use the standard font Times, the subscript numbers would fall back to the 'Noto' font and the poop emoji would fall back to the Noto Emoji font.
