### ISSUE TITLE
Invalid Certificate

### ISSUE THREAD

**Issue by ainulfitriyah17** [gettalong/hexapdf#324]
hi @gettalong 
I have a problem adding a signature, the document already has a previous certificate and I want to add a new certificate to the same document, I have checked that the document does not have a DocMDP.  However, after the process of adding a new certificate, the old certificate becomes invalid.

This is the result after adding a new certificate:
![image](https://github.com/user-attachments/assets/9b51eb06-9ca9-46a4-aed5-03637150fcbb)

The following is the signature information that I got from the document (before adding a new certificate)
![image](https://github.com/user-attachments/assets/dfed2c47-5194-4551-b114-21eaf0cba5f0)
![image](https://github.com/user-attachments/assets/592f45c5-13f6-4285-809c-49b2c69030e6)

How can I still add new certificates without destroying the existing certificates?
Thanks.

**Comment by gettalong** [comment]
Can you please share the original PDF document?

It is possible that adding a new signature field invalidates the first signature since setting the value of a second existing signature field is different to adding one.

**Comment by ainulfitriyah17** [comment]
Hi @gettalong 
I have sent the original PDF document to your email, please check it. Thank You.

**Comment by gettalong** [comment]
@ainulfitriyah17 Thanks for providing the PDF!

Using the following script:

~~~ ruby
require 'hexapdf'
require 'stringio'
require HexaPDF.data_dir + '/cert/demo_cert.rb'

doc = HexaPDF::Document.open(ARGV[0])
doc.sign('/tmp/out.pdf', reason: "Some reason",
                   certificate: HexaPDF.demo_cert.cert,
                   key: HexaPDF.demo_cert.key,
                   certificate_chain: [HexaPDF.demo_cert.sub_ca,
                                       HexaPDF.demo_cert.root_ca])
~~~

I was able to produce a valid second signature:

![image](https://github.com/user-attachments/assets/cde5da8e-9cb2-4b0b-a35b-1a807c5c3aa6)

So the problem will be in the way you add the second signature.

**Comment by ainulfitriyah17** [comment]
Hi @gettalong thanks for the response. 
After I updated the latest hexapdf version, the issue with the document was solved in this document. But I still have 1 document that is still experiencing the same issue. I ask permission to send other documents that still have issues to your email. Thanks

**Comment by gettalong** [comment]
@ainulfitriyah17 Thank you for the file! I found the problem that makes Adobe Reader thinking the signatures are not valid anymore: The added /DR and /DA keys on the main AcroForm dictionary. You can omit validation by adding `write_options: {validate: false}` to the `Document#sign` method.

I will think about whether HexaPDF can add the two keys only if necesary.

**Comment by ainulfitriyah17** [comment]
thanks @gettalong. The issue has been solved after I added  `{validate: false}` according to your suggestion.

**Comment by gettalong** [comment]
@ainulfitriyah17 The upcoming version of HexaPDF will omit setting the `/DA` (and `/DR`) key on validation, so using validation should be fine again.
