### ISSUE TITLE
Removing XRef streams using :optimize task causes invalid trailer entry, broken signature in Acrobat

### ISSUE THREAD

**Issue by KoffeinFlummi** [gettalong/hexapdf#326]
When you take a PDF containing XRef streams, and you remove those XRef streams using the `:optimize` task, the resulting PDF has a trailer dictionary containing the entry `/Type /XRef`. There are some references in the HexaPDF codebase suggesting that this indicates that the document contains XRef streams (which would be wrong in this case), but by my reading of ISO 32000-2 (7.5.), this is not a valid entry for the trailer dictionary.

This by itself doesn't seem to cause any issues, the PDF looks fine in viewers. If you then sign it, however, Adobe indicates that the signature is broken, giving a "byte range is invalid" message. This also seems to be wrong, since the byte range is perfectly fine. I can only guess at what the cause for that is, but it could be that Adobe tries to "fix" the document somehow, which then causes a change in document size, making the signature byte range invalid.

I think there are actually 2 issues at play here:
- The `:optimize` task should not produce a trailer dictionary containing the `/Type /XRef` entry. Definitely not in this case, and as per my reading of the standard, ever (although there may be circumstances where programs expect it that I'm not aware of).
- Since apparently readers like Adobe are very sensitive to issues with the trailer dictionary, validation should catch (and potentially correct) it, especially when signing. PR is on the way for this change.

Repro (tested with v0.46):

```ruby
# Generate a test pdf. The only thing that matters is that it uses XRef streams.
doc = HexaPDF::Document.new
canvas = doc.pages.add.canvas
canvas.font('Helvetica', size: 100)
canvas.text("Hello World!", at: [20, 400])
doc.write("with_xref_streams.pdf", optimize: true)

# Remove the XRef stream using :optimize
doc = HexaPDF::Document.open("with_xref_streams.pdf")
doc.task(:optimize, object_streams: :delete, xref_streams: :delete)
doc.write("without_xref_streams.pdf")

# The PDF now contains an invalid trailer (contains /Type/XRef):
# trailer
# <</Type/XRef/Size 10 [...] >>
# startxref

# Now we sign it.
pkey = OpenSSL::PKey::RSA.generate(2048)
cert = OpenSSL::X509::Certificate.new
cert.not_before = Time.now
cert.not_after = 10.years.since
cert.public_key = pkey.public_key
cert.subject = cert.issuer = OpenSSL::X509::Name.parse('CN=sigtest')
ef = OpenSSL::X509::ExtensionFactory.new
ef.subject_certificate = cert
ef.issuer_certificate = cert
cert.add_extension(ef.create_extension('basicConstraints', 'CA:FALSE', true))
cert.add_extension(ef.create_extension('keyUsage', 'digitalSignature,nonRepudiation', true))
cert.sign(pkey, 'sha256')

puts cert.to_pem

doc = HexaPDF::Document.open('without_xref_streams.pdf')
signed = StringIO.new
doc.sign(signed, certificate: cert, key: pkey, certificate_chain: [])
signed.rewind
File.binwrite('broken_trailer_signed.pdf', signed.read)

# broken_trailer_signed.pdf shows as a broken signature in Acrobat.
# ("signature byte range is invalid")
```

**Comment by gettalong** [comment]
Thank you for the detailed report!

It is true that the optimization task may be the culprit of leaving a `/Type /XRef` entry around. However, this could happen in other ways, too. Additionally, the XRef and ObjectStreams are not like regular PDF dictionary object types and need special treatment when writing.

I have pushed a change to the devel branch that fixes this and removes the `/Type` entry from any trailer that is not a cross-reference stream.
