### ISSUE TITLE
Digital Signature Versioning

### ISSUE THREAD

**Issue by heruwaspodov** [gettalong/hexapdf#329]
Hi mas @gettalong 

Can the hexapdf versioning file be based on a digital signature like adobe reader? picture below:
<img width="384" alt="image" src="https://github.com/user-attachments/assets/c1bf3597-589d-4970-b58f-7d9ffa92b59b">

I try to loop each the digital signatures that are contained in the pdf and I save in the temp data, but it's not as pdf file. i tried to force the extension but nothing.

<img width="555" alt="image" src="https://github.com/user-attachments/assets/05c0383e-5cff-41c0-b247-089ab1a9b208">

could you give me guidance for this.
thank you.

**Comment by gettalong** [comment]
To be honest I'm not entirely sure what you are saying. I *think* you are asking whether HexaPDF can extract a certain revision of a PDF document that has additions done using incremental updates. If that is the case the answer is yes.

The CLI command `hexapdf inspect file.pdf rev` lists all revisions of a file. You can specify the revision number to extract that specific revision into a file, e.g. `hexapdf inspect file.pdf rev 1 > revision_1.pdf`. The code for this can be seen here https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/cli/inspect.rb#L275-L285.

**Comment by heruwaspodov** [comment]
I'm sorry to confuse you with my question. Thank you for understanding. Yes, you are correct. 
I tried to execute via CLI and that's work. But can we code in the code rails without using CLI? because if we use CLI we exec this command via terminal.

**Comment by gettalong** [comment]
You can see the implementation used by the CLI here: https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/cli/inspect.rb#L275-L285 . The `revision_information` is defined here: https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/cli/inspect.rb#L392-L421. You can use them together to implement this in your Rails application.

**Comment by heruwaspodov** [comment]
thank you mas @gettalong 

i tried on my end, by copying the method that you recommended.

this is my gist https://gist.github.com/heruwaspodov/ba0741cb332f311d23617b962e05facd

all information in `revision_information` can be reached. we can get info on the `end_offset`, but it will error when creating a file.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/e419fe5e-5c29-452e-a0a4-420711ab2f63">

this is an error that appears:
<img width="463" alt="369595609-a1d3b599-cff5-49e0-a859-5ba045c8aab7" src="https://github.com/user-attachments/assets/5ce0ccb1-37c3-42dc-aa39-e5e07d86f70f">
and I tried to save it as a file read, the error does not appear, but the document that was created is corrupted.

**Comment by gettalong** [comment]
If you use a StringIO and then `IO.copy_stream` with it, you can do `io.pos = 0` before `IO.copy_stream` and leave out the last argument to `IO.copy_stream`.

Btw. `@doc.revisions.parser.io` will never be a String.

**Comment by heruwaspodov** [comment]
Thanks a lot, mas @gettalong ~ it's work for me.
May I know what `io.pos` is? and what is the purpose?

**Comment by gettalong** [comment]
@heruwaspodov `io.pos` sets the current IO position in bytes.
