### ISSUE TITLE
Adding a new font with a filepath makes it the font name

### ISSUE THREAD

**Issue by freesteph** [gettalong/hexapdf#333]
Hello, I've been trying to add a custom font to my document but the following fails because HexaPDF uses `'fonts/Arial.ttf` as the font name, i.e the file path rather than the font name.

```rb
# frozen_string_literal: true

require 'hexapdf'

# setup the font
composer = HexaPDF::Composer.new(page_size: :A4, margin: 48)
composer.document.fonts.add('fonts/Arial.ttf')

# setup the style
composer.style(:base, font: 'Arial', font_size: 10, line_spacing: 1.3, last_line_gap: true, padding: [3, 0, 0, 0])

# add some content
composer.text('this is some sample text')

# write out
composer.write('./output.pdf')
```

Would it make sense to apply the following patch? Happy to submit a PR (and add some tests) but wanted to double check with you first.

```diff
modified   lib/hexapdf/document/fonts.rb
@@ -68,7 +68,7 @@ def add(name, **options)
         end
 
         if font
-          @loaded_fonts_cache[[name, options]] = font
+          @loaded_fonts_cache[[font.wrapped_font.full_name, options]] = font
         else
           font_list = configured_fonts.sort.map do |font_name, variants|
             "#{font_name} (#{variants.join(', ')})"
```

**Comment by gettalong** [comment]
When you call `document.fonts.add`, the `name` you provide is interpreted by the registered font loaders. For example, the name "Times" is recognized by the font loader for the built-in standard 14 PDF fonts. And if `name` resolves to a file, another font loader tries to load and add that file as a font.

And you should get the same result when you provide the same arguments. If the internal name of a font was used - as in your proposed patch -, this wouldn't be true anymore. Furthermore, the internal name of a font might be different from the file name and thus would need to be guessed/specially retrieved.

However, there is one font loader that allows specifying nice names for font files and associating variants of a font with the same name. This works through the configuration option `font.map`. See the [PDF/A example](https://hexapdf.gettalong.org/examples/pdfa.html) where this functionality is used to define the "Lato" font in various variants.

**Comment by freesteph** [comment]
Gotcha, thank you for the explanation.
