### ISSUE TITLE
What to do with UnsupportedEncryptionError?

### ISSUE THREAD

**Issue by yfngdu** [gettalong/hexapdf#338]
Hello, I'm working on an app where users can upload files to my service and when I run

```
HexaPDF::Document.new(io: attachment_io)
```

Sometimes I see the error
```
HexaPDF::UnsupportedEncryptionError: Invalid /R value 5 for standard security handler
```

Can someone please advise on what this means? Is it a legitimate pdf file?

**Comment by gettalong** [comment]
Support for that security handler was added in version 0.47.0, so once you update to the latest version, everything should work fine.
