### ISSUE TITLE
Adding DSS Streams

### ISSUE THREAD

**Issue by cw6365** [gettalong/hexapdf#339]
@gettalong how would i got about adding certificate streams in a DSS store like below?

<img width="501" alt="Screenshot 2024-11-08 at 17 24 14" src="https://github.com/user-attachments/assets/f5a352a6-8f6e-48b3-be76-f8ba0f587033">

I have a DER encoded object of the streams i want to insert. Do i use the HexaPDF::Stream | HexaPDF::StreamData ? Do you have any examples of how i would create these please?

**Comment by gettalong** [comment]
Best way would be to use `HexaPDF::Document#add`, like this: `obj = doc.add({}, stream: data_as_string)`.

You would use a `StreamData` object if the data is not already stored in a string but in an IO or a file, see https://hexapdf.gettalong.org/documentation/api/HexaPDF/StreamData.html, e.g. `obj = doc.add({}, stream: HexaPDF::StreamData.new(filename))`.
