### ISSUE TITLE
Question - Update an existing GlyphBox

### ISSUE THREAD

**Issue by AvnerCohen** [gettalong/hexapdf#4]
I want to alter the content of any existing PDF and save a modified version of it.

Is it possible to read a text from a GlyphBox and insert a new text in there, or just delete the whole GlyphBox completely?

The code seem to suggest a GlyphBox is immutable, so I'm not sure what would be a best approach to do that.

**Comment by gettalong** [comment]
Modifying the text of an existing PDF is not easy as exchanging an UTF-8 character for another one, especially when font subsets are used.

There is currently no built-in way to do this. As you have suspected, parsing a content stream is currently a read-only operation.

If you like a functionality like that, please add the needed functionality with a bit more explanation in the Wiki: https://github.com/gettalong/hexapdf/wiki/Roadmap-and-Feature-Requests
