### ISSUE TITLE
Single page PDF based on multiple PDF files

### ISSUE THREAD

**Issue by guineo21** [gettalong/hexapdf#40]
Hello,

Thank you for HexaPDF it's an awesome tool!

I am just wondering if HexaPDF will help me on a specific task. For example I have a 4 Letter Size PDF's 8.5"x11" (1 page posters)  but I want to use HexaPDF to create a one big page PDF 17"x22" with a grid of the four individual pdfs displayed on the one larger pdf.

**Comment by gettalong** [comment]
Sure - you can use the following script to do just that. Save it as `stitch.rb` and invoke it like this `ruby stitch.rb 2 source.pdf output.pdf`.

It assumes that all the equally-sized pages of the source document should be put into N columns into the output document. The size of the output document is automatically calculated from the page size of the source document.

~~~ ruby
#!/usr/bin/env ruby
#
# Usage: stitch.rb column_count source.pdf dest.pdf
#
# Arranges the pages from source.pdf in a pattern where each +column_count+ pages
# are arranged from left to right. It is assumed that all pages are of the same
# size.
#
require 'hexapdf'

columns = ARGV[0].to_i
source_path, dest_path = *ARGV[1, 2]

source = HexaPDF::Document.open(source_path)
dest = HexaPDF::Document.new

rows = (source.pages.count / columns.to_f).ceil
page_width = source.pages[0].box.width
page_height = source.pages[0].box.height

puts "Source pages: #{source.pages.count} pages, #{page_width}pt x #{page_height}pt"
puts "Dest layout: #{columns} columns, #{rows} rows"

canvas = dest.pages.add([0, 0, page_width * columns, page_height * rows]).canvas
row = 1
column = 0
source.pages.each do |page|
  form = dest.import(page.to_form_xobject)
  canvas.xobject(form, at: [column * page_width, page_height * rows - row * page_height])
  column += 1
  if column == columns
    row += 1
    column = 0
  end
end
dest.write(dest_path)
~~~

**Comment by guineo21** [comment]
This is awesome! Thank you very much!
