### ISSUE TITLE
How to change background on a canvas?

### ISSUE THREAD

**Issue by konung** [gettalong/hexapdf#43]
Hi.
I'm playing with hexapdf and simply can't get the canvas background to change (from white), nor the box (TextLyaouter). 

It seems that the API for textbox changed in the past several releases, and examples no longer work. I tried to follow tests, but nothing I try seems to work. 

Since I can modify other params - like alignment, the color of the fonts,  width, height, etc - it seems I'm not completely off the reservation. 

Also when I query `fill_color` it seems to have the color I set, it's just not "painting" it on the canvas. 

Any suggestsions?
Thank you

**Comment by gettalong** [comment]
If you want to change the background color of the canvas, you have to draw a rectangle filling it with the requested color:

~~~ ruby
require 'hexapdf'
doc = HexaPDF::Document.new
canvas = doc.pages.add.canvas
canvas.fill_color(0.5).rectangle(0, 0, canvas.context.box.width, canvas.context.box.height).fill
doc.write('test.pdf')
~~~

Calling the `#rectangle` method doesn't mean anything visibly is done with the created path. You need to fill and/or stroke the created rectangle to have actual results. The reason for this is that path drawing operators can also be used for other things, like drawing soft masks.

Yes, the API for complex text layouting via `TextLayouter` is currently in flux and it seems that I have updated the website with unreleased example code - this is fixed now, sorry for the inconvenience. So the code on the homepage (e.g. https://hexapdf.gettalong.org/examples/text_layouter_styling.html) will now actually work with the latest released version 0.7.0. You might have to force-reload the page to get the updated version.
