### ISSUE TITLE
Get binary content of PDF images

### ISSUE THREAD

**Issue by skurdyukov** [gettalong/hexapdf#45]
Hello!

I want to get pictures from the PDF file to format them. I need their binary contents. Is it possible to get binary contents of images of PDF file using HexaPDF?

Thank.

**Comment by gettalong** [comment]
HexaPDF currently supports JPEG and deflate encoded (think: PNG) images. There are other image formats supported in the PDF specification but they have not been implemented yet.

You can list all images of a file using the hexapdf application, ie. `hexapdf images file.pdf`and extract them with the same command using the command line switch `-e`.

If you want to do it programmatically, you can do something like the following:

~~~ ruby
require 'hexapdf'

doc = HexaPDF::Document.open(filename)
doc.images.each_with_index do |image, index|
  info = image.info
  image.write("image.#{info.extension}") if info.writeable
end
~~~

Does this answer your question?

**Comment by skurdyukov** [comment]
Thank you, it works for me.

`writable` instead `writeable`
