### ISSUE TITLE
Rotating pages in a document

### ISSUE THREAD

**Issue by Phill** [gettalong/hexapdf#48]
Hello again,

I'm trying to figure out how to rotate pages in a document. Some pages are landscape and the rest are portrait. Just want to turn the landscape pages. I'm trying to figure out how to use the canvas.rotate() to do this by looking at the examples in the hexapdf app and the docs, but I just can't figure it out.

Can you provide some simple code for doing it?

Thanks!

**Comment by gettalong** [comment]
Ad rotation: Page rotation can be done by using the `:Rotate` key in a page's dictionary, i.e. without touching the page's contents at all. The value of this key must be ("shall" in ISO terms) a multiple of 90. I will add a `Page#rotate` convenience function for the next release. In the meantime have a look at the [code for the `modify` CLI command](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/cli/modify.rb#L97) to have an example.

Ad landscape: To decide whether a page is landscape or portrait, you have to look at the page's media box *and* the `:Rotate` key to check whether the width is greater than the height. I will also add a convenience method `Page#orientation` for this.
