### ISSUE TITLE
Need to put an image by replacing any text - i.e [IMAGE1]

### ISSUE THREAD

**Issue by ashishprajapati** [gettalong/hexapdf#49]
@gettalong Can I raise a PR for the same ? I have completed that set of work and if you want I can help other people too by collaborating in this repo. I used this gem and enhanced it for allowing ability to put an image at any of the text location. i.e People can use text as a placeholder to replace it by any image.

**Comment by ashishprajapati** [comment]
@gettalong 
Let me know if it make sense and I can raise the PR :) I hope, lots of people really looking for similar things to put an image at particular location by replacing some text. 

i.e
This is my picture below
[image1] 


![screenshot 2018-10-26 at 12 25 09 pm](https://user-images.githubusercontent.com/5468981/47549674-6879f400-d91a-11e8-9620-a8bd2264edba.png)
![screenshot 2018-10-26 at 12 26 33 pm](https://user-images.githubusercontent.com/5468981/47549676-6b74e480-d91a-11e8-8d18-8dff1a50d728.png)

**Comment by gettalong** [comment]
I don't know yet whether it makes sense to include this directly in HexaPDF but have you tried your code with various versions of PDF encoded text? I.e. the `my-cute-dog.pdf` file only represents the optimal case where the to-be-replaced text is available as one string since only text showing operator is used but the text may be split into multiple strings.

Here is your PDF changed in a way that the appearance is the same but the underlying content operations are not: [test2.pdf](https://github.com/gettalong/hexapdf/files/2518432/test2.pdf). Does your code still work?

**Comment by ashishprajapati** [comment]
Hello @gettalong,

First of all, I am very happy to see your views on the stuff. Really appreciated !

Let me clear on the replacing the text first of all. We can replace any of the strings or text with in the pdf with image. It's just an text `[image1]` that I used to replace with image. We can even replace any strings like `Simple` or `A Simple PDF File` with image. 

Yes @gettalong, Code still works in the case that you are asking for :)

I am happy for you to showcase my code to you.

Thanks a lot @gettalong

**Comment by gettalong** [comment]
@ashishprajapati Cool :smile: 

I would suggest that you put your code online in a separate repo and create a rubygem containing a [HexaPDF task](https://hexapdf.gettalong.org/api/HexaPDF/Task/index.html). HexaPDF tasks are self-contained algorithms that work on a document.

This will allow you to develop your code independently from HexaPDF but still have a strong integration with it. I'd be happy to look over your code if you like.

Usage would be something like this:

~~~ ruby
require 'hexapdf'
require 'text_replacer' # <- your library, could also be named hexapdf/task/text_replacer

doc = HexaPDF::Document.new
doc.task(:text_replacer, text: "My cute dog", image: path_to_image)
~~~

**Comment by gettalong** [comment]
@ashishprajapati I will close this issue since there is nothing for me to do here. Once you have your solution available online, please add a comment with a link to your solution so that others find it - thank you.

**Comment by ashishprajapati** [comment]
Thanks a lot @gettalong, Yeah :)

Hello everyone, 
If you are looking for solution to the similar  problem then read my important notes below :)

I have created a new gem using the ‘hexapdf library’. It is itself very much powerful that is allowing my gem to perform it’s operation :) So the gem, I have created is ‘add_image_inside_pdf’ and it is very efficient for the case when we need to replace any text with image within the pdfs. This gem also allows to replace multiple texts with any image in single call.

Please find the github link below:
https://github.com/ashishprajapati/add_image_inside_pdf

‘gem add_image_inside_pdf’

:)

**Comment by gettalong** [comment]
Thanks for open sourcing your code!

I have looked at the files in the repository and your code will work if the PDF was generated in a meaningful way. However, it doesn't work for all cases, for example, out of order text will not be found and there may be other problems. For this you would need to track the location of all text fragments and rearrange them in reading order.

**Comment by ashishprajapati** [comment]
Thanks a lot @gettalong for the feedback.
I understood the problem that you are referring. Yeah, there may be case as you are mentioning if PDF is not generated in a meaningful way. But, I think for the basic need, it's working as I really need it :). I have tested it with so many pdf files and tried putting the image at the text location and found it working in all the cases. I will surely work in the way you are suggesting and will try to improve it accordingly.

**Usecase:**
1. First, it white-outs the text.
2. Then, it puts the image at the text location.

I will ask you for the help :)

Thanks a lot @gettalong
