### ISSUE TITLE
RangeError (integer 256 too big to convert into `unsigned char') on Ruby 2.6.0

### ISSUE THREAD

**Issue by Phill** [gettalong/hexapdf#52]
I just upgraded to Ruby 2.6.0 and I'm getting this new error:

RangeError (integer 256 too big to convert into `unsigned char'):
  
hexapdf (0.8.0) lib/hexapdf/filter/predictor.rb:170:in `setbyte'
hexapdf (0.8.0) lib/hexapdf/filter/predictor.rb:170:in `block (3 levels) in png_execute'
hexapdf (0.8.0) lib/hexapdf/filter/predictor.rb:169:in `upto'
hexapdf (0.8.0) lib/hexapdf/filter/predictor.rb:169:in `block (2 levels) in png_execute'
hexapdf (0.8.0) lib/hexapdf/filter/predictor.rb:247:in `block in png_execute'

**Comment by gettalong** [comment]
Thanks for the report, I have already seen that Ruby 2.6.0 has changed this (see https://bugs.ruby-lang.org/issues/15460). For the time being please don't use 2.6.0 with HexaPDF <= 0.8.0. I will release a new version with the fix soon.

**Comment by gettalong** [comment]
@Phill Fixed with 0.9.0 release!
