### ISSUE TITLE
HexaPDF::Error: Validation error: Required field BaseFont is not set

### ISSUE THREAD

**Issue by AkankshaSh** [gettalong/hexapdf#54]
https://github.com/gettalong/hexapdf/issues/30 is not completely fixed. 
manipulation of a file is not possible coz of the font, Hindi Font(A language in India).
Attached the sample file. 
[sample.pdf](https://github.com/gettalong/hexapdf/files/2724174/sample.pdf)

**Comment by gettalong** [comment]
Sorry, but I don't find a problem with the attached file. Please provide step by step instructions on how to produce the error - thank you!

**Comment by gettalong** [comment]
@AkankshaSh Can you provide more information?

**Comment by gettalong** [comment]
@AkankshaSh I will close this issue because I didn't find a problem with the attached PDF and you didn't provide more information. Feel free to post more information on the issue and I will re-open it.
