### ISSUE TITLE
Is it possible to fill a form?

### ISSUE THREAD

**Issue by xBartu** [gettalong/hexapdf#55]
Hi,

I am trying to fill a pdf form using your gem. However, I couldn't see anything related. Did I miss the related part? I have seen that it has been on your TODO list, however, I have not seen any current update? 

Thanks,
Bartu

**Comment by gettalong** [comment]
You can manually create all the required PDF objects and content streams for forms but there are no convenience methods for this functionality, yet.

There is currently also no ongoing work in this area. However, if there is need to get this functionality sooner than later, I could possibly rearrange development tasks.

**Comment by gettalong** [comment]
@xBartu Just a heads up: The next version of HexaPDF tentatively scheduled for end of June will allow filling out forms using convenience methods.

**Comment by xBartu** [comment]
@gettalong awesome to hear and thanks for the update. Cannot wait to try that.

**Comment by ksocha** [comment]
Hi @gettalong. Are there any news about the next release? We're really looking forward to it! Thanks.

**Comment by gettalong** [comment]
@ksocha Sorry for the delay. I first wanted to release just a basic version of the support but that would have been a half-baked solution. So I implemented support for almost all parts. Just finishing up the CLI command for filling out a form and then will release a new version. You can have a look at the [devel](https://github.com/gettalong/hexapdf/tree/devel) branch to see what's happening.

**Comment by gettalong** [comment]
@xBartu New release with this support is out!
