### ISSUE TITLE
Return a PDF file without saving to disk

### ISSUE THREAD

**Issue by bassambarham** [gettalong/hexapdf#56]
Hi,

In the readme file it states:
>the HexaPDF library can be used for all things PDFs (except for rendering)

Does this mean that there is no way for me to serve a PDF file with "send_data" without saving to disk first?

Thanks

**Comment by gettalong** [comment]
Rendering refers to the display of a PDF page on an output device such as a monitor or printer (or an image file). This is not supported. However, creating/loading and writing PDFs is possible with HexaPDF. See the documentation for [HexaPDF::Document#write](https://hexapdf.gettalong.org/api/HexaPDF/Document/index.html#method-i-write) on how to write to an IO object which could also be a StringIO.

**Comment by maxence33** [comment]
Hi, 
I have the same problem as @bassambarham . Because I use HexaPDF from a Rails app, I can't persist files in the App. I upload them to Amazon AWS S3.
I have found the solution of writing the file to disk then deleting it at the end of the printing method.
Though I am not sure if this will hold over time. I am not too sure either on how to write to a Tempfile or to IO ( the link seems dead. )

Yet congratulations for building this gem. HexaPdf keeps RAM usage pretty low, which is pretty cool considering the cost of RAM at Heroku or in other cloud offers in general.. 
I use HexaPdf for merging, and still use WickedPdf/wkhtmltopdf for printing from layouts but will check if can be done with HexaPdf only.

**Comment by gettalong** [comment]
Thanks! Low RAM usage and good performance are two goals HexaPDF strives for.

The website structure changed in the last two years, here is the correct link to the method: https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Document/index.html#method-i-write.

And here is a minimal example of writing to a `StringIO`:

~~~ ruby
require 'hexapdf'
require 'stringio'

doc = HexaPDF::Document.new
doc.pages.add.canvas.font('Helvetica', size: 20).text('Hello World', at: [100, 100])
io = StringIO.new(''.b)
doc.write(io)
# do something with io.string
~~~

If you need to write to a temp file, you can do it like this:

~~~ ruby
# create doc as above
require 'tempfile'
io = Tempfile.new('some_name_here')
doc.write(io)
# Do something with io
~~~

As for creating PDF documents with HexaPDF: Yes, this is possible. All the basic methods are available through the [HexaPDF::Content::Canvas](https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Content/Canvas.html) class. There is also preliminary support for a more involved layout engine, available under the `HexaPDF::Layout` module. There are some examples on the [HexaPDF homepage](https://hexapdf.gettalong.org/examples/) to see what's currently possible (the various "Text Layouter" examples down to the "Composer" example). The `HexaPDF::Composer` class will become the main entry point for easy PDF creation. It is already usable but is missing more advanced box types like tables or lists.

If you can point me to your Rails app, I can check what would be doable by HexaPDF in its current form.

**Comment by maxence33** [comment]
Thanks a lot @gettalong !!
Both methods do work great
Just with StringIO, it works when I send data to the front using `io.string`
and for Tempfiles using `io.rewind` then passing `io.string` to the `send_data` method
(just precising for future Rails developpers stumbling on the same issue)

Unfortunately the Rails app is currently private but I think I have everything at hand to try render my views to PDF

**Comment by gettalong** [comment]
@maxence33 Great to hear!

Let me know if you need anything else.

**Comment by zackgilbert** [comment]
I know this is older, but it helped me with figuring out how to dynamically render the PDF in a rails action and I figured I'd share for others:

```
require 'hexapdf'
def pdf
    filename = "#{Rails.root}/lib/assets/existing-sample.pdf"
    doc = HexaPDF::Document.open(filename)

    # Do whatever manipulation/canvas overlay stuff you need.
    page1 = doc.pages[0]
    overlay_canvas = page1.canvas(type: :overlay)
    overlay_canvas.fill_color(0,0,0).
      font('Helvetica', size: 16).
      save_graphics_state.
      text("Added Text", at: [180, 320])

    # This will render and force the user to download the file at the provided filename:
    io = StringIO.new(''.b)
    doc.write(io, optimize: true)
    send_data(io.string, filename: "new-filename.pdf", type: 'application/pdf')
end
```
