### ISSUE TITLE
ruby on rails?

### ISSUE THREAD

**Issue by universeonfire** [gettalong/hexapdf#59]
i am kinda newbie in on rails framework looking for a solution to manipulate pdf documents instead of  prawl. can i use this gem in ror? if so how? i tried it but in the end all i can see is an error message cannot load document. 
thanks in advance

**Comment by gettalong** [comment]
FYI: Prawn and HexaPDF cannot directly be compared - they have different use cases and licenses. So depending on what you did with Prawn, it may not (currently) be possible with HexaPDF.

HexaPDF can be used with any application, meaning, it can also be used with Rails. It would help if you could show the code that produced the error and the actual error message/stack trace. Without this information I can't really help you.

**Comment by gettalong** [comment]
@universeonfire I will close this issue for now since you didn't provide enough information to investigate the problem. Please add a note once you can provide the needed information and I will reopen the issue.
