### ISSUE TITLE
NoMethodError: undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by drummman** [gettalong/hexapdf#6]
Hi @gettalong , I'm not able to use the "write" method on a document object. It always raises this exception:

```NoMethodError:` undefined method `downcase' for nil:NilClass```
```from ...gems/hexapdf-0.1.0/lib/hexapdf/serializer.rb:91:in `block (2 levels) in initialize'```

I'm getting this even copying your Hello World example.

Thanks!

**Comment by gettalong** [comment]
Are you by chance using Rails? They are known to change the built-in classes, see #2. But the latest commits on master should help you out.

**Comment by ajcubeta** [comment]
@gettalong - Is there any chance that your (latest commits on master for https://github.com/gettalong/hexapdf) can be updated too and publish to RubyGems?

**Comment by gettalong** [comment]
@ajcubeta The change to fix this is already on Github, see #2. The next gem version will be released once I have finished the items on my work list, probably in two weeks.
