### ISSUE TITLE
FrozenError in HexaPDF::Font::CMap::Writer

### ISSUE THREAD

**Issue by sabrams86** [gettalong/hexapdf#61]
I'm receiving a `FrozenError: can't modify frozen String` in hexapdf/font/cmap.rb:85, I believe as a bug due to the addition of the `# frozen_string_literal: true` comment.

`Writer.new.create_to_unicode_cmap(mapping)`

I'm working on providing an example to reproduce the error, however, it looks like `create_to_unicode_cmap` in hexapdf/font/cmap/writer.rb is attempting to mutate a string in certain circumstances, which would throw this error.  Any string created with `""` is immutable by default due to the `# frozen_string_literal: true` comment. Mutable strings need to be defined as `String.new`.

I'll add an example as soon as I can wrap my head around how my code is getting to this point.

**Comment by gettalong** [comment]
Thank you for reporting this problem, @sabrams86!

I have looked at the source code and found one/the problem. Please have a look at commit 9748468 and try it out.

**Comment by sabrams86** [comment]
@gettalong Thanks for taking a look so quickly! I have verified that this fix resolves the error I was seeing.

**Comment by gettalong** [comment]
@sabrams86 Thanks for your feedback - I have released a bug fix version!
