### ISSUE TITLE
Digital Signature and encryption

### ISSUE THREAD

**Issue by Nerian** [gettalong/hexapdf#62]
Hi!

I need to generate a PDF and sign it with a digital certificate and disallow any changes.

Is this something I can do with Hexapdf?

Thanks!

**Comment by gettalong** [comment]
The signing functionality is on my todo list but not yet implemented. You can currently only encrypt and decrypt documents.

Document generation is possible, have a look at the [HexaPDF::Composer class](https://hexapdf.gettalong.org/examples/composer.html).

**Comment by Nerian** [comment]
Ok, Thanks.
