### ISSUE TITLE
set permission of print to a PDF.

### ISSUE THREAD

**Issue by ramir2426** [gettalong/hexapdf#63]
I need some prototype code that takes a PDF and set permissions of `print` like is shown in the api here: https://hexapdf.gettalong.org/api/HexaPDF/Encryption/StandardSecurityHandler/Permissions.html

**Comment by gettalong** [comment]
You need to use the [`HexaPDF::Document#encrypt`](https://hexapdf.gettalong.org/api/HexaPDF/Document/index.html#method-i-encrypt) method, e.g.

~~~ ruby
require 'hexapdf'

HexaPDF::Document.open('in.pdf') do |doc|
  doc.encrypt(permissions: [:print])
  doc.write('out.pdf')
end
~~~

Also see https://hexapdf.gettalong.org/api/HexaPDF/Encryption/StandardSecurityHandler/EncryptionOptions.html and https://hexapdf.gettalong.org/api/HexaPDF/Encryption/SecurityHandler/index.html#method-i-set_up_encryption.

**Comment by ramir2426** [comment]
Hi @gettalong!! 
How can we give permission with the composer?
example code:

    HexaPDF::Composer.create('composer.pdf') do |pdf|
      pdf.text("this is some text")
    end

**Comment by gettalong** [comment]
@ramir2426 Yes, just use the [HexaPDF::Composer#document](https://hexapdf.gettalong.org/api/HexaPDF/Composer.html#attribute-i-document) method to access the PDF document.
