### ISSUE TITLE
hexapdf doc page configuration.

### ISSUE THREAD

**Issue by ramir2426** [gettalong/hexapdf#64]
1) How to set page content from top instead of bottom in the doc page and how can we give height, width and at parameters in percentage.
also I wanna know what is the default unit of at, height and width is it px, pt etc?
2) how can we set page auto line down/ line spacing instead of every paragraph or line to set at because some line and paras are not adjusting with same styling and sometime overlap so line spacing will be more helpful to me.

please gimme solution about them. Thanks.

**Comment by gettalong** [comment]
Ad 1) If you are using `HexaPDF::Composer`, document content already flows from top to the bottom. What you probably mean is the coordinate system of a PDF page which has its origin at the lower left corner. HexaPDF also uses this convention to make it easier to use low-level graphics routines.

For what would you like to use percentages? And what should be the reference for the percentages?

ad 2) I don't really know what you mean. Can you provide a failing example? HexaPDF supports line spacing. See [HexaPDF::Layout::Style#line_spacing](https://hexapdf.gettalong.org/api/HexaPDF/Layout/Style/index.html#method-i-line_spacing).

**Comment by ramir2426** [comment]
Hi @gettalong !
I want to know what is margin value means exactly is it percentage, pixels, or any thing else in the given example:

    HexaPDF::Composer.create('graphics.pdf', margin: 36) do |pdf|
    end
also would you please refer me how to draw a simple horizontal line (like hr tag in html) with composer object.

Thanks for your worthy time and great effort.

**Comment by gettalong** [comment]
ad 1) It is PDF points, i.e. 72 points equals 1 inch (2.56cm).

ad 2) You need to use `HexaPDF::Composer#draw_box` and create a custom box:

~~~ ruby
require 'hexapdf'

HexaPDF::Composer.create('composer.pdf') do |pdf|
  pdf.text("this is some text")
  hr_box = HexaPDF::Layout::Box.new(height: 20) do |canvas, box|
    canvas.line_width = 0.5
    canvas.stroke_color(225, 225, 225)
    canvas.line(0, 10, box.content_width, 10).stroke
  end
  pdf.draw_box(hr_box)
  pdf.text("this is some other text")
end
~~~

This results in the following:

![composer](https://user-images.githubusercontent.com/4104/55941332-5084fb00-5c42-11e9-8250-505d7629fd58.png)

ad 3) With the next version there will be a ColumnBox that would easily allow side-by-side text. What you may do now is use a floating box for the left text and a normal, right-aligned box for the right text:

~~~ ruby
require 'hexapdf'

HexaPDF::Composer.create('composer.pdf') do |pdf|
  pdf.text("this is some text", position: :float)
  pdf.text("this is some other text", align: :right)
end
~~~

![composer2](https://user-images.githubusercontent.com/4104/55941996-bc1b9800-5c43-11e9-98e3-eccd3ce4aeab.png)


As for fontawesome: Just add the TTF file as font and use it like any other - this
[truetype.pdf](https://github.com/gettalong/hexapdf/files/3067607/truetype.pdf) file is the result of running the truetype example on the fontawesome PDF.

**Comment by ramir2426** [comment]
Thanks @gettalong my first 3 problem are solved as per your great efforts but only one thing is remaining and that is about font (fontawesome) because I need a font with some text  and I wanna do with `Composer` currently I do this but for displaying font using canvas and my position again disturbed.
so please give me a solution to do this. sample of scenario's screenshot attached here.
https://screenshot.net/om3mocg

**Comment by gettalong** [comment]
Make sure the horizontal line box is large enough:

~~~ ruby
 activity_hr_box = HexaPDF::Layout::Box.new(height: 10) do |canvas, box|
    canvas.line_width = 0.5
    canvas.stroke_color(225, 225, 225)
    canvas.line(0, 5, box.content_width, 5).stroke
  end
~~~

**Comment by ramir2426** [comment]
Thanks @gettalong ! you made my day. +1
