### ISSUE TITLE
how to add a another font like chinse?

### ISSUE THREAD

**Issue by genkin-he** [gettalong/hexapdf#69]
thanks for your work.

**Comment by gettalong** [comment]
See [the documentation for the font.map configuration option](https://hexapdf.gettalong.org/api/HexaPDF/index.html) (scroll down a bit). Or you can just provide the filename of the TrueType font file to the `HexaPDF::Content::Canvas#font` method. Or if you are using `HexaPDF::Composer`, set the `font` property of the used style to the TrueType font filename.
