### ISSUE TITLE
Merging several (small) pages of a document in a (bigger) single page

### ISSUE THREAD

**Issue by robjperez** [gettalong/hexapdf#75]
Hi!, First of all thank you for this useful library!

This issue is more a question than an issue, sorry If I posted in the wrong place.

Let's say I have a document with 8, A6 size pages. What I'm trying to do is to have a new document with 2 A4 pages, in each page there will be 4 A6 pages.

I saw that it is possible to treat the pdf document as a xobject, and add it via `canvas.xobject(doc.pdf, at:[])`, however that will just pick the first page of the document and I'm not sure about the quality of the document for print it (the original A6 document has 300dpi).

How should be the best way to do it with hexapdf?

Thanks in advance!

**Comment by gettalong** [comment]
Here is a small script I wrote to help someone on Reddit some time ago. This should probably work for your case, too. If not, the needed changes should be easy to do:

~~~ ruby
#!/usr/bin/env ruby
#
# Usage: stitch.rb column_count source.pdf dest.pdf
#
# Arranges the pages from source.pdf in a pattern where each +column_count+ pages
# are arranged from left to right. It is assumed that all pages are of the same
# size.
#
require 'hexapdf'

columns = ARGV[0].to_i
source_path, dest_path = *ARGV[1, 2]

source = HexaPDF::Document.open(source_path)
dest = HexaPDF::Document.new

rows = (source.pages.count / columns.to_f).ceil
page_width = source.pages[0].box.width
page_height = source.pages[0].box.height

puts "Source pages: #{source.pages.count} pages, #{page_width}pt x #{page_height}pt"
puts "Dest layout: #{columns} columns, #{rows} rows"

canvas = dest.pages.add([0, 0, page_width * columns, page_height * rows]).canvas
row = 1
column = 0
source.pages.each do |page|
  form = dest.import(page.to_form_xobject)
  canvas.xobject(form, at: [column * page_width, page_height * rows - row * page_height])
  column += 1
  if column == columns
    row += 1
    column = 0
  end
end
dest.write(dest_path)
~~~

Hope that helps!

**Comment by robjperez** [comment]
Thanks!

It works like a charm :)

**Comment by gettalong** [comment]
Great! :smile:
