### ISSUE TITLE
Example of linklayer

### ISSUE THREAD

**Issue by danyill** [gettalong/hexapdf#77]
I'd like to do a link annotation between two pages of a pdf (probably using [LinkLayer](https://hexapdf.gettalong.org/api/HexaPDF/Layout/Style/LinkLayer.html)) but my Ruby skills are inadequate.

I've looked at [style.rb](
https://github.com/gettalong/hexapdf/blob/842faf052244ed4d10f04e964e0babb570cf4edc/lib/hexapdf/layout/style.rb#L471) and https://github.com/gettalong/hexapdf/issues/32 which works fine for a URL link.

I'd be very grateful if you could  provide an example of this.

**Comment by iamjohnford** [comment]
Here's an example that might help. You'll want to look at the PDF spec, section 12.3.2.2, to better understand the `:dest` parameter and the different ways you can link to things in the document.

```ruby
require 'hexapdf'

doc = HexaPDF::Document.new

x = 300
y = 500
width = 70
height = 10
radius = 30

# Create a few pages
page1 = doc.pages.add
page2 = doc.pages.add
page3 = doc.pages.add

# Draw some text
page1.canvas.font('Helvetica', size: 10)
page1.canvas.text("Link to Page 3", at: [x, y])
page1.canvas.text("Link to Circle", at: [x, y+30])

# Draw a circle on page 2
page2.canvas.circle(x, y, radius)
page2.canvas.fill

# Create the link to the circle on page 2
# Read the PDF spec section 12.3.2.2 for the dest format details
link = HexaPDF::Layout::Style::LinkLayer.new(dest: [page2, :XYZ, x, y+radius], border: [5, 5, 2])

# Move to the position where we want to draw the link
page1.canvas.translate(x, y+30)

# Place the link on the canvas within this box
link.call(page1.canvas, HexaPDF::Layout::Box.new(width: width, height: height))

# Steps to link to page 3
link2 = HexaPDF::Layout::Style::LinkLayer.new(dest: [page3, :FitH], border: false)
page1.canvas.translate(0, -30)
link2.call(page1.canvas, HexaPDF::Layout::Box.new(width: width, height: height))

doc.write("link.pdf", optimize: true)
```

**Comment by danyill** [comment]
@iamjohnford Thank you so much, that's extremely helpful. I'm back on track.

**Comment by jagondolTirant** [comment]
Is it possible to use it using formatted_text while using Composer?

**Comment by gettalong** [comment]
@jagondolTirant Sure:

~~~ ruby
require 'hexapdf'

HexaPDF::Composer.create('test.pdf') do |c|
  c.formatted_text(['This is ', {link: "https://hexapdf.gettalong.org", text: 'a link'}, " to the homepage."])
  c.formatted_text(['Or like ', {text: 'this', overlays: [[:link, uri: "https://hexapdf.gettalong.org", border: true, border_color: "hp-blue"]]}])
end
~~~

The first way allows an easy way to make a link. The second way allows using the full power of the [LinkLayer](https://hexapdf.gettalong.org/documentation/api/HexaPDF/Layout/Style/LinkLayer.html) class.
