### ISSUE TITLE
Error Optimizing Font

### ISSUE THREAD

**Issue by iamjohnford** [gettalong/hexapdf#78]
I've been testing HexaPDF against a number of crazy PDF files and ran into an error when running using the `optimize` command. It seems to be related to the font optimization portion of the code.

**Test File**

[test-form-fields.pdf](https://github.com/gettalong/hexapdf/files/3626860/test-form-fields.pdf)

**Code**

```
hexapdf optimize test-form-fields.pdf output.pdf
```

**Trace**

```
Problem encountered: undefined method `unpack' for nil:NilClass
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/table.rb:138:in `read_formatted'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/table/directory.rb:76:in `block in load_from_io'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/table.rb:130:in `with_io_pos'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/table/directory.rb:75:in `load_from_io'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/table.rb:79:in `initialize'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/font.rb:97:in `new'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/font.rb:97:in `directory'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/font.rb:91:in `[]'
/gems/hexapdf-0.9.3/lib/hexapdf/font/true_type/optimizer.rb:50:in `build_for_pdf'
/gems/hexapdf-0.9.3/lib/hexapdf/cli/command.rb:263:in `optimize_font'
/gems/hexapdf-0.9.3/lib/hexapdf/cli/command.rb:238:in `block in apply_optimization_options'
/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:415:in `block (2 levels) in each'
/gems/hexapdf-0.9.3/lib/hexapdf/revision.rb:182:in `block in each'
/gems/hexapdf-0.9.3/lib/hexapdf/utils/object_hash.rb:120:in `block in each'
/gems/hexapdf-0.9.3/lib/hexapdf/utils/object_hash.rb:120:in `each'
/gems/hexapdf-0.9.3/lib/hexapdf/utils/object_hash.rb:120:in `each'
/gems/hexapdf-0.9.3/lib/hexapdf/revision.rb:182:in `each'
/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:413:in `block in each'
/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:412:in `reverse_each'
/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:412:in `each'
/gems/hexapdf-0.9.3/lib/hexapdf/cli/command.rb:236:in `apply_optimization_options'
/gems/hexapdf-0.9.3/lib/hexapdf/cli/optimize.rb:76:in `block in execute'
/gems/hexapdf-0.9.3/lib/hexapdf/cli/command.rb:91:in `with_document'
/gems/hexapdf-0.9.3/lib/hexapdf/cli/optimize.rb:74:in `execute'
/gems/cmdparse-3.0.4/lib/cmdparse.rb:885:in `parse'
/gems/hexapdf-0.9.3/lib/hexapdf/cli.rb:134:in `parse'
/gems/hexapdf-0.9.3/lib/hexapdf/cli.rb:58:in `run'
/gems/hexapdf-0.9.3/bin/hexapdf:6:in `<top (required)>'
/bin/hexapdf:23:in `load'
/bin/hexapdf:23:in `<main>'
```

**Comment by gettalong** [comment]
Thanks for reporting this problem!

The file in question contains a reference to an embedded font file. However, only the dictionary portion of that embedded font file is stored (with probably correct length and all) but not the file itself. Therefore an empty string is returned (which should probably not be done).

Will see how to best solve this handling of such malformed PDFs.

**Comment by gettalong** [comment]
I will fix this problem in two steps:

* Prohibiting the automatic conversion of hash objects or simple `HexaPDF::Dictionary` objects into `HexaPDF::Stream` objects so that we get better error messages

* Rescuing from such an error in the CLI command and not optimizing the font.

A side note: You shouldn't use the `--optimize-fonts` switch when optimizing a PDF with an input form since then fully embedded fonts will be stripped of data essential to filling out the form.

**Comment by gettalong** [comment]
I have implemented both changes and pushed to Github. Invalid font objects are now handled gracefully by the optimization code of the CLI commands.

Thanks again for providing these test cases (e.g. #79) and the steps to reproduce - that makes finding the problems and fixes easier.
