### ISSUE TITLE
NoMethodError: undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by mangar** [gettalong/hexapdf#8]
Hey guys, I'm getting the error: NoMethodError: undefined method `downcase' for nil:NilClass when trying to generate a new pdf document by adding a page from another.

The same problem occurs when I'm running the 'Hello World' example.

Bellow the code that I'm trying to run:

    file = "./filepdf.pdf"

    pdf = HexaPDF::Document.open(file)

    page1 = pdf.pages.page(1)

    doc = HexaPDF::Document.new

    doc.pages.add_page(page1)

    doc.write("./newpdf.pdf")

I have tried with different pdf files. And get the same respose.
the version of the library installed is:  hexapdf (0.1.0)

The complete error message is:
    `NoMethodError: undefined method 'downcase' for nil:NilClass
from /usr/local/bundle/gems/hexapdf-0.1.0/lib/hexapdf/serializer.rb:91:in `block (2 levels) in initialize'`

Somebody knows if there is a problem in the library?

**Comment by mangar** [comment]
I have tried with different pdf files. 
And get the same respose

**Comment by mangar** [comment]
Looks that the problem is when I'm using it with Rails (rails console for instance)

**Comment by gettalong** [comment]
@mangar Yeah, its ActiveSupport polluting the namespace. Has already been reported as #2 and fixed, please try the latest version on Github.
