### ISSUE TITLE
Handling page[:Rotate] consistently between pdfs

### ISSUE THREAD

**Issue by danyill** [gettalong/hexapdf#80]
I've got some pages, both are A3 landscape. One has `page[:Rotate]` set to `0` and one has `page[:Rotate]` set to `270`. Visually in a pdf viewer they look identical.

I am manipulating annotations on both pages and wish to use the "canonical" coordinate system (the page coordinates, section 8.3.2.1 of the PDF 1.7 spec) so that I don't need to process the coordinates in a different manner between between the annotations.

I think I need to pre-process all annotations in some fashion. Ultimately I would like `page[:Rotate]` to be set to zero on all pages (or transform the coordinates to allow this).

I thought that after reading #73 perhaps the approach would be to extract [the code](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/type/page.rb#L275-L296) from `page.rotate(ang, flatten: true)` however so far I have not been able to figure it out. I don't want to do any flattening however, just "re-orient" the annotations to allow consistent processing. 

I'd appreciate any pointers.

**Comment by gettalong** [comment]
Have you looked at section 12.5.3 of the PDF 1.7 spec, more specifically bit 5 "NoRotate":

> (PDF 1.3) If set, do not rotate the annotation’s appearance to match the rotation of the page. The upper-left corner of the annotation rectangle shall remain in a fixed location on the page, regardless of the page rotation. See further discussion following this Table."

If you just delete the `/Rotate` key of the page, it will look differently. Setting`flatten: true` makes sure the canvas of the page is rotated so that the overall appearance stays the same.

**Comment by danyill** [comment]
Thanks for the response!

Yes, I did in fact read that section. However I'm dealing with an existing pdf which already has annotations. My basic task is simply to read the position of the annotation and then make a decision.

At the moment I'm working around the different rotations through (too many) if statements based on the `page[:Rotate]` value, something like:

```ruby
page_rotation = page[:Rotate]
if page[:Rotate] == 0
  page_width = page.box.value[2]
  page_height = page.box.value[3]
elsif page[:Rotate] == 270
  page_width = page.box.value[3]
  page_height = page.box.value[2]
else
  puts 'Unknown page rotation' if verbose
end

left, bottom, right, top = *a[:Rect] # annotation rect

# link to x coordinate 10% of page less than required rung where possible
if page_rotation == 0
  min_left = left - 0.1 * @page_width < 0 ? 0 : left - 0.1 * @page_width
elsif page_rotation == 270
  min_left = @page_width - top < 0 ? 0 : @page_width - top - 0.1 * @page_width
end
```

I'm trying to figure out the best way to have everything within a similar coordinate space. 

I suspect within Hexapdf what I need to do is transform everything back to `page[:Rotate]` = `0` so that I can read attributes and apply canvas operations in a consistent manner. But I don't wish to flatten the entire document.

**Comment by gettalong** [comment]
You could probably use [`HexaPDF::Content::TransformationMatrix`](https://hexapdf.gettalong.org/api/HexaPDF/Content/TransformationMatrix.html) to store the needed transformation (based on the page rotation) and then use the `#evaluate` method everywhere to get the correctly transformed coordinates.

**Comment by danyill** [comment]
OK, thanks for the assistance, I'll have a go with that.

**Comment by danyill** [comment]
Thanks for your help, and thanks for this library. I have achieved my task and so am delighted.

To solve my problem I've ended up using my own bespoke methods, partly because I couldn't quite get my mind around what was required to transform coordinates. I also couldn't see that `TransformationMatrix` could help me directly (this is quite likely an error on my part because this is exactly what is described in 8.3.2.3 to go from user space to device space).

Effectively I wrote helper methods to handle the coordinate changes and then to convert back.

Perhaps such helper methods could be a useful future addition to this library. As I understand the spec (8.3.2.3 of PDF32000:2008) the user space coordinates normally are:

```
y
^
|
|
|________> x
```

Put with a page[:Rotate] of 270 degrees they are instead:

```
          x
          ^
          |
          |
y <_______|
```

Additionally with at least my PDFs this has an effect on the way the `:Rect` coordinates come out which means top, left, bottom and right don't appear to be very useful. Ideally I would like to be able to refer everything back to something like the ?device space? (i.e. without worrying about handling of `Page[:Rotate]`)

What complicates this is that even with `page[:Rotate] == 0` the output of hexapdf doesn't seem correct as I understand it (of course I may have missed something important). hexapdf often gives me a value for `right` which appears to be the `left` value.

For instance applying the following snippet to [this pdf file](https://gitlab.com/danyill/pdf-hyperlinking-play/blob/master/spec/fixtures/Line_Prot_Test.pdf), the right value is less than the left value. i.e. typically I would see something like:

```
[119, 377, 105, 477]
[544, 478, 529, 529]
[542, 399, 528, 434]
[541, 118, 528, 362]
[289, 490, 277, 529]
[289, 353, 277, 477]
[128, 838, 96, 1135]
[612, 481, 597, 529]
[610, 399, 596, 434]
```

for the following code:

```ruby
require 'hexapdf'

BASE_PATH = File.dirname(__FILE__)

LINE_TEST_FILE = 'fixtures/Line_Prot_Test.pdf'
TX_TEST_FILE = 'fixtures/Tx_Prot_Test.pdf'

def showAnnotationRects(fileName)

    doc = HexaPDF::Document.open(File.join(BASE_PATH, fileName))

    puts doc.pages[0][:Rotate] # rotation

    doc.pages[0][:Annots].each do |x|
        a = doc.deref(x)
        if a.key? :Rect
            puts a[:Rect].inspect
        end
    end

end

showAnnotationRects(LINE_TEST_FILE)

showAnnotationRects(TX_TEST_FILE)
```

I expected these to be `[left, bottom, right, top]` (the annotation rectangle referred to in Table 164 of the PDF32000:2008 spec and defined in section 4.40 in the same manner as in [the API docs for a rectangle](https://hexapdf.gettalong.org/api/HexaPDF/Rectangle.html)).  

Thanks again for the help and for this library.

**Comment by gettalong** [comment]
HexaPDF doesn't yet have implementations for all annotation types. The provided PDF contains annotations of /Subtype /Square which are not implemented. One of the annotations looks like this:

~~~
<<
  /Border [0 0 0 ]
  /Contents (41)
  /F 64
  /NM (3fde07c3-7d36-4d8c-a3c2b05e08360412)
  /Rect [91 1149 74 1165 ]
  /Subtype /Square
  /T (AutoCAD SHX Text)
>>
~~~

Since the /Type field is missing, HexaPDF doesn't know that this is an annotation and therefore the `a[:Rect]` value is not a Rectangle but just an array. If you change the line `a = doc.deref(x)` to `  a = doc.wrap(doc.deref(x), type: HexaPDF::Type::Annotation)`, you will get an Annotation object and `a[:Rect]` will return a correct Rectangle instance.

I will add a `page.each_annotation` method for the next release to make working with annotations easier.

**Comment by danyill** [comment]
Thank you! It turns out I am relying on the current behaviour to process square annotations and that is likely part of the problem. I'm happy to close this issue.
