### ISSUE TITLE
[Feedback] (Futter zurück) - the new hexapdf release

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/hexapdf#81]
Sorry for the non-english folks - this is just a bit of feedback to Thomas specifically, aka same country/same city feedback. ;)

Ich habe die neue Webseite von hexapdf angesehen i. e.

https://hexapdf.gettalong.org/documentation/tutorials/index.html

Sieht meiner Meinung nach recht gut und übersichtlich aus. Eventuell vielleicht kleine(kleinste)
Änderungen wie grössere Schrift, etwas weniger padding und so, aber das ist zugegebenermassen Ansichtssache (auch da ich eher schlechte Augen habe) und mehr kleine Details - das grosse und ganze finde ich sehr gut.

HexaPDF selbst setze ich (noch?) nicht besonders aktiv ein, primär da ich eher bisserl mit prawn, oder auch ghostscript, verwende (letzteres vor allem für das automatische "splitten" und "joinen" von .pdf Dateien).

Unter der Woche komme ich nicht so einfach dazu in Ruhe Software zu testen, aber ich
schau das ich mal in den nächsten Wochen (Wochenenden) HexPDF intensiver (und vor allem systematischer) testen werde; vielleicht kann ich dann auch etwas besseren Feedback liefern. :)

Bis dahin sollte das einfach nur mal so eine Art "thumbs up" sein (war auch irgendwie einfacher das über einen issue tracker zu machen als per email; sorry - bin absolut chaotisch was emails betrifft, in meinem gmail account sind auch +5000 ungelesene Nachrichten :P).

**Comment by gettalong** [comment]
Danke für das "Futter" :smile: 

Für die Webseite verwende ich jetzt [mini.css](https://minicss.org/), ist klein, übersichtlich und lässt sich gut anpassen. Die Schriftgröße ist die Standard-Schriftgröße, schau es mir an, ob es ein wenig größer für mich auch passt. Was meinst du mit kleine Details?

Die Kommandozeilenapplikation [`hexapdf`](https://hexapdf.gettalong.org/documentation/reference/hexapdf.1.html), die bei der Bibliothek auch dabei ist, kann unter anderem auch splitten und joinen. Vielleicht hilft dir das. Und die Funktionalität werde ich in Zukunft noch ausbauen, z.B. wird es in der nächsten Version eine Möglichkeit geben, aus Bildern (vorerst nur JPG, PNG und PDF selbst) ein PDF zu erzeugen. Und sobald ich die Formular-Funktionalität implementiert habe, möchte ich auch eine Formular-Ausfüll-Funktionalität in die Applikation integrieren.

Testen ist immer gut :smile: Ich habe zwar eine große Testsuite, aber es gibt so viele unterschiedliche Möglichkeiten, PDFs zu erzeugen bzw. zu verunstalten, dass HexaPDF immer wieder Probleme mit manchen Dateien hat. Feedback bzw. problematische Dateien sind immer erwünscht!

**Comment by gettalong** [comment]
Ich schließe den Issue mal, wenn du noch Feedback hast, einfach posten.
