### ISSUE TITLE
Raise on invalid 'settings'

### ISSUE THREAD

**Issue by alexanderadam** [gettalong/hexapdf#82]
I ran into a few Symbol vs String issues and it would be easier to find the cause if proper exceptions would be raised because `nil can't be coerced into Integer` was not very helpful. :wink: 

The issue I ran into in was:

```bash
TypeError:
  nil can't be coerced into Integer
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:853:in `+'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:853:in `block in apply_offsets'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:850:in `each'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:850:in `each_with_index'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:850:in `apply_offsets'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:791:in `block in fit'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:389:in `fixed_width_wrapping'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:341:in `call'
# /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:751:in `fit'
```

which can happen when `style.align` is not `:left`, `:center`, `:right` or `:justify`. However, this could be handled easily because [the method just contains a `case` statement](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/layout/text_layouter.rb#L880-L887).
So something like:

```ruby
def horizontal_alignment_offset(line, available_width)
  case style.align
  when :left then 0
  when :center then (available_width - line.width) / 2
  when :right then available_width - line.width
  when :justify then (justify_line(line, available_width); 0)
  else
    raise ArgumentError, "#{style.align.inspect} is not a valid alignment value (:left, :center, :right, :justify)."
  end
end
```

or similar would make it easier for users of hexapdf to see what is wrong. The same could be applied on [`#initial_baseline_offset`](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/layout/text_layouter.rb#L868-L877) as well.

PS: thank you for your work!
PPS: I didn't see any `gemspec` or `Gemfile` and there seem some dependency missing because I can't even run `rake test`

```
rake test

File does not exist: geom2d

Coverage report generated for Unit Tests to /some/path/hexapdf/coverage. 1233 / 3185 LOC (38.71%) covered.
SimpleCov failed with exit 1rake aborted!
Command failed with status (1)

Tasks: TOP => test
(See full trace by running task with --trace)
```

Otherwise I would have created a PR.

**Comment by gettalong** [comment]
Thanks for the report - I will look into it!

As for dependencies: You need `geom2d` for the layout functionality and therefore the tests (`cmdparse` is only needed for the hexapdf application which has no test code).

The gem is generated by a Rake task, so no gemspec file is needed. However, I can provide a task that generates the gemspec if this is needed. I don't really see a need for a Gemfile or bundler because there won't be problems with dependencies (`cmdparse` and `geom2d` are gems written by me).

And I will update the test task to automatically install the needed dependencies if they are not available.

**Comment by gettalong** [comment]
The reason for not having a gemspec file are two-fold: I'm rather old-fashioned in this way by having a Rakfile with all the tasks that need to be done, like generating a Gem file. And the other reason is that the repo can't be used directly by bundler or similar tools.

Although I try to have the repo in a usable state, I don't guarantee it. So if there were a gemspec, somebody could just use the repo directly and run into problems. If one really wants to use a non-Gem version of HexaPDF, they can clone the repo, generate the gemspec with `rake dev:gemspec` and use their clone. However, for all the tests to run properly there are some binaries like `pngcheck` needed.

**Comment by alexanderadam** [comment]
> I'm rather old-fashioned in this way by having a Rakfile with all the tasks that need to be done, like generating a Gem file

I don't get this point: you could have a `….gemspec` and build the gem with a rake task anyway. It's not like you have to stop building the gem via rake task when you have a `….gemspec`. :wink:
The only thing that would change is that the Rakefile would become smaller and therefore more clear.

> So if there were a gemspec, somebody could just use the repo directly and run into problems.

I'm not getting this point either because you don't have a `….gemspec` and @iamjohnford & me actually ran into problems. :wink: 

So maybe I misunderstood this? :thinking:

**Comment by gettalong** [comment]
I will think about adding the gemspec (and the pros/cons) and come back to you!

**Comment by gettalong** [comment]
@alexanderadam @iamjohnford So, I extracted the code for the gem specification into the `hexapdf.gemspec` so that `rake dev:gem` still works as before. However, `gem build hexapdf.gemspec` won't work because of missing files (several files like the man page are generated by rake). Any pointers on how to solve such an issue?

**Comment by alexanderadam** [comment]
That's great news! Thank you so much! :tada: 

> However, `gem build hexapdf.gemspec` won't work because of missing files

IMHO you could simply [add an extension](https://guides.rubygems.org/specification-reference/#extensions) where you run the the rake task / generate the files.

**Comment by gettalong** [comment]
Hm, it seems that the extensions are run when the gem is installed, i.e. when the gem is already built. We need to run something before the **specification object itself** and the gem are created because the files need to go into the gem.

**Comment by alexanderadam** [comment]
Sorry, my fault. In that case I don't know. If it's just about man pages and files that are not necessary for a local dependency build I would propose to skip it for now (done is better than perfect).

PS: should we move the gemfile discussion into a separate issue? I have the feeling that we are drifting apart from the original issue. :wink:

**Comment by gettalong** [comment]
You are right. The gemspec file would just be used for testing and is not intended to be used in production. In this case we can just provide the minimum information for that to work, e.g. no example files or test files or documentation. I will do that for now and see what comes.

**Comment by gettalong** [comment]
@alexanderadam @iamjohnford I have added the `hexapdf.gemspec` for development/testing purposes - see the [gemspec branch](https://github.com/gettalong/hexapdf/tree/gemspec). Works locally for me. Can you confirm that this would work for you?

**Comment by alexanderadam** [comment]
> @alexanderadam @iamjohnford I have added the `hexapdf.gemspec` for development/testing purposes - see the [gemspec branch](https://github.com/gettalong/hexapdf/tree/gemspec) [](/gettalong/hexapdf/tree/HEAD@{2019-10-11T15:19:57Z}). Works locally for me. Can you confirm that this would work for you?

Works like charm (for me)! Thank you so much for your efforts!
Would you consider adding a single `Gemfile` with this content:

```ruby
source 'http://www.rubygems.org'

gemspec
```

Then it would be just _perfect_.

**Comment by gettalong** [comment]
Thanks for testing!

As far as I know `Gemfile`s are only used by bundler and bundler is used for solving the problem of finding the right versions of dependencies. Since this is not a problem with HexaPDF I see no point in adding this file, sorry. What would the benefits be?

**Comment by alexanderadam** [comment]
> What would the benefits be?

finding the right versions of dependencies for _contributors_. :wink:
This is clearly optional but enables just to execute `bundle` and having everything available.

If you don't want a `Gemfile` that's fine for me as well but then it would be nice to add a `.gitignore` that includes the `Gemfile`.
This way someone could have a `Gemfile` and won't have it as a git change or so.

**Comment by gettalong** [comment]
@alexanderadam Will think about the `.gitignore`.

But back to the original topic: I have implemented the value checking but not at the place where the values are used but directly when setting a value on the style object. This way you will get an error if you set an invalid value, making it easy to spot the problem location. Otherwise, you would know that there is an invalid value but would have to search for it to see where you set it.

**Comment by alexanderadam** [comment]
Thank you! :+1:
