### ISSUE TITLE
Two line breaks lead to `No font set (HexaPDF::Error)`

### ISSUE THREAD

**Issue by alexanderadam** [gettalong/hexapdf#85]
I took [`007-truetype.rb`](https://github.com/gettalong/hexapdf/blob/master/examples/007-truetype.rb) as an example and modified it a bit (added a layouter). It works perfectly fine until you try to render two line breaks (i.e. `"\n\n"`).
See this small example

```ruby
require 'hexapdf'

doc = HexaPDF::Document.new
font = doc.fonts.add(File.join(__dir__, '../test/data/fonts/Ubuntu-Title.ttf'))
canvas = doc.pages.add.canvas

text_fragment = HexaPDF::Layout::TextFragment.create("this is broken\n\n", { font: font })
text_layouter = HexaPDF::Layout::TextLayouter.new
text_layouter.style.align(:left).valign(:top)
text_layouter.fit([text_fragment], 100, 100).draw(canvas, 300, 300)

doc.write("truetype.pdf", optimize: true)
```

<details>
  <summary>Backtrace (Click to expand)</summary>

```
Traceback (most recent call last):
  16: from examples/007-truetype.rb:27:in `<main>'
  15: from /…/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:751:in `fit'
  14: from /…/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:341:in `call'
  13: from /…/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:389:in `fixed_width_wrapping'
  12: from /…/hexapdf-0.10.0/lib/hexapdf/layout/text_layouter.rb:786:in `block in fit'
  11: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:278:in `height'
  10: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:263:in `y_max'
   9: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:329:in `calculate_y_dimensions'
   8: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:329:in `new'
   7: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:99:in `initialize'
   6: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:99:in `each'
   5: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:99:in `block in initialize'
   4: from /…/hexapdf-0.10.0/lib/hexapdf/layout/line.rb:106:in `add'
   3: from /…/hexapdf-0.10.0/lib/hexapdf/layout/text_fragment.rb:218:in `y_min'
   2: from /…/hexapdf-0.10.0/lib/hexapdf/layout/style.rb:1038:in `scaled_y_min'
   1: from /…/hexapdf-0.10.0/lib/hexapdf/layout/style.rb:1033:in `scaled_font_descender'
/…/hexapdf-0.10.0/lib/hexapdf/layout/style.rb:914:in `font': No font set (HexaPDF::Error)
```
</details>

**Comment by gettalong** [comment]
The reason for the error message is that you didn't set a font for the `TextLayouter#style` instance. If you use `... TextLayouter.new(text_fragment.style)` it will work.

Rationale: Before the text is layed out, it is broken down into segments, in this case `this`, ` `, `is`, ` `, `broken`, `\n`, `\n`. During layout the first `\n` signals a paragraph break, no error here. When the second `\n` is encountered, there has nothing been layed out on the current line - it is empty. However, the text layouter still needs to determine a height for this empty line. It does so by consulting the font set in its style. And here the error occurs because no font is set.

**Comment by alexanderadam** [comment]
This feels somehow inconsistent, doesn't it?

The `TextFragment` is the only item in the `TextLayouter`. And the string is part of the `TextFragment`.
When the text of the `TextFragment` is broken into segments it's already known what the `TextFragment` has a certain font. Meaning: every part of the string (including the 'paragraph break') of the `TextFragment` should have the font of the `TextFragment`.

Otherwise the calculation would probably be wrong anyway.
If `TextFragment` and `TextLayouter` have different fonts assigned in this case (say Ubuntu font in the fragment and MS Comic Sans in the layouter) everything would be calculated by the Ubuntu font metrics _except_ a new paragraph / empty line which would be calculated by the metrics of MS Comic Sans.

IMHO this would be clearly a bug if this is the case.

**Comment by gettalong** [comment]
The TextLayouter is completely separate from text fragments. You provide the fragments, width and height in the `#fit` method and the layouter lays out the fragments. Note that the fragments may not be text fragments but any kind that fulfills the contract, for example, inline boxes. Those don't need to have a font set. How would the text layouter know the height of an empty line in this case?

I see your point, however, and will see how to make this more consistent - thanks for pointing this out! :+1:

**Comment by gettalong** [comment]
@alexanderadam I have implemented this now and it will work as you described. Additionally, the fallback behaviour is retained to handle the cases where line breaks are manually inserted (ie. not generated by the text of a text fragment).

Thanks for raising this issue and pointing out the problem! :+1:

**Comment by alexanderadam** [comment]
Thank you! :tada:

**Comment by beneggett** [comment]
I ran into this issue after upgrading to `0.14.1` 

Changing 
```
page_text = HexaPDF::Layout::TextLayouter.new.fit( [content], text_w, text_h)
```

to 

```
base_style = {font: font, font_size: font_size}
page_text = HexaPDF::Layout::TextLayouter.new(base_style).fit( [content], text_w, text_h)
```

resolved it.
