### ISSUE TITLE
Option to decode pdf into objects

### ISSUE THREAD

**Issue by mnithya** [gettalong/hexapdf#87]
I'm looking for a way to decode/uncompress a pdf file into objects similar to what qpdf does.

I realized the code snippet mentioned [here](https://github.com/gettalong/hexapdf/issues/68) is for extracting text from a pdf document and does not necessarily return the uncompressed file itself. Is there currently anything in the public API to do this? 

Basically looking for something that turns a compressed pdf file into individual objects like so:
```
%PDF-1.7
1 0 obj
  << /Type /Catalog
     /Pages 2 0 R
  >>
endobj

2 0 obj
  << /Type /Pages
     /Kids [3 0 R]
     /Count 1
  >>
endobj

xref
0 3
00000000000 65535 f
00000000010 00000 n
00000000069 00000 n
trailer
  << /Root 1 0 R
     /Size 3
  >>
startxref
249
%%EOF
```

It seems using one of the [Filter functions](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/filter.rb) would be useful, but couldn't find examples on how to use them. 

```ruby
file = File.open("test.pdf", 'rb')
pdfFiber = HexaPDF::Filter.source_from_string(file.read)
returnedPDF = HexaPDF::Filter::FlateDecode.decoder(pdfFiber)
# how do you parse through the returnedPDF?
```

**Comment by gettalong** [comment]
You can use the [`:optimize` task](https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Task/Optimize.html) to do this, or just use the command line application: `hexapdf modify input.pdf --object-streams delete --xref-streams delete output.pdf`.
