### ISSUE TITLE
PDF rectangle structure error when writing to a PDF

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#88]
We have a PDF that we can open fine with Acrobat reader and other tools/applications. But for some reason, when we try to write to it, we're seeing this error:

"ArgumentError: A PDF rectangle structure must contain an array of four numbers"

The PDF itself seems to have been created by Acrobat 18. Here's a link to download that PDF: [https://cl.ly/1b64e55d01f9](https://cl.ly/1b64e55d01f9)

This is the line of code that's writing to the file: 
`output_pdf.write(file, validate: false, optimize: true)`

**Comment by gettalong** [comment]
Thanks for the bug report!

I think I found the reason (numbers of some rectangles are stored as indirect objects instead of direct object) - will see how best to solve this!

**Comment by earthlingworks** [comment]
That's great! Thanks so much for the fast response 👍

**Comment by gettalong** [comment]
FYI: To solve this problem for more/all cases I will introduce a new array wrapper class similar to how hashes are wrapped in `HexaPDF::Dictionary` classes. This wrapper will automatically resolve references to avoid this problem.

**Comment by gettalong** [comment]
@earthlingworks I have implemented this and processing the provided PDF now works. Depending on the code that uses HexaPDF this may be a breaking change, especially if `obj.kind_of?(Array)` is used.

**Comment by earthlingworks** [comment]
@gettalong Excellent! Thanks so much...this is great :)

**Comment by earthlingworks** [comment]
@gettalong Question: not sure how this works but I'm guessing the fix will be in an upcoming release? Or is there a way we get access to that otherwise? (we have a paid license)

**Comment by gettalong** [comment]
@earthlingworks There is one more thing I would like to include in the next release, so you can expect a new version to be released in the next few days.

However, I have just pushed the latest commits to Github and those include a change that allows using HexaPDF via bundler directly from the git repository. Note, though, that this feature should only be used for testing/development purposes, only use proper releases in production.

**Comment by earthlingworks** [comment]
@gettalong Great; thank you!

**Comment by earthlingworks** [comment]
@gettalong This seems related to the wrapping of arrays, but this is just a method we we're calling on an object (not familiar with the code much since I didn't write it, but that dev isn't around anymore). Seems like it's breaking but not in the way you mentioned? Or it is, we would just get at the page height in a different way? Here's the specific error: https://share.getcloudapp.com/xQuvy4Ln

**Comment by gettalong** [comment]
Hm... it is strange that it returns a `HexaPDF::PDFArray` instance instead of `HexaPDF::Rectangle`. I just ran some code and that works just fine. Can you reproduce the problem outside of your application code by running the following in your Ruby environment:

~~~
require "hexapdf"
HexaPDF::Document.open(SOME_PDF_FILE").pages.each_with_index {|pa, i| p pa.box.height}
~~~

This should result in one line with the height in PDF points per page.

**Comment by earthlingworks** [comment]
It works on most PDFs, but seems to keep happening on a few specific PDFs. Going to try to run that and will give you an update - just will take a bit to get one of the source PDFs that's having that problem.

**Comment by earthlingworks** [comment]
@gettalong Yep, I'm seeing the same problem from the console: https://share.getcloudapp.com/2NuAn1nP

**Comment by earthlingworks** [comment]
@gettalong Here's an example PDF that is having that problem: https://share.getcloudapp.com/4gu7dY7x

**Comment by gettalong** [comment]
Thanks for the PDF in question!

I have found the problem and pushed a bug fix release (0.11.2) to address the problem. Please test if it works for you - thanks!

**Comment by earthlingworks** [comment]
That was fast! Perfect - works great :) 

Thanks for being so responsive!

**Comment by gettalong** [comment]
No problem, glad I could help so fast!
