### ISSUE TITLE
HexaPDF::Document pages.add_page error

### ISSUE THREAD

**Issue by ajcubeta** [gettalong/hexapdf#9]
Hi thomas,

I've updated my gem to 0.2.0 lately for test-demo, but I'm stuck on the "add_page" method.

```
require 'hexapdf'

doc = HexaPDF::Document.new
canvas = doc.pages.add_page.canvas
```

I got this error message:

NoMethodError: undefined method `add_page' for #<HexaPDF::Document::Pages:0x007fe72d065b00>
	from (irb):3

**Comment by ajcubeta** [comment]
Nevermind, I think you change the implementation methods
https://github.com/gettalong/hexapdf/blob/master/examples/hello_world.rb

**Comment by gettalong** [comment]
Yes, it now has a more Ruby like interface as mentioned in the changelog by being a separate class.
