### ISSUE TITLE
Finding root fields causes Nil Class exception

### ISSUE THREAD

**Issue by kprinssu** [gettalong/hexapdf#91]
I get an ```
*** NoMethodError Exception: undefined method `each' for nil:NilClass```
 error when trying to get root fields of a document. 

I believe that I have narrowed down the issue to this line, https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/type/acro_form/form.rb#L70. Certain pages (on malformed PDFs?) may not have the `:Annots` key and `page[:Annot]` will be nil.

**Comment by gettalong** [comment]
Thanks for the report - you are completely right. The `/Annots` key may not be set on all pages, so this is a bug. I have fixed it and pushed and new version.
