### ISSUE TITLE
Problem with ruby 2.4

### ISSUE THREAD

**Issue by julbouln** [gettalong/hexapdf#92]
Hi,
I found a compatibility issue with ruby 2.4 in hexapdf/rectangle.rb after_data_change and perform_validation methods.

It raises `all?: wrong number of arguments (given 1, expected 0) (ArgumentError)`

all? does not seems to accept 1 argument in ruby 2.4 https://apidock.com/ruby/v2_4_6/Enumerable/all%3F
replacing `all?(Numeric)` by `all?{|v| v.is_a?(Numeric)}` fix the problem.

Regards

**Comment by gettalong** [comment]
Thanks for reporting this. Since Ruby 2.4 has its EOL date next year in March, I will just bump the required Ruby version to 2.5.

**Comment by julbouln** [comment]
Too bad, we wanted to get a commercial license to use hexapdf, but we can't possibly manage to migrate all our infrastructure to ruby 2.5. It seems we will need to find another solution.

**Comment by gettalong** [comment]
If it is important to you that Ruby 2.4 is still supported, I will have a look at the code base and dependent gems. The original target was 2.4, so most of the code should still be 2.4 compatible.

**Comment by gettalong** [comment]
@julbouln It seems that your found problem as well as one in a dependent gem were the only 2.4 compatibility issues. I have already released geom2d version 0.3.1 to fix it there and will release a bug fix version of HexaPDF later.

**Comment by julbouln** [comment]
Thank you !
As a small business, we really need longer term support for ruby versions. We often have a lot of greater priority than updating our large ageing application to recent ruby versions. As evidence, we only migrated from 2.1 to 2.4 this year.
If you tell us that you can continue maintaining hexapdf for ruby 2.4, we will take a license.

**Comment by gettalong** [comment]
@julbouln I just pushed 0.11.3 with the fix for Ruby 2.4. Together with geom2d 0.3.1 HexaPDF can now be used on 2.4 again.

Please note, however, that I won't maintain 2.4 compatibility forever. There were some big improvements from 2.3 to 2.4, so there was a good reason to switch to 2.4. The improvements in 2.5, 2.6 and 2.7 are currently no reason to switch, however (only the EOL of 2.4).

**Comment by julbouln** [comment]
Thanks, @gettalong !
