### ISSUE TITLE
Extracting embedded PDF images

### ISSUE THREAD

**Issue by dennyluan** [gettalong/hexapdf#94]
Is there a way to neatly extract embedded PDF images from a document, e.g. by doing something like `doc.images`? Currently images that are in a document that are embedded PDF are not included.

**Comment by gettalong** [comment]
I'm sorry but I don't understand the question. All images in the PDF except those defined directly in content streams can be iterated via `doc.images`. What do you mean by "embedded PDF images"?

**Comment by dennyluan** [comment]
Ah sorry, the only way I can describe it is with an [example PDF](https://github.com/gettalong/hexapdf/files/3982601/extracting.pdf) that was built from LaTeX with embedded images that are PDF files. When listing the images, the vector graphics part of the images don't appear in the documents image list.

**Comment by gettalong** [comment]
Thanks for the PDF! I see what you mean: That a page from one PDF is used as kind of image in another PDF. Alas, these "images" are not really images according to the PDF spec but so called Form XObjects which work similar to PDF pages but can, for example, be re-used on multiple pages. HexaPDF itself also provides the functionality to import PDF pages for use as a kind of image.

It is not really possible to know which Form XObject was originally from an other PDF file and therefore constitutes a vector image. However, it is certainly possible to extract such Form XObjects into separate PDF files.

**Comment by dennyluan** [comment]
Thanks! I guess a follow up question then is it possible to extract the vector images from a PDF like this: [example.pdf](https://github.com/gettalong/hexapdf/files/3985548/example.pdf)

**Comment by gettalong** [comment]
It seems that this is a simple one page PDF file where the only page *is* the image you would like to extract - correct? In that case it depends on what you mean by "extract"?

The PDF file itself can already be considered a vector image. For example, Adobe Illustrator saves (or saved, don't know the current state of affairs) its vector images in PDF format, albeit with some custom extensions.

If you want to convert the PDF into an image format like SVG, you could use Inkscape (should also be possible via the command line).

**Comment by dennyluan** [comment]
Got it, thanks again. Yeah I was thinking along the lines of converting into an SVG or PNG.
