### ISSUE TITLE
Extracting transparent PNGs replaces with a black background

### ISSUE THREAD

**Issue by dml-1** [gettalong/hexapdf#95]
It looks like when trying to extract images, if there's a PDF with transparent png images, it gets extracted with a black background. An example of a PDF is [attached here](https://github.com/gettalong/hexapdf/files/3982595/parsrc.pdf).

Is it possible to extract them with the transparency preserved?

**Comment by gettalong** [comment]
Image soft-masks which are used for transparent images are currently not supported - I will fix the image support detection to make this clear.

**Comment by gettalong** [comment]
Images with soft masks are now flagged as not writable. Some kinds of transparency are supported but full soft masks are not. This will be implemented in a future version.
