### ISSUE TITLE
Get coordinates of image

### ISSUE THREAD

**Issue by t4t5** [gettalong/hexapdf#99]
Hi and thanks for this great library!

I'm trying to generate a copy of an existing PDF file, and replace all of its images with black boxes. I can find lots of documentation of how to do similar things with text strings through `decode_text_with_positioning`, but I can't find an equivalent for images?

Extracting a document's images through `doc.images` gives you some info, but not the image's coordinates as far as I can see. Is there any way to get an image's position so that I know where to draw my `canvas.rectange`?

Any pointers would be appreciated! 🙏

**Comment by t4t5** [comment]
Found a way to find the coordinates through [pdf-reader](https://github.com/yob/pdf-reader/issues/114).

**Comment by gettalong** [comment]
If you still haven't decided whether to use pdf-reader, here is a small script that draws a border around each found image.:

~~~ ruby
require 'hexapdf'

class ImageBorderProcessor < HexaPDF::Content::Processor

  def initialize(page)
    super()
    @canvas = page.canvas(type: :overlay)
  end

  def paint_xobject(name)
    super
    xobject = resources.xobject(name)
    return unless xobject[:Subtype] == :Image
    w, h = xobject.width, xobject.height
    llx, lly = graphics_state.ctm.evaluate(0, 0)
    lrx, lry = graphics_state.ctm.evaluate(1, 0)
    urx, ury = graphics_state.ctm.evaluate(1, 1)
    ulx, uly = graphics_state.ctm.evaluate(0, 1)
    @canvas.line_width = 0.5
    @canvas.stroke_color(224, 0, 0)
    @canvas.polyline(llx, lly, lrx, lry, urx, ury, ulx, uly).close_subpath.stroke
  end

end

doc = HexaPDF::Document.open(ARGV.shift)
doc.pages.each_with_index do |page, index|
  processor = ImageBorderProcessor.new(page)
  page.process_contents(processor)
end
doc.write('imagebox.pdf', optimize: true)
~~~

**Comment by t4t5** [comment]
That's way cleaner! Thank you so much @gettalong!
